# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-27T18:07:47+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class SnapshotCreationFailed(BaseModel):
    EventCategories: list[str]
    EventID: str
    Message: str
    SourceArn: str
    SourceIdentifier: str
    SourceType: str


class ElasticacheSnapshotCreationFailedEvent(BaseModel):
    account: str
    detail: SnapshotCreationFailed
    detail_type: str = Field(..., alias='detail-type')
    id: str
    region: str
    resources: list[str]
    source: str
    time: AwareDatetime
    version: str
