# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T17:10:12+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class CodePipelineStageExecutionStateChange(BaseModel):
    """
    Detail payload for a stage execution state-change event.
    """

    #: Pipeline execution identifier.
    execution_id: str = Field(..., alias="execution-id")
    #: Pipeline name.
    pipeline: str
    #: Attempt number for this pipeline execution.
    pipeline_execution_attempt: float | None = Field(
        None, alias="pipeline-execution-attempt"
    )
    #: Stage execution start timestamp.
    start_time: AwareDatetime | None = Field(None, alias="start-time")
    #: Stage name.
    stage: str
    #: New stage execution state.
    state: str
    #: Pipeline structure version associated with event.
    version: float


class CodepipelineCodePipelineStageExecutionStateChangeEvent(BaseModel):
    """
    Top-level EventBridge envelope for CodePipeline stage execution changes.
    """

    #: AWS account that emitted event.
    account: str
    #: Event detail payload.
    detail: CodePipelineStageExecutionStateChange
    #: EventBridge detail type.
    detail_type: str = Field(..., alias="detail-type")
    #: EventBridge event identifier.
    id: str
    #: AWS region where event was emitted.
    region: str
    #: Event resources list.
    resources: list[str]
    #: Event source identifier.
    source: str
    #: Event timestamp.
    time: AwareDatetime
    #: Event envelope version.
    version: str
