# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T17:10:10+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class ExecutionTrigger(BaseModel):
    """
    Trigger metadata attached to a CodePipeline execution event.
    """

    #: Detail describing actor or source that triggered execution.
    trigger_detail: str = Field(..., alias="trigger-detail")
    #: Trigger category reported by CodePipeline.
    trigger_type: str = Field(..., alias="trigger-type")


class CodePipelinePipelineExecutionStateChange(BaseModel):
    """
    Detail payload for a pipeline execution state-change event.
    """

    #: Pipeline execution identifier.
    execution_id: str = Field(..., alias="execution-id")
    #: Trigger metadata for execution when present.
    execution_trigger: ExecutionTrigger | None = Field(
        None, alias="execution-trigger"
    )
    #: Pipeline name.
    pipeline: str
    #: Attempt number for this pipeline execution.
    pipeline_execution_attempt: float | None = Field(
        None, alias="pipeline-execution-attempt"
    )
    #: New pipeline execution state.
    state: str
    #: Pipeline execution start timestamp.
    start_time: AwareDatetime | None = Field(None, alias="start-time")
    #: Stop comment when present.
    stop_execution_comments: str | None = Field(
        None, alias="stop-execution-comments"
    )
    #: Pipeline structure version associated with event.
    version: float


class CodepipelineCodePipelinePipelineExecutionStateChangeEvent(BaseModel):
    """
    Top-level EventBridge envelope for CodePipeline pipeline execution changes.
    """

    #: AWS account that emitted event.
    account: str
    #: Event detail payload.
    detail: CodePipelinePipelineExecutionStateChange
    #: EventBridge detail type.
    detail_type: str = Field(..., alias="detail-type")
    #: EventBridge event identifier.
    id: str
    #: AWS region where event was emitted.
    region: str
    #: Event resources list.
    resources: list[str]
    #: Event source identifier.
    source: str
    #: Event timestamp.
    time: AwareDatetime
    #: Event envelope version.
    version: str
