# ruff: noqa: ERA001, Q000
# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T17:10:08+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class ExecutionResult(BaseModel):
    """
    External execution metadata attached to an action event.
    """

    #: External system execution identifier.
    external_execution_id: str | None = Field(None, alias='external-execution-id')
    #: Human-readable external execution summary.
    external_execution_summary: str | None = Field(
        None, alias='external-execution-summary'
    )
    #: URL to external execution details.
    external_execution_url: str | None = Field(None, alias='external-execution-url')


class S3Location(BaseModel):
    """
    S3 artifact location reported for an action artifact.
    """

    #: S3 bucket name.
    bucket: str
    #: S3 object key.
    key: str


class Type(BaseModel):
    """
    CodePipeline action type descriptor.
    """

    #: CodePipeline action category.
    category: str
    #: Action owner.
    owner: str
    #: Action provider.
    provider: str
    #: Action type version.
    version: str


class ArtifactReference(BaseModel):
    """
    Artifact reference attached to an action event.
    """

    #: Artifact name.
    name: str
    #: Artifact S3 location.
    s3location: S3Location


class CodePipelineActionExecutionStateChange(BaseModel):
    """
    Detail payload for an action execution state-change event.
    """

    #: Action name.
    action: str
    #: Action execution identifier.
    action_execution_id: str | None = Field(None, alias="action-execution-id")
    #: Pipeline execution identifier.
    execution_id: str = Field(..., alias="execution-id")
    #: External execution metadata when present.
    execution_result: ExecutionResult | None = Field(None, alias="execution-result")
    #: Input artifact references.
    input_artifacts: list[ArtifactReference] | None = Field(
        None, alias="input-artifacts"
    )
    #: Output artifact references.
    output_artifacts: list[ArtifactReference] | None = Field(
        None, alias="output-artifacts"
    )
    #: Pipeline name.
    pipeline: str
    #: Attempt number for this pipeline execution.
    pipeline_execution_attempt: float | None = Field(
        None, alias="pipeline-execution-attempt"
    )
    #: AWS region where action ran.
    region: str
    #: Action start timestamp.
    start_time: AwareDatetime | None = Field(None, alias="start-time")
    #: Stage name.
    stage: str
    #: New action execution state.
    state: str
    #: Action type descriptor.
    type: Type
    #: Pipeline structure version associated with event.
    version: float


class CodepipelineCodePipelineActionExecutionStateChangeEvent(BaseModel):
    """
    Top-level EventBridge envelope for CodePipeline action execution changes.
    """

    #: AWS account that emitted event.
    account: str
    #: Event detail payload.
    detail: CodePipelineActionExecutionStateChange
    #: EventBridge detail type.
    detail_type: str = Field(..., alias="detail-type")
    #: EventBridge event identifier.
    id: str
    #: AWS region where event was emitted.
    region: str
    #: Event resources list.
    resources: list[str]
    #: Event source identifier.
    source: str
    #: Event timestamp.
    time: AwareDatetime
    #: Event envelope version.
    version: str
