# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T20:06:56+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class ACMCertificateRevoked(BaseModel):
    CertificateExpirationDate: AwareDatetime
    CertificateType: str
    CommonName: str
    Exportable: bool


class ACMACMCertificateRevokedEvent(BaseModel):
    account: str
    detail: ACMCertificateRevoked
    detail_type: str = Field(..., alias='detail-type')
    id: str
    region: str
    resources: list[str]
    source: str
    time: AwareDatetime
    version: str
