# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T20:06:48+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class ACMCertificateAvailable(BaseModel):
    Action: str
    CertificateCreatedDate: AwareDatetime
    CertificateExpirationDate: AwareDatetime
    CertificateType: str
    CommonName: str
    DaysToExpiry: float
    DomainValidationMethod: str | None = None
    Exportable: bool | None = None
    Exported: bool
    InUse: bool


class ACMACMCertificateAvailableEvent(BaseModel):
    account: str
    detail: ACMCertificateAvailable
    detail_type: str = Field(..., alias='detail-type')
    id: str
    region: str
    resources: list[str]
    source: str
    time: AwareDatetime
    version: str
