# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T20:06:45+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class ACMCertificateApproachingExpiration(BaseModel):
    DaysToExpiry: float
    Exportable: bool | None = None


class ACMACMCertificateApproachingExpirationEvent(BaseModel):
    account: str
    detail: ACMCertificateApproachingExpiration
    detail_type: str = Field(..., alias='detail-type')
    id: str
    region: str
    resources: list[str]
    source: str
    time: AwareDatetime
    version: str
