# This file is automatically generated by botocraft.  Do not edit directly.
# mypy: disable-error-code="index, override, assignment, union-attr, misc"
from botocraft.services.bedrock_agentcore_control import Content
from pydantic import Field
from datetime import datetime
from typing import ClassVar, Literal, Any, Type as ModelType, cast
import builtins
from .abstract import PrimaryBoto3ModelQuerySet
from .abstract import (
    Boto3Model,
    ReadonlyBoto3Model,
    PrimaryBoto3Model,
    ReadonlyPrimaryBoto3Model,
    Boto3ModelManager,
    ReadonlyBoto3ModelManager,
)
from botocraft.mixins.tags import TagsDictMixin

# ===============
# Managers
# ===============


class AgentCoreEventManager(Boto3ModelManager):
    service_name: str = "bedrock-agentcore"

    def create(
        self,
        model: "AgentCoreEvent",
        clientToken: "str | None" = None,
        extractionMode: "Literal['SKIP'] | None" = None,
    ) -> "AgentCoreEvent":
        """
        Creates an event in an AgentCore Memory resource.

        Events represent interactions or activities that occur within a session and are
        associated with specific actors.

        Args:
            model: The :py:class:`Event` to create.

        Keyword Args:
            clientToken: A unique, case-sensitive identifier to ensure that the
                operation completes no more than one time. If
                this token matches a previous request, AgentCore ignores the request,
                but does not return an error.
            extractionMode: Controls long-term memory extraction for this event. When
                set to ``SKIP``, the event is stored in
                short-term memory but is excluded from long-term memory extraction. If
                not specified, the event is processed for
                extraction as usual.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            memoryId=data.get("memoryId"),
            actorId=data.get("actorId"),
            eventTimestamp=data.get("eventTimestamp"),
            payload=data.get("payload"),
            sessionId=data.get("sessionId"),
            branch=data.get("branch"),
            clientToken=self.serialize(clientToken),
            metadata=data.get("metadata"),
            extractionMode=self.serialize(extractionMode),
        )
        _response = self.client.create_event(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = CreateEventOutput(**_response)

        self.sessionize(response.event)
        return cast("AgentCoreEvent", response.event)

    def get(
        self, memoryId: str, sessionId: str, actorId: str, eventId: str
    ) -> "AgentCoreEvent | None":
        """
        Retrieves information about a specific event in an AgentCore Memory resource.

        Args:
            memoryId: The identifier of the AgentCore Memory resource containing the
                event.
            sessionId: The identifier of the session containing the event.
            actorId: The identifier of the actor associated with the event.
            eventId: The identifier of the event to retrieve.
        """
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            sessionId=self.serialize(sessionId),
            actorId=self.serialize(actorId),
            eventId=self.serialize(eventId),
        )
        _response = self.client.get_event(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetEventOutput(**_response)

        if response and response.event:
            self.sessionize(response.event)
            return response.event
        return None

    def list(
        self,
        memoryId: str,
        sessionId: str,
        actorId: str,
        *,
        includePayloads: "bool | None" = None,
        filter: "FilterInput | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists events in an AgentCore Memory resource based on specified criteria.

        We recommend using pagination to ensure that the operation returns quickly and
        successfully.

        Args:
            memoryId: The identifier of the AgentCore Memory resource for which to list
                events.
            sessionId: The identifier of the session for which to list events.
            actorId: The identifier of the actor for which to list events.

        Keyword Args:
            includePayloads: Specifies whether to include event payloads in the
                response. Set to true to include payloads, or
                false to exclude them.
            filter: Filter criteria to apply when listing events.
        """
        paginator = self.client.get_paginator("list_events")
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            sessionId=self.serialize(sessionId),
            actorId=self.serialize(actorId),
            includePayloads=self.serialize(includePayloads),
            filter=self.serialize(filter),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListEventsOutput(**_response)
            if response.events:
                results.extend(response.events)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, memoryId: str, sessionId: str, eventId: str, actorId: str) -> None:
        """
        Deletes an event from an AgentCore Memory resource.

        When you delete an event, it is permanently removed.

        Args:
            memoryId: The identifier of the AgentCore Memory resource from which to
                delete the event.
            sessionId: The identifier of the session containing the event to delete.
            eventId: The identifier of the event to delete.
            actorId: The identifier of the actor associated with the event to delete.
        """
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            sessionId=self.serialize(sessionId),
            eventId=self.serialize(eventId),
            actorId=self.serialize(actorId),
        )
        self.client.delete_event(**{k: v for k, v in args.items() if v is not None})


class AgentCorePaymentInstrumentManager(Boto3ModelManager):
    service_name: str = "bedrock-agentcore"

    def create(
        self,
        model: "AgentCorePaymentInstrument",
        agentName: "str | None" = None,
        clientToken: "str | None" = None,
    ) -> "AgentCorePaymentInstrument":
        """
        Create a new payment instrument for a connector.

        Args:
            model: The :py:class:`PaymentInstrument` to create.

        Keyword Args:
            agentName: The agent name associated with this request, used for
                observability.
            clientToken: A unique, case-sensitive identifier that you provide to ensure
                the idempotency of the request.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            paymentManagerArn=data.get("paymentManagerArn"),
            paymentConnectorId=data.get("paymentConnectorId"),
            paymentInstrumentType=data.get("paymentInstrumentType"),
            paymentInstrumentDetails=data.get("paymentInstrumentDetails"),
            userId=data.get("userId"),
            agentName=self.serialize(agentName),
            clientToken=self.serialize(clientToken),
        )
        _response = self.client.create_payment_instrument(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = CreatePaymentInstrumentResponse(**_response)

        self.sessionize(response.paymentInstrument)
        return cast("AgentCorePaymentInstrument", response.paymentInstrument)

    def get(
        self,
        paymentManagerArn: str,
        paymentInstrumentId: str,
        *,
        userId: "str | None" = None,
        agentName: "str | None" = None,
        paymentConnectorId: "str | None" = None,
    ) -> "AgentCorePaymentInstrument | None":
        """
        Get a payment instrument by ID.

        Args:
            paymentManagerArn: The ARN of the payment manager that owns this payment
                instrument.
            paymentInstrumentId: The ID of the payment instrument to retrieve.

        Keyword Args:
            userId: The user ID associated with this payment instrument.
            agentName: The agent name associated with this request, used for
                observability.
            paymentConnectorId: The ID of the payment connector.
        """
        args: dict[str, Any] = dict(
            paymentManagerArn=self.serialize(paymentManagerArn),
            paymentInstrumentId=self.serialize(paymentInstrumentId),
            userId=self.serialize(userId),
            agentName=self.serialize(agentName),
            paymentConnectorId=self.serialize(paymentConnectorId),
        )
        _response = self.client.get_payment_instrument(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetPaymentInstrumentResponse(**_response)

        if response and response.paymentInstrument:
            self.sessionize(response.paymentInstrument)
            return response.paymentInstrument
        return None

    def list(
        self,
        paymentManagerArn: str,
        *,
        userId: "str | None" = None,
        agentName: "str | None" = None,
        paymentConnectorId: "str | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        List payment instruments for a manager.

        Args:
            paymentManagerArn: The ARN of the payment manager that owns the payment
                instruments.

        Keyword Args:
            userId: The user ID associated with the payment instruments.
            agentName: The agent name associated with this request, used for
                observability.
            paymentConnectorId: The ID of the payment connector to filter by.
        """
        paginator = self.client.get_paginator("list_payment_instruments")
        args: dict[str, Any] = dict(
            paymentManagerArn=self.serialize(paymentManagerArn),
            userId=self.serialize(userId),
            agentName=self.serialize(agentName),
            paymentConnectorId=self.serialize(paymentConnectorId),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListPaymentInstrumentsResponse(**_response)
            if response.paymentInstruments:
                results.extend(response.paymentInstruments)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(
        self,
        paymentManagerArn: str,
        paymentConnectorId: str,
        paymentInstrumentId: str,
        *,
        userId: "str | None" = None,
    ) -> None:
        """
        Deletes a payment instrument.

        This is a soft delete operation that preserves the record for audit and
        compliance purposes.

        Args:
            paymentManagerArn: The payment manager ARN. Must match the instrument's
                paymentManagerArn.
            paymentConnectorId: The payment connector ID. Must match the instrument's
                paymentConnectorId.
            paymentInstrumentId: The payment instrument ID to delete.

        Keyword Args:
            userId: The user ID making the delete request. Must match the instrument's
                userId.
        """
        args: dict[str, Any] = dict(
            paymentManagerArn=self.serialize(paymentManagerArn),
            paymentConnectorId=self.serialize(paymentConnectorId),
            paymentInstrumentId=self.serialize(paymentInstrumentId),
            userId=self.serialize(userId),
        )
        self.client.delete_payment_instrument(
            **{k: v for k, v in args.items() if v is not None}
        )


class AgentCorePaymentSessionManager(Boto3ModelManager):
    service_name: str = "bedrock-agentcore"

    def create(
        self,
        model: "AgentCorePaymentSession",
        agentName: "str | None" = None,
        clientToken: "str | None" = None,
    ) -> "AgentCorePaymentSession":
        """
        Create a new payment session.

        Args:
            model: The :py:class:`PaymentSession` to create.

        Keyword Args:
            agentName: The agent name associated with this request, used for
                observability.
            clientToken: A unique, case-sensitive identifier that you provide to ensure
                the idempotency of the request.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            paymentManagerArn=data.get("paymentManagerArn"),
            expiryTimeInMinutes=data.get("expiryTimeInMinutes"),
            userId=data.get("userId"),
            agentName=self.serialize(agentName),
            limits=data.get("limits"),
            clientToken=self.serialize(clientToken),
        )
        _response = self.client.create_payment_session(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = CreatePaymentSessionResponse(**_response)

        self.sessionize(response.paymentSession)
        return cast("AgentCorePaymentSession", response.paymentSession)

    def get(
        self,
        paymentManagerArn: str,
        paymentSessionId: str,
        *,
        userId: "str | None" = None,
        agentName: "str | None" = None,
    ) -> "AgentCorePaymentSession | None":
        """
        Get a payment session.

        Args:
            paymentManagerArn: The ARN of the payment manager that owns this session.
            paymentSessionId: The ID of the payment session to retrieve.

        Keyword Args:
            userId: The user ID associated with this payment session.
            agentName: The agent name associated with this request, used for
                observability.
        """
        args: dict[str, Any] = dict(
            paymentManagerArn=self.serialize(paymentManagerArn),
            paymentSessionId=self.serialize(paymentSessionId),
            userId=self.serialize(userId),
            agentName=self.serialize(agentName),
        )
        _response = self.client.get_payment_session(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetPaymentSessionResponse(**_response)

        if response and response.paymentSession:
            self.sessionize(response.paymentSession)
            return response.paymentSession
        return None

    def list(
        self,
        paymentManagerArn: str,
        *,
        userId: "str | None" = None,
        agentName: "str | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        List payment sessions.

        Args:
            paymentManagerArn: The ARN of the payment manager that owns the sessions.

        Keyword Args:
            userId: The user ID associated with the payment sessions.
            agentName: The agent name associated with this request, used for
                observability.
        """
        paginator = self.client.get_paginator("list_payment_sessions")
        args: dict[str, Any] = dict(
            paymentManagerArn=self.serialize(paymentManagerArn),
            userId=self.serialize(userId),
            agentName=self.serialize(agentName),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListPaymentSessionsResponse(**_response)
            if response.paymentSessions:
                results.extend(response.paymentSessions)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(
        self,
        paymentManagerArn: str,
        paymentSessionId: str,
        *,
        userId: "str | None" = None,
    ) -> None:
        """
        Deletes a payment session.

        This permanently removes the payment session record.

        Args:
            paymentManagerArn: The payment manager ARN. Must match the session's
                paymentManagerArn.
            paymentSessionId: The payment session ID to delete.

        Keyword Args:
            userId: The user ID making the delete request. Must match the session's
                userId.
        """
        args: dict[str, Any] = dict(
            paymentManagerArn=self.serialize(paymentManagerArn),
            paymentSessionId=self.serialize(paymentSessionId),
            userId=self.serialize(userId),
        )
        self.client.delete_payment_session(
            **{k: v for k, v in args.items() if v is not None}
        )


class AgentCoreMemoryRecordManager(Boto3ModelManager):
    service_name: str = "bedrock-agentcore"

    def batch_create(
        self,
        memoryId: str,
        records: "builtins.list[MemoryRecordCreateInput]",
        *,
        clientToken: "str | None" = None,
    ) -> "BatchCreateMemoryRecordsOutput":
        """
        Creates multiple memory records in a single batch operation for the specified
        memory with custom content.

        Args:
            memoryId: The unique ID of the memory resource where records will be
                created.
            records: A list of memory record creation inputs to be processed in the
                batch operation.

        Keyword Args:
            clientToken: A unique, case-sensitive identifier to ensure idempotent
                processing of the batch request.
        """
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            records=self.serialize(records),
            clientToken=self.serialize(clientToken),
        )
        _response = self.client.batch_create_memory_records(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = BatchCreateMemoryRecordsOutput(**_response)

        results: "BatchCreateMemoryRecordsOutput" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("BatchCreateMemoryRecordsOutput", results)

    def batch_update(
        self, memoryId: str, records: "builtins.list[MemoryRecordUpdateInput]"
    ) -> "BatchUpdateMemoryRecordsOutput":
        """
        Updates multiple memory records with custom content in a single batch operation
        within the specified memory.

        Args:
            memoryId: The unique ID of the memory resource where records will be
                updated.
            records: A list of memory record update inputs to be processed in the batch
                operation.
        """
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId), records=self.serialize(records)
        )
        _response = self.client.batch_update_memory_records(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = BatchUpdateMemoryRecordsOutput(**_response)

        results: "BatchUpdateMemoryRecordsOutput" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("BatchUpdateMemoryRecordsOutput", results)

    def get(self, memoryId: str, memoryRecordId: str) -> "AgentCoreMemoryRecord | None":
        """
        Retrieves a specific memory record from an AgentCore Memory resource.

        Args:
            memoryId: The identifier of the AgentCore Memory resource containing the
                memory record.
            memoryRecordId: The identifier of the memory record to retrieve.
        """
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            memoryRecordId=self.serialize(memoryRecordId),
        )
        _response = self.client.get_memory_record(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetMemoryRecordOutput(**_response)

        if response and response.memoryRecord:
            self.sessionize(response.memoryRecord)
            return response.memoryRecord
        return None

    def list(
        self,
        memoryId: str,
        *,
        namespace: "str | None" = None,
        namespacePath: "str | None" = None,
        memoryStrategyId: "str | None" = None,
        metadataFilters: "builtins.list[MemoryMetadataFilterExpression] | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists memory records in an AgentCore Memory resource based on specified
        criteria.

        We recommend using pagination to ensure that the operation returns quickly and
        successfully.

        Args:
            memoryId: The identifier of the AgentCore Memory resource for which to list
                memory records.

        Keyword Args:
            namespace: The namespace prefix to filter memory records by. Returns all
                memory records in namespaces that start
                with the provided prefix. Either ``namespace`` or ``namespacePath`` is
                required.
            namespacePath: Use namespacePath for hierarchical retrievals. Return all
                memory records where namespace falls under
                the same parent hierarchy. Either ``namespace`` or ``namespacePath`` is
                required.
            memoryStrategyId: The memory strategy identifier to filter memory records
                by. If specified, only memory records with
                this strategy ID are returned.
            metadataFilters: A list of metadata filter expressions to scope the returned
                memory records.
        """
        paginator = self.client.get_paginator("list_memory_records")
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            namespace=self.serialize(namespace),
            namespacePath=self.serialize(namespacePath),
            memoryStrategyId=self.serialize(memoryStrategyId),
            metadataFilters=self.serialize(metadataFilters),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListMemoryRecordsOutput(**_response)
            if response.memoryRecordSummaries:
                results.extend(response.memoryRecordSummaries)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, memoryId: str, memoryRecordId: str) -> None:
        """
        Deletes a memory record from an AgentCore Memory resource.

        When you delete a memory record, it is permanently removed.

        Args:
            memoryId: The identifier of the AgentCore Memory resource from which to
                delete the memory record.
            memoryRecordId: The identifier of the memory record to delete.
        """
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId),
            memoryRecordId=self.serialize(memoryRecordId),
        )
        self.client.delete_memory_record(
            **{k: v for k, v in args.items() if v is not None}
        )


class AgentCoreAgentCardManager(Boto3ModelManager):
    service_name: str = "bedrock-agentcore"

    def get(
        self,
        agentRuntimeArn: str,
        *,
        runtimeSessionId: "str | None" = None,
        qualifier: "str | None" = None,
    ) -> "AgentCoreAgentCard | None":
        """
        Retrieves the A2A agent card associated with an AgentCore Runtime agent.

        Args:
            agentRuntimeArn: The ARN of the AgentCore Runtime agent for which you want
                to get the A2A agent card.

        Keyword Args:
            runtimeSessionId: The session ID that the AgentCore Runtime agent is using.
            qualifier: Optional qualifier to specify an agent alias, such as
                ``prod``code> or ``dev``. If you don't provide a
                value, the DEFAULT alias is used.
        """
        args: dict[str, Any] = dict(
            agentRuntimeArn=self.serialize(agentRuntimeArn),
            runtimeSessionId=self.serialize(runtimeSessionId),
            qualifier=self.serialize(qualifier),
        )
        _response = self.client.get_agent_card(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetAgentCardResponse(**_response)

        if response and response.agentCard:
            self.sessionize(response.agentCard)
            return response.agentCard
        return None


class AgentCoreExtractionJobManager(Boto3ModelManager):
    service_name: str = "bedrock-agentcore"

    def create(
        self,
        model: "AgentCoreExtractionJob",
        extractionJob: "ExtractionJob",
        clientToken: "str | None" = None,
    ) -> "StartMemoryExtractionJobOutput":
        """
        Starts a memory extraction job that processes events that failed extraction
        previously in an AgentCore Memory resource and produces structured memory
        records. When earlier extraction attempts have left events unprocessed, this job
        will pick up and extract those as well.

        Args:
            model: The :py:class:`ExtractionJobMetadata` to create.
            extractionJob: Extraction job to start in this operation.

        Keyword Args:
            clientToken: A unique, case-sensitive identifier to ensure idempotent
                processing of the request.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            memoryId=data.get("memoryId"),
            extractionJob=self.serialize(extractionJob),
            clientToken=self.serialize(clientToken),
        )
        _response = self.client.start_memory_extraction_job(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = StartMemoryExtractionJobOutput(**_response)

        self.sessionize(response)
        return cast("StartMemoryExtractionJobOutput", response)

    def list(
        self, memoryId: str, *, filter: "ExtractionJobFilterInput | None" = None
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists all long-term memory extraction jobs that are eligible to be started with
        optional filtering.

        Args:
            memoryId: The unique identifier of the memory to list extraction jobs for.

        Keyword Args:
            filter: Filter criteria to apply when listing extraction jobs.
        """
        paginator = self.client.get_paginator("list_memory_extraction_jobs")
        args: dict[str, Any] = dict(
            memoryId=self.serialize(memoryId), filter=self.serialize(filter)
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListMemoryExtractionJobsOutput(**_response)
            if response.jobs:
                results.extend(response.jobs)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results


# ==============
# Service Models
# ==============


class Conversational(Boto3Model):
    """
    Contains conversational content for an event payload.
    """

    content: Content
    """
    The content of the conversation message.
    """

    role: Literal["ASSISTANT", "USER", "TOOL", "OTHER"]
    """
    The role of the participant in the conversation (for example, "user" or
    "assistant").
    """


class MemoryDocument(Boto3Model):
    pass


class PayloadType(Boto3Model):
    """
    Contains the payload content for an event.
    """

    conversational: "Conversational | None" = None
    """
    The conversational content of the payload.
    """

    blob: "MemoryDocument | None" = None
    """
    The binary content of the payload.
    """

class Branch(Boto3Model):
    """
    Contains information about a branch in an AgentCore Memory resource.

    Branches allow for organizing events into different conversation threads or paths.
    """

    rootEventId: "str | None" = None
    """
    The identifier of the root event for this branch.
    """

    name: str
    """
    The name of the branch.
    """

class MetadataValue(Boto3Model):
    """
    Value associated with the ``eventMetadata`` key.
    """

    stringValue: "str | None" = None
    """
    Value associated with the ``eventMetadata`` key.
    """

class AgentCoreEvent(PrimaryBoto3Model):
    """
    Contains information about an event in an AgentCore Memory resource.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = AgentCoreEventManager

    memoryId: str
    """
    The identifier of the AgentCore Memory resource containing the event.
    """

    actorId: str
    """
    The identifier of the actor associated with the event.
    """

    sessionId: str
    """
    The identifier of the session containing the event.
    """

    eventId: str = Field(frozen=True)
    """
    The unique identifier of the event.
    """
    eventTimestamp: datetime
    """
    The timestamp when the event occurred.
    """

    payload: "builtins.list[PayloadType]"
    """
    The content payload of the event.
    """
    branch: "Branch | None" = None
    """
    The branch information for the event.
    """

    metadata: "dict[str, MetadataValue] | None" = Field(default_factory=dict)
    """
    Metadata associated with an event.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`eventId` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.eventId

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`eventId` attribute.
        """
        return hash(self.eventId)


class LinkedAccountEmail(Boto3Model):
    """
    Linked account using an email address.
    """

    emailAddress: str
    """
    The email address used for the linked account.

    Must be a valid email format.
    """


class LinkedAccountSms(Boto3Model):
    """
    Linked account using a phone number in E.164 format.
    """

    phoneNumber: str
    """
    The phone number in E.164 format (e.g., +1234567890).
    """


class LinkedAccountDeveloperJwt(Boto3Model):
    """
    Authentication method using JWT with key ID and subject claims.
    """

    kid: str
    """
    The key ID (kid) from the JWT header.

    Identifies which key was used to sign the JWT.
    """

    sub: str
    """
    The subject (sub) claim from the JWT payload.

    Identifies the principal that is the subject of the JWT.
    """
class OAuth2Authentication(Boto3Model):
    """
    OAuth2 authentication information for third-party providers.
    """

    sub: str
    """
    The subject (sub) claim from the OAuth2 provider.

    Uniquely identifies the user at the provider.
    """

    emailAddress: "str | None" = None
    """
    The email address from the OAuth2 provider.
    """

    name: "str | None" = None
    """
    The user's name from the OAuth2 provider.
    """

    username: "str | None" = None
    """
    The username from the OAuth2 provider.
    """

class LinkedAccountOAuth2(Boto3Model):
    """
    Authentication method using OAuth2 providers.

    Supports Google, Apple, X, Telegram, and GitHub providers.
    """

    google: "OAuth2Authentication | None" = None
    """
    Google OAuth2 authentication.
    """

    apple: "OAuth2Authentication | None" = None
    """
    Apple OAuth2 authentication.
    """

    x: "OAuth2Authentication | None" = None
    """
    X (formerly Twitter) OAuth2 authentication.
    """
    telegram: "OAuth2Authentication | None" = None
    """
    Telegram OAuth2 authentication.
    """

    github: "OAuth2Authentication | None" = None
    """
    GitHub OAuth2 authentication.
    """

class LinkedAccount(Boto3Model):
    """
    Represents different linked accounts that can be linked to an embedded wallet.

    Supports email, SMS, JWT, and OAuth2 approaches.
    """
    email: "LinkedAccountEmail | None" = None
    """
    Email-based linked account.
    """
    sms: "LinkedAccountSms | None" = None
    """
    SMS-based linked account using phone number.
    """

    developerJwt: "LinkedAccountDeveloperJwt | None" = None
    """
    Developer JWT linked account with key ID and subject.
    """

    oAuth2: "LinkedAccountOAuth2 | None" = None
    """
    OAuth2 provider linked account (Google, Apple, X, Telegram, GitHub).
    """

class EmbeddedCryptoWallet(Boto3Model):
    """
    Embedded crypto wallet instrument details.
    """
    network: Literal["ETHEREUM", "SOLANA"]
    """
    The blockchain network for this embedded crypto wallet.

    Supported networks: ETHEREUM, SOLANA.
    """

    linkedAccounts: "builtins.list[LinkedAccount]"
    """
    List of linked accounts linked to this wallet.

    Each represents a way the end user can authenticate to this wallet.
    """

    walletAddress: "str | None" = None
    """
    The wallet address on the specified blockchain network.
    """
    redirectUrl: "str | None" = None
    """
    URL for the end user to complete a provider-specific action such as wallet linking
    or onboarding.
    """
class PaymentInstrumentDetails(Boto3Model):
    """
    Details specific to the instrument type.
    """

    embeddedCryptoWallet: "EmbeddedCryptoWallet | None" = None
    """
    Embedded crypto wallet managed directly by end user.
    """

class AgentCorePaymentInstrument(PrimaryBoto3Model):
    """
    Represents a payment instrument.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        AgentCorePaymentInstrumentManager
    )
    paymentInstrumentId: str = Field(frozen=True)
    """
    The unique identifier for this payment instrument.
    """

    paymentManagerArn: str
    """
    The ARN of the payment manager that owns this payment instrument.
    """
    paymentConnectorId: str
    """
    The ID of the payment connector associated with this instrument.
    """
    userId: str
    """
    The user ID associated with this payment instrument.
    """

    paymentInstrumentType: Literal["EMBEDDED_CRYPTO_WALLET"]
    """
    The type of payment instrument (e.g., EMBEDDED_CRYPTO_WALLET).
    """

    paymentInstrumentDetails: PaymentInstrumentDetails
    """
    The details specific to the payment instrument type.
    """

    createdAt: datetime = Field(frozen=True)
    """
    The timestamp when this payment instrument was created.
    """

    status: Literal["INITIATED", "ACTIVE", "FAILED", "DELETED"] = Field(frozen=True)
    """
    The current status of this payment instrument.
    """

    updatedAt: datetime = Field(frozen=True)
    """
    The timestamp when this payment instrument was last updated.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`paymentInstrumentId` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.paymentInstrumentId

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`paymentInstrumentId` attribute.
        """
        return hash(self.paymentInstrumentId)
class Amount(Boto3Model):
    """
    Represents a monetary amount with a currency.
    """

    value: str
    """
    The numeric value of the amount.
    """

    currency: Literal["USD"]
    """
    The currency code for the amount.
    """


class SessionLimits(Boto3Model):
    """
    The spending limits configuration for a payment session.
    """
    maxSpendAmount: Amount
    """
    The maximum amount that can be spent in the session.
    """
class AvailableLimits(Boto3Model):
    """
    The available spending limits for a payment session.
    """

    availableSpendAmount: "Amount | None" = None
    """
    The remaining available amount that can be spent.
    """

    updatedAt: "datetime | None" = None
    """
    The timestamp when the available limits were last updated.
    """

class AgentCorePaymentSession(PrimaryBoto3Model):
    """
    A payment session for managing payment transactions.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        AgentCorePaymentSessionManager
    )
    paymentSessionId: str = Field(frozen=True)
    """
    The unique identifier of the payment session.
    """

    paymentManagerArn: str
    """
    The ARN of the payment manager that owns this session.
    """

    limits: "SessionLimits | None" = None
    """
    The spending limits for the payment session.
    """

    userId: str
    """
    The user ID associated with this session.
    """

    expiryTimeInMinutes: int
    """
    The session expiry time in minutes.
    """

    createdAt: datetime = Field(frozen=True)
    """
    The timestamp when the session was created.
    """

    availableLimits: AvailableLimits = Field(default=None, frozen=True)
    """
    The current available spending limits.
    """

    updatedAt: datetime = Field(frozen=True)
    """
    The timestamp when the session was last updated.
    """
    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`paymentSessionId` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.paymentSessionId
    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`paymentSessionId` attribute.
        """
        return hash(self.paymentSessionId)
class MemoryContent(Boto3Model):
    """
    Contains the content of a memory record.
    """

    text: "str | None" = None
    """
    The text content of the memory record.
    """
class MemoryRecordMetadataValue(Boto3Model):
    """
    The value of a memory record metadata entry.
    """

    stringValue: "str | None" = None
    """
    A string value.
    """

    stringListValue: "builtins.list[str] | None" = Field(default_factory=list)
    """
    A list of string values.
    """

    numberValue: "float | None" = None
    """
    A numeric value.
    """

    dateTimeValue: "datetime | None" = None
    """
    A timestamp value in ISO 8601 UTC format.
    """

class AgentCoreMemoryRecord(PrimaryBoto3Model):
    """
    Contains information about a memory record in an AgentCore Memory resource.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = AgentCoreMemoryRecordManager

    memoryRecordId: str
    """
    The unique identifier of the memory record.
    """

    content: MemoryContent
    """
    The content of the memory record.
    """

    memoryStrategyId: str
    """
    The identifier of the memory strategy associated with this record.
    """

    namespaces: "builtins.list[str]"
    """
    The namespaces associated with this memory record.

    Namespaces help organize and categorize memory records.
    """
    createdAt: datetime
    """
    The timestamp when the memory record was created.
    """

    metadata: "dict[str, MemoryRecordMetadataValue] | None" = Field(
        default_factory=dict
    )
    """
    A map of metadata key-value pairs associated with a memory record.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`memoryRecordId` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.memoryRecordId

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`memoryRecordId` attribute.
        """
        return hash(self.memoryRecordId)


class AgentCoreAgentCard(ReadonlyPrimaryBoto3Model):
    manager_class: ClassVar[ModelType[Boto3ModelManager]] = AgentCoreAgentCardManager

    agentRuntimeArn: str
    """
    ARN of the agent runtime this card describes.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`agentRuntimeArn` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.agentRuntimeArn

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`agentRuntimeArn` attribute.
        """
        return hash(self.agentRuntimeArn)


class MessageMetadata(Boto3Model):
    """
    Metadata information associated with this message.
    """

    eventId: str
    """
    The identifier of the event associated with this message.
    """

    messageIndex: int
    """
    The position of this message within that event’s ordered list of messages.
    """


class ExtractionJobMessages(Boto3Model):
    """
    The list of messages that compose this extraction job.
    """

    messagesList: "builtins.list[MessageMetadata] | None" = Field(default_factory=list)
    """
    The list of messages that compose this extraction job.
    """
class AgentCoreExtractionJob(ReadonlyPrimaryBoto3Model):
    """
    Metadata information associated with this extraction job.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        AgentCoreExtractionJobManager
    )

    jobID: str
    """
    The unique identifier for the extraction job.
    """

    messages: ExtractionJobMessages
    """
    The messages associated with the extraction job.
    """

    status: "Literal['FAILED'] | None" = None
    """
    The current status of the extraction job.
    """

    failureReason: "str | None" = None
    """
    The cause of failure, if the job did not complete successfully.
    """

    strategyId: "str | None" = None
    """
    The identifier of the memory strategy for this extraction job.
    """

    sessionId: "str | None" = None
    """
    The identifier of the session for this extraction job.
    """

    actorId: "str | None" = None
    """
    The identifier of the actor for this extraction job.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`jobID` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.jobID
    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`jobID` attribute.
        """
        return hash(self.jobID)
# =======================
# Request/Response Models
# =======================

class CreateEventOutput(Boto3Model):
    event: AgentCoreEvent
    """
    The event that was created.
    """


class GetEventOutput(Boto3Model):
    event: AgentCoreEvent
    """
    The requested event information.
    """


class BranchFilter(Boto3Model):
    """
    Contains filter criteria for branches when listing events.
    """

    name: str
    """
    The name of the branch to filter by.
    """

    includeParentBranches: "bool | None" = None
    """
    Specifies whether to include parent branches in the results.

    Set to true to include parent branches, or false to exclude them.
    """

class LeftExpression(Boto3Model):
    """
    Left expression of the event metadata filter.
    """

    metadataKey: "str | None" = None
    """
    Key associated with the metadata in an event.
    """

class RightExpression(Boto3Model):
    """
    Right expression of the ``eventMetadata``filter.
    """

    metadataValue: "MetadataValue | None" = None
    """
    Value associated with the key in ``eventMetadata``.
    """

class EventMetadataFilterExpression(Boto3Model):
    """
    Filter expression for retrieving events based on metadata associated with an event.
    """

    left: LeftExpression
    """
    Left operand of the event metadata filter expression.
    """

    operator: Literal["EQUALS_TO", "EXISTS", "NOT_EXISTS"]
    """
    Operator applied to the event metadata filter expression.
    """

    right: "RightExpression | None" = None
    """
    Right operand of the event metadata filter expression.
    """

class FilterInput(Boto3Model):
    """
    Contains filter criteria for listing events.
    """

    branch: "BranchFilter | None" = None
    """
    The branch filter criteria to apply when listing events.
    """

    eventMetadata: "builtins.list[EventMetadataFilterExpression] | None" = Field(
        default_factory=list
    )
    """
    Event metadata filter criteria to apply when retrieving events.
    """

class ListEventsOutput(Boto3Model):
    events: "builtins.list[AgentCoreEvent]"
    """
    The list of events that match the specified criteria.
    """

    nextToken: "str | None" = None
    """
    The token to use in a subsequent request to get the next set of results.

    This value is null when there are no more results to return.
    """

class DeleteEventOutput(Boto3Model):
    eventId: str
    """
    The identifier of the event that was deleted.
    """


class CreatePaymentInstrumentResponse(Boto3Model):
    """
    Response structure for creating a payment instrument.
    """
    paymentInstrument: AgentCorePaymentInstrument
    """
    The created payment instrument.
    """

class GetPaymentInstrumentResponse(Boto3Model):
    """
    Response structure for getting a payment instrument.
    """

    paymentInstrument: AgentCorePaymentInstrument
    """
    The payment instrument details.
    """
class PaymentInstrumentSummary(Boto3Model):
    """
    Summary of a payment instrument for list operations.
    """

    paymentInstrumentId: str
    """
    The unique identifier for this payment instrument.
    """

    paymentManagerArn: str
    """
    The ARN of the payment manager that owns this payment instrument.
    """
    paymentConnectorId: str
    """
    The ID of the payment connector associated with this instrument.
    """

    userId: str
    """
    The user ID associated with this payment instrument.
    """
    paymentInstrumentType: Literal["EMBEDDED_CRYPTO_WALLET"]
    """
    The type of payment instrument (e.g., EMBEDDED_CRYPTO_WALLET).
    """

    status: Literal["INITIATED", "ACTIVE", "FAILED", "DELETED"]
    """
    The current status of this payment instrument.
    """

    createdAt: datetime
    """
    The timestamp when this payment instrument was created.
    """

    updatedAt: datetime
    """
    The timestamp when this payment instrument was last updated.
    """


class ListPaymentInstrumentsResponse(Boto3Model):
    """
    Response structure for listing payment instruments.
    """

    paymentInstruments: "builtins.list[PaymentInstrumentSummary]"
    """
    List of payment instrument summaries matching the request criteria.
    """

    nextToken: "str | None" = None
    """
    Token for pagination to retrieve the next set of results.
    """

class DeletePaymentInstrumentResponse(Boto3Model):
    """
    Response structure for deleting a payment instrument.
    """

    status: Literal["INITIATED", "ACTIVE", "FAILED", "DELETED"]
    """
    The status of the instrument after deletion.

    Always DELETED for successful soft delete.
    """

class CreatePaymentSessionResponse(Boto3Model):
    """
    Response structure for creating a payment session.
    """
    paymentSession: AgentCorePaymentSession
    """
    The created payment session.
    """


class GetPaymentSessionResponse(Boto3Model):
    """
    Response structure for getting a payment session.
    """

    paymentSession: AgentCorePaymentSession
    """
    The payment session details.
    """


class PaymentSessionSummary(Boto3Model):
    """
    Summary information about a payment session.
    """

    paymentSessionId: str
    """
    The unique identifier of the payment session.
    """

    paymentManagerArn: str
    """
    The ARN of the payment manager that owns this session.
    """

    userId: str
    """
    The user ID associated with this session.
    """

    expiryTimeInMinutes: int
    """
    The session expiry time in minutes.
    """

    createdAt: datetime
    """
    The timestamp when the session was created.
    """

    updatedAt: datetime
    """
    The timestamp when the session was last updated.
    """


class ListPaymentSessionsResponse(Boto3Model):
    """
    Response structure for listing payment sessions.
    """

    paymentSessions: "builtins.list[PaymentSessionSummary]"
    """
    List of payment session summaries matching the request criteria.
    """

    nextToken: "str | None" = None
    """
    Token for pagination to retrieve the next set of results.
    """
class DeletePaymentSessionResponse(Boto3Model):
    """
    Response structure for deleting a payment session.
    """

    status: Literal["ACTIVE", "EXPIRED", "DELETED"]
    """
    The status of the deletion.

    Always DELETED for successful hard delete.
    """


class MemoryRecordCreateInput(Boto3Model):
    """
    Input structure to create a new memory record.
    """

    requestIdentifier: str
    """
    A client-provided identifier for tracking this specific record creation request.
    """

    namespaces: "builtins.list[str]"
    """
    A list of namespace identifiers that categorize or group the memory record.
    """

    content: MemoryContent
    """
    The content to be stored within the memory record.
    """
    timestamp: datetime
    """
    Time at which the memory record was created.
    """
    memoryStrategyId: "str | None" = None
    """
    The ID of the memory strategy that defines how this memory record is grouped.
    """
    metadata: "dict[str, MemoryRecordMetadataValue] | None" = Field(
        default_factory=dict
    )
    """
    Metadata key-value pairs to be stored with the memory record.
    """

class MemoryRecordOutput(Boto3Model):
    """
    Output information returned after processing a memory record operation.
    """

    memoryRecordId: str
    """
    The unique ID associated to the memory record.
    """

    status: Literal["SUCCEEDED", "FAILED"]
    """
    The status of the memory record operation (e.g., SUCCEEDED, FAILED).
    """

    requestIdentifier: "str | None" = None
    """
    The client-provided identifier that was used to track this record operation.
    """
    errorCode: "int | None" = None
    """
    The error code returned when the memory record operation fails.
    """
    errorMessage: "str | None" = None
    """
    A human-readable error message describing why the memory record operation failed.
    """

class BatchCreateMemoryRecordsOutput(Boto3Model):
    successfulRecords: "builtins.list[MemoryRecordOutput]"
    """
    A list of memory records that were successfully created during the batch operation.
    """

    failedRecords: "builtins.list[MemoryRecordOutput]"
    """
    A list of memory records that failed to be created, including error details for each
    failure.
    """


class MemoryRecordUpdateInput(Boto3Model):
    """
    Input structure to update an existing memory record.
    """

    memoryRecordId: str
    """
    The unique ID of the memory record to be updated.
    """
    timestamp: datetime
    """
    Time at which the memory record was updated.
    """
    content: "MemoryContent | None" = None
    """
    The content to be stored within the memory record.
    """

    namespaces: "builtins.list[str] | None" = Field(default_factory=list)
    """
    The updated list of namespace identifiers for categorizing the memory record.
    """

    memoryStrategyId: "str | None" = None
    """
    The updated ID of the memory strategy that defines how this memory record is
    grouped.
    """

    metadata: "dict[str, MemoryRecordMetadataValue] | None" = Field(
        default_factory=dict
    )
    """
    Metadata key-value pairs to be stored with the memory record.
    """

class BatchUpdateMemoryRecordsOutput(Boto3Model):
    successfulRecords: "builtins.list[MemoryRecordOutput]"
    """
    A list of memory records that were successfully updated during the batch operation.
    """

    failedRecords: "builtins.list[MemoryRecordOutput]"
    """
    A list of memory records that failed to be updated, including error details for each
    failure.
    """


class GetMemoryRecordOutput(Boto3Model):
    memoryRecord: AgentCoreMemoryRecord
    """
    The requested memory record.
    """


class MemoryRecordLeftExpression(Boto3Model):
    """
    The left-hand side of a memory record metadata filter expression.
    """

    metadataKey: "str | None" = None
    """
    The metadata key to filter on.
    """

class MemoryRecordRightExpression(Boto3Model):
    """
    The right-hand side of a memory record metadata filter expression.
    """

    metadataValue: "MemoryRecordMetadataValue | None" = None
    """
    The metadata value to compare against.
    """

class MemoryMetadataFilterExpression(Boto3Model):
    """
    Filters to apply to metadata associated with a memory.

    Specify the metadata key and value in the ``left`` and ``right`` fields and use the
    ``operator`` field to define the relationship to match.
    """

    left: MemoryRecordLeftExpression
    """
    The metadata key to evaluate.
    """

    operator: Literal[
        "EQUALS_TO",
        "EXISTS",
        "NOT_EXISTS",
        "BEFORE",
        "AFTER",
        "CONTAINS",
        "GREATER_THAN",
        "GREATER_THAN_OR_EQUALS",
        "LESS_THAN",
        "LESS_THAN_OR_EQUALS",
    ]
    """
    The relationship between the metadata key and value to match when applying the
    metadata filter.
    """

    right: "MemoryRecordRightExpression | None" = None
    """
    The value to compare against.

    Required for all operators except EXISTS and NOT_EXISTS.
    """

class MemoryRecordSummary(Boto3Model):
    """
    Contains summary information about a memory record.
    """
    memoryRecordId: str
    """
    The unique identifier of the memory record.
    """

    content: MemoryContent
    """
    The content of the memory record.
    """

    memoryStrategyId: str
    """
    The identifier of the memory strategy associated with this record.
    """

    namespaces: "builtins.list[str]"
    """
    The namespaces associated with this memory record.
    """

    createdAt: datetime
    """
    The timestamp when the memory record was created.
    """

    score: "float | None" = None
    """
    The relevance score of the memory record when returned as part of a search result.

    Higher values indicate greater relevance to the search query.
    """
    metadata: "dict[str, MemoryRecordMetadataValue] | None" = Field(
        default_factory=dict
    )
    """
    A map of metadata key-value pairs associated with a memory record.
    """

class ListMemoryRecordsOutput(Boto3Model):
    memoryRecordSummaries: "builtins.list[MemoryRecordSummary]"
    """
    The list of memory record summaries that match the specified criteria.
    """

    nextToken: "str | None" = None
    """
    The token to use in a subsequent request to get the next set of results.

    This value is null when there are no more results to return.
    """

class DeleteMemoryRecordOutput(Boto3Model):
    memoryRecordId: str
    """
    The identifier of the memory record that was deleted.
    """


class GetAgentCardResponse(Boto3Model):
    runtimeSessionId: "str | None" = None
    """
    The ID of the session associated with the AgentCore Runtime agent.
    """

    agentCard: AgentCoreAgentCard
    """
    An agent card document that contains metadata and capabilities for an AgentCore
    Runtime agent.
    """

    statusCode: "int | None" = None
    """
    The status code of the request.
    """

class ExtractionJob(Boto3Model):
    """
    Represents the metadata of a memory extraction job such as the message identifiers
    that compose this job.
    """

    jobId: str
    """
    The unique identifier of the extraction job.
    """


class StartMemoryExtractionJobOutput(Boto3Model):
    jobId: str
    """
    Extraction Job ID that was attempted to start.
    """


class ExtractionJobFilterInput(Boto3Model):
    """
    Filters for querying memory extraction jobs based on various criteria.
    """

    strategyId: "str | None" = None
    """
    The memory strategy identifier to filter extraction jobs by.

    If specified, only extraction jobs with this strategy ID are returned.
    """

    sessionId: "str | None" = None
    """
    The unique identifier of the session.

    If specified, only extraction jobs with this session ID are returned.
    """

    actorId: "str | None" = None
    """
    The identifier of the actor.

    If specified, only extraction jobs with this actor ID are returned.
    """

    status: "Literal['FAILED'] | None" = None
    """
    The status of the extraction job.

    If specified, only extraction jobs with this status are returned.
    """

class ListMemoryExtractionJobsOutput(Boto3Model):
    jobs: "builtins.list[AgentCoreExtractionJob]"
    """
    List of extraction job metadata matching the specified criteria.
    """

    nextToken: "str | None" = None
    """
    Token to retrieve the next page of results, if available.
    """
