# This file is automatically generated by botocraft.  Do not edit directly.
# mypy: disable-error-code="index, override, assignment, union-attr, misc"
from botocraft.mixins.grafana import ManagedGrafanaServiceAccountTokenManagerMixin
from botocraft.mixins.grafana import ManagedGrafanaWorkspaceManagerMixin
from collections import OrderedDict
from botocraft.mixins.grafana import service_account_tokens_add_context
from botocraft.mixins.grafana import service_account_token_create_to_token_with_key
from pydantic import Field
import builtins
from botocraft.mixins.grafana import service_account_create_to_service_account
from .abstract import PrimaryBoto3ModelQuerySet
from botocraft.mixins.tags import TagsDictMixin
from botocraft.mixins.grafana import service_accounts_add_workspace_context
from .abstract import (
    Boto3Model,
    ReadonlyBoto3Model,
    PrimaryBoto3Model,
    ReadonlyPrimaryBoto3Model,
    Boto3ModelManager,
    ReadonlyBoto3ModelManager,
)
from datetime import datetime
from typing import ClassVar, Literal, Any, Type as ModelType, cast

# ===============
# Managers
# ===============


class ManagedGrafanaWorkspaceManager(
    ManagedGrafanaWorkspaceManagerMixin, Boto3ModelManager
):
    service_name: str = "grafana"

    def create(
        self,
        model: "ManagedGrafanaWorkspace",
        authenticationProviders: "builtins.list[Literal['AWS_SSO', 'SAML']]",
        clientToken: "str | None" = None,
        workspaceDataSources: "builtins.list[Literal['AMAZON_OPENSEARCH_SERVICE', 'CLOUDWATCH', 'PROMETHEUS', 'XRAY', 'TIMESTREAM', 'SITEWISE', 'ATHENA', 'REDSHIFT', 'TWINMAKER']] | None" = None,
        workspaceDescription: "str | None" = None,
        workspaceName: "str | None" = None,
        workspaceNotificationDestinations: "builtins.list[Literal['SNS']] | None" = None,
        workspaceOrganizationalUnits: "builtins.list[str] | None" = None,
        configuration: "str | None" = None,
    ) -> "ManagedGrafanaWorkspace":
        """
        Create a new AWS Managed Grafana workspace.

        Note that ````model.name```` and ````model.description```` are ignored in favor
        of the ````workspaceName=````/````workspaceDescription=```` keyword arguments;
        this is an AWS API asymmetry, not a
        Botocraft bug.

        Args:
            model: The :py:class:`WorkspaceDescription` to create.
            authenticationProviders: Specifies whether this workspace uses SAML 2.0, IAM
                Identity Center, or both to
                authenticate users for using the Grafana console within a workspace. For
                more information, see `User authentication
                in Amazon Managed Grafana <https://docs.aws.amazon.com/grafana/latest/userguide/authentication-in-AMG.html>`_.

        Keyword Args:
            clientToken: A unique, case-sensitive, user-provided identifier to ensure
                the idempotency of the request.
            workspaceDataSources: This parameter is for internal use only, and should
                not be used.
            workspaceDescription: A description for the workspace. This is used only to
                help you identify this workspace.
            workspaceName: The name for the workspace. It does not have to be unique.
            workspaceNotificationDestinations: Specify the Amazon Web Services
                notification channels that you plan to use in
                this workspace. Specifying these data sources here enables Amazon
                Managed Grafana to create IAM roles and
                permissions that allow Amazon Managed Grafana to use these channels.
            workspaceOrganizationalUnits: Specifies the organizational units that this
                workspace is allowed to use data sources
                from, if this workspace is in an account that is part of an
                organization.
            configuration: The configuration string for the workspace that you create.
                For more information about the format and
                configuration options available, see `Working in your Grafana workspace
                <https://docs.aws.amazon.com/grafana/latest/userguide/AMG- configure-workspace.html>`_.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            accountAccessType=data.get("accountAccessType"),
            permissionType=data.get("permissionType"),
            authenticationProviders=self.serialize(authenticationProviders),
            clientToken=self.serialize(clientToken),
            organizationRoleName=data.get("organizationRoleName"),
            stackSetName=data.get("stackSetName"),
            workspaceDataSources=self.serialize(workspaceDataSources),
            workspaceDescription=self.serialize(workspaceDescription),
            workspaceName=self.serialize(workspaceName),
            workspaceNotificationDestinations=self.serialize(
                workspaceNotificationDestinations
            ),
            workspaceOrganizationalUnits=self.serialize(workspaceOrganizationalUnits),
            workspaceRoleArn=data.get("workspaceRoleArn"),
            tags=data.get("tags"),
            vpcConfiguration=data.get("vpcConfiguration"),
            configuration=self.serialize(configuration),
            networkAccessControl=data.get("networkAccessControl"),
            grafanaVersion=data.get("grafanaVersion"),
            ipAddressType=data.get("ipAddressType"),
            kmsKeyId=data.get("kmsKeyId"),
        )
        _response = self.client.create_workspace(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = CreateWorkspaceResponse(**_response)

        self.sessionize(response.workspace)
        return cast("ManagedGrafanaWorkspace", response.workspace)

    def get(self, workspaceId: str) -> "ManagedGrafanaWorkspace | None":
        """
        Get a single AWS Managed Grafana workspace by id.

        Args:
            workspaceId: The ID of the workspace to display information about.
        """
        args: dict[str, Any] = dict(workspaceId=self.serialize(workspaceId))
        _response = self.client.describe_workspace(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeWorkspaceResponse(**_response)

        if response and response.workspace:
            self.sessionize(response.workspace)
            return response.workspace
        return None

    def update(
        self,
        model: "ManagedGrafanaWorkspace",
        workspaceId: str,
        workspaceDataSources: "builtins.list[Literal['AMAZON_OPENSEARCH_SERVICE', 'CLOUDWATCH', 'PROMETHEUS', 'XRAY', 'TIMESTREAM', 'SITEWISE', 'ATHENA', 'REDSHIFT', 'TWINMAKER']] | None" = None,
        workspaceDescription: "str | None" = None,
        workspaceName: "str | None" = None,
        workspaceNotificationDestinations: "builtins.list[Literal['SNS']] | None" = None,
        workspaceOrganizationalUnits: "builtins.list[str] | None" = None,
        removeVpcConfiguration: "bool | None" = None,
        removeNetworkAccessConfiguration: "bool | None" = None,
    ) -> "ManagedGrafanaWorkspace":
        """
        Update an existing AWS Managed Grafana workspace.

        Note that ````model.name```` and ````model.description```` are ignored in favor
        of the ````workspaceName=````/````workspaceDescription=```` keyword arguments;
        this is an AWS API asymmetry,
        not a Botocraft bug.

        Args:
            model: The :py:class:`WorkspaceDescription` to update.
            workspaceId: The ID of the workspace to update.

        Keyword Args:
            workspaceDataSources: This parameter is for internal use only, and should
                not be used.
            workspaceDescription: A description for the workspace. This is used only to
                help you identify this workspace.
            workspaceName: A new name for the workspace to update.
            workspaceNotificationDestinations: Specify the Amazon Web Services
                notification channels that you plan to use in
                this workspace. Specifying these data sources here enables Amazon
                Managed Grafana to create IAM roles and
                permissions that allow Amazon Managed Grafana to use these channels.
            workspaceOrganizationalUnits: Specifies the organizational units that this
                workspace is allowed to use data sources
                from, if this workspace is in an account that is part of an
                organization.
            removeVpcConfiguration: Whether to remove the VPC configuration from the
                workspace.
            removeNetworkAccessConfiguration: Whether to remove the network access
                configuration from the workspace.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            workspaceId=self.serialize(workspaceId),
            accountAccessType=data.get("accountAccessType"),
            organizationRoleName=data.get("organizationRoleName"),
            permissionType=data.get("permissionType"),
            stackSetName=data.get("stackSetName"),
            workspaceDataSources=self.serialize(workspaceDataSources),
            workspaceDescription=self.serialize(workspaceDescription),
            workspaceName=self.serialize(workspaceName),
            workspaceNotificationDestinations=self.serialize(
                workspaceNotificationDestinations
            ),
            workspaceOrganizationalUnits=self.serialize(workspaceOrganizationalUnits),
            workspaceRoleArn=data.get("workspaceRoleArn"),
            vpcConfiguration=data.get("vpcConfiguration"),
            removeVpcConfiguration=self.serialize(removeVpcConfiguration),
            networkAccessControl=data.get("networkAccessControl"),
            removeNetworkAccessConfiguration=self.serialize(
                removeNetworkAccessConfiguration
            ),
            ipAddressType=data.get("ipAddressType"),
        )
        _response = self.client.update_workspace(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = UpdateWorkspaceResponse(**_response)

        self.sessionize(response.workspace)
        return cast("ManagedGrafanaWorkspace", response.workspace)

    def delete(self, workspaceId: str) -> "ManagedGrafanaWorkspace":
        """
        Delete an AWS Managed Grafana workspace.

        Args:
            workspaceId: The ID of the workspace to delete.
        """
        args: dict[str, Any] = dict(workspaceId=self.serialize(workspaceId))
        _response = self.client.delete_workspace(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DeleteWorkspaceResponse(**_response)
        return cast("ManagedGrafanaWorkspace", response.workspace)

    def describe_authentication(self, workspaceId: str) -> "AuthenticationDescription":
        """
        Describe the authentication configuration for a workspace.

        Args:
            workspaceId: The ID of the workspace to return authentication information
                about.
        """
        args: dict[str, Any] = dict(workspaceId=self.serialize(workspaceId))
        _response = self.client.describe_workspace_authentication(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeWorkspaceAuthenticationResponse(**_response)

        results: "AuthenticationDescription" = None
        if response is not None:
            results = response.authentication

        self.sessionize(results)
        return cast("AuthenticationDescription", results)

    def update_authentication(
        self,
        workspaceId: str,
        authenticationProviders: "builtins.list[Literal['AWS_SSO', 'SAML']]",
        *,
        samlConfiguration: "SamlConfiguration | None" = None,
    ) -> "AuthenticationDescription":
        """
        Update the authentication configuration for a workspace.

        Args:
            workspaceId: The ID of the workspace to update the authentication for.
            authenticationProviders: Specifies whether this workspace uses SAML 2.0, IAM
                Identity Center, or both to
                authenticate users for using the Grafana console within a workspace. For
                more information, see `User authentication
                in Amazon Managed Grafana <https://docs.aws.amazon.com/grafana/latest/userguide/authentication-in-AMG.html>`_.

        Keyword Args:
            samlConfiguration: If the workspace uses SAML, use this structure to map
                SAML assertion attributes to workspace user
                information and define which groups in the assertion attribute are to
                have the ``Admin`` and ``Editor`` roles in the
                workspace.
        """
        args: dict[str, Any] = dict(
            workspaceId=self.serialize(workspaceId),
            authenticationProviders=self.serialize(authenticationProviders),
            samlConfiguration=self.serialize(samlConfiguration),
        )
        _response = self.client.update_workspace_authentication(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = UpdateWorkspaceAuthenticationResponse(**_response)

        results: "AuthenticationDescription" = None
        if response is not None:
            results = response.authentication

        self.sessionize(results)
        return cast("AuthenticationDescription", results)

    def describe_configuration(
        self, workspaceId: str
    ) -> "DescribeWorkspaceConfigurationResponse":
        """
        Describe the Grafana configuration blob for a workspace.

        Args:
            workspaceId: The ID of the workspace to get configuration information for.
        """
        args: dict[str, Any] = dict(workspaceId=self.serialize(workspaceId))
        _response = self.client.describe_workspace_configuration(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeWorkspaceConfigurationResponse(**_response)

        results: "DescribeWorkspaceConfigurationResponse" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("DescribeWorkspaceConfigurationResponse", results)

    def update_configuration(
        self,
        configuration: str,
        workspaceId: str,
        *,
        grafanaVersion: "str | None" = None,
    ) -> None:
        """
        Update the Grafana configuration blob for a workspace; AWS Managed Grafana
        returns no content on success.

        Args:
            configuration: The new configuration string for the workspace. For more
                information about the format and
                configuration options available, see `Working in your Grafana workspace
                <https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure- workspace.html>`_.
            workspaceId: The ID of the workspace to update.

        Keyword Args:
            grafanaVersion: Specifies the version of Grafana to support in the
                workspace. If not specified, keeps the current
                version of the workspace.
        """
        args: dict[str, Any] = dict(
            configuration=self.serialize(configuration),
            workspaceId=self.serialize(workspaceId),
            grafanaVersion=self.serialize(grafanaVersion),
        )
        self.client.update_workspace_configuration(
            **{k: v for k, v in args.items() if v is not None}
        )

    def associate_license(
        self,
        workspaceId: str,
        licenseType: Literal["ENTERPRISE", "ENTERPRISE_FREE_TRIAL"],
        *,
        grafanaToken: "str | None" = None,
    ) -> "ManagedGrafanaWorkspace":
        """
        Associate a Grafana Enterprise license with a workspace.

        Args:
            workspaceId: The ID of the workspace to associate the license with.
            licenseType: The type of license to associate with the workspace.

        Keyword Args:
            grafanaToken: A token from Grafana Labs that ties your Amazon Web Services
                account with a Grafana Labs account. For
                more information, see `Link your account with Grafana Labs
                <https://docs.aws.amazon.com/grafana/latest/userguide/upgrade-to-Grafana- Enterprise.html#AMG-workspace-register-
                enterprise>`_.
        """
        args: dict[str, Any] = dict(
            workspaceId=self.serialize(workspaceId),
            licenseType=self.serialize(licenseType),
            grafanaToken=self.serialize(grafanaToken),
        )
        _response = self.client.associate_license(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = AssociateLicenseResponse(**_response)

        results: "ManagedGrafanaWorkspace" = None
        if response is not None:
            results = response.workspace

        self.sessionize(results)
        return cast("ManagedGrafanaWorkspace", results)

    def disassociate_license(
        self,
        workspaceId: str,
        licenseType: Literal["ENTERPRISE", "ENTERPRISE_FREE_TRIAL"],
    ) -> "ManagedGrafanaWorkspace":
        """
        Disassociate a Grafana Enterprise license from a workspace.

        Args:
            workspaceId: The ID of the workspace to remove the Grafana Enterprise
                license from.
            licenseType: The type of license to remove from the workspace.
        """
        args: dict[str, Any] = dict(
            workspaceId=self.serialize(workspaceId),
            licenseType=self.serialize(licenseType),
        )
        _response = self.client.disassociate_license(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DisassociateLicenseResponse(**_response)

        results: "ManagedGrafanaWorkspace" = None
        if response is not None:
            results = response.workspace

        self.sessionize(results)
        return cast("ManagedGrafanaWorkspace", results)

    def list_permissions(
        self,
        workspaceId: str,
        *,
        userType: "Literal['SSO_USER', 'SSO_GROUP'] | None" = None,
        userId: "str | None" = None,
        groupId: "str | None" = None,
    ) -> "builtins.list[PermissionEntry]":
        """
        List the user and group permissions granted on a workspace.

        Args:
            workspaceId: The ID of the workspace to list permissions for. This parameter
                is required.

        Keyword Args:
            userType: (Optional) If you specify ``SSO_USER``, then only the permissions
                of IAM Identity Center users are
                returned. If you specify ``SSO_GROUP``, only the permissions of IAM
                Identity Center groups are returned.
            userId: (Optional) Limits the results to only the user that matches this ID.
            groupId: (Optional) Limits the results to only the group that matches this
                ID.
        """
        paginator = self.client.get_paginator("list_permissions")
        args: dict[str, Any] = dict(
            workspaceId=self.serialize(workspaceId),
            userType=self.serialize(userType),
            userId=self.serialize(userId),
            groupId=self.serialize(groupId),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )

        results: "builtins.list[PermissionEntry]" = []

        for _response in response_iterator:
            response = ListPermissionsResponse(**_response)
            if response.permissions is not None:
                results.extend(response.permissions)
            else:
                break

        self.sessionize(results)
        return cast("builtins.list[PermissionEntry]", results)

    def update_permissions(
        self,
        updateInstructionBatch: "builtins.list[UpdateInstruction]",
        workspaceId: str,
    ) -> "builtins.list[UpdateError]":
        """
        Grant or revoke user and group permissions on a workspace.

        Returns a list of errors, one per update instruction that AWS Managed Grafana
        was not able to apply; an empty list means every instruction succeeded.

        Args:
            updateInstructionBatch: An array of structures that contain the permission
                updates to make.
            workspaceId: The ID of the workspace to update.
        """
        args: dict[str, Any] = dict(
            updateInstructionBatch=self.serialize(updateInstructionBatch),
            workspaceId=self.serialize(workspaceId),
        )
        _response = self.client.update_permissions(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = UpdatePermissionsResponse(**_response)

        results: "builtins.list[UpdateError]" = None
        if response is not None:
            results = response.errors

        self.sessionize(results)
        return cast("builtins.list[UpdateError]", results)

    def list_versions(
        self, *, workspaceId: "str | None" = None
    ) -> "builtins.list[str]":
        """
        List the Grafana versions available for new workspaces, or the versions
        available to upgrade an existing workspace to.

        Keyword Args:
            workspaceId: The ID of the workspace to list the available upgrade versions.
                If not included, lists all versions of
                Grafana that are supported for ``CreateWorkspace``.
        """
        paginator = self.client.get_paginator("list_versions")
        args: dict[str, Any] = dict(workspaceId=self.serialize(workspaceId))
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )

        results: "builtins.list[str]" = []

        for _response in response_iterator:
            response = ListVersionsResponse(**_response)
            if response.grafanaVersions is not None:
                results.extend(response.grafanaVersions)
            else:
                break

        self.sessionize(results)
        return cast("builtins.list[str]", results)


class ManagedGrafanaServiceAccountManager(Boto3ModelManager):
    service_name: str = "grafana"

    @service_account_create_to_service_account
    def create(
        self, model: "ManagedGrafanaServiceAccount"
    ) -> "ManagedGrafanaServiceAccount":
        """
        Create a service account in an AWS Managed Grafana workspace.

        The ````CreateWorkspaceServiceAccount```` boto3 response is a flat shape
        (````id````, ````name````, ````grafanaRole````, ````workspaceId````) that does
        not match the
        ````ServiceAccountSummary```` shape used everywhere else (which has
        ````isDisabled```` instead of ````workspaceId````);
        the ````service_account_create_to_service_account```` decorator builds a proper
        :py:class:`ServiceAccountSummary`
        from the flat response, defaulting ````isDisabled```` to ````"false"```` (a
        string) since a newly-created service
        account is never disabled.

        Args:
            model: The :py:class:`ServiceAccountSummary` to create.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            name=data.get("name"),
            grafanaRole=data.get("grafanaRole"),
            workspaceId=data.get("workspaceId"),
        )
        _response = self.client.create_workspace_service_account(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = CreateWorkspaceServiceAccountResponse(**_response)

        self.sessionize(response)
        return cast("ManagedGrafanaServiceAccount", response)

    @service_accounts_add_workspace_context
    def list(self, workspaceId: str) -> PrimaryBoto3ModelQuerySet:
        """
        List the service accounts in an AWS Managed Grafana workspace.

        Args:
            workspaceId: The workspace for which to list service accounts.
        """
        paginator = self.client.get_paginator("list_workspace_service_accounts")
        args: dict[str, Any] = dict(workspaceId=self.serialize(workspaceId))
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListWorkspaceServiceAccountsResponse(**_response)
            if response.serviceAccounts:
                results.extend(response.serviceAccounts)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, serviceAccountId: str, workspaceId: str) -> None:
        """
        Delete a service account from an AWS Managed Grafana workspace.

        Args:
            serviceAccountId: The ID of the service account to delete.
            workspaceId: The ID of the workspace where the service account resides.
        """
        args: dict[str, Any] = dict(
            serviceAccountId=self.serialize(serviceAccountId),
            workspaceId=self.serialize(workspaceId),
        )
        self.client.delete_workspace_service_account(
            **{k: v for k, v in args.items() if v is not None}
        )


class ManagedGrafanaServiceAccountTokenManager(
    ManagedGrafanaServiceAccountTokenManagerMixin, Boto3ModelManager
):
    service_name: str = "grafana"

    @service_account_token_create_to_token_with_key
    def create(
        self, model: "ManagedGrafanaServiceAccountToken", secondsToLive: int
    ) -> "ManagedGrafanaServiceAccountTokenWithKey":
        """
        Create a service account token.

        The plaintext token ````key```` is visible only in this response; AWS Managed
        Grafana never returns it again -- see
        :py:class:`ServiceAccountTokenSummaryWithKey`.

        Args:
            model: The :py:class:`ServiceAccountTokenSummary` to create.
            secondsToLive: Sets how long the token will be valid, in seconds. You can
                set the time up to 30 days in the future.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            name=data.get("name"),
            secondsToLive=self.serialize(secondsToLive),
            serviceAccountId=data.get("serviceAccountId"),
            workspaceId=data.get("workspaceId"),
        )
        _response = self.client.create_workspace_service_account_token(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = CreateWorkspaceServiceAccountTokenResponse(**_response)

        self.sessionize(response)
        return cast("ManagedGrafanaServiceAccountTokenWithKey", response)

    @service_account_tokens_add_context
    def list(
        self, serviceAccountId: str, workspaceId: str
    ) -> PrimaryBoto3ModelQuerySet:
        """
        List the service account tokens for a service account.

        This never includes the plaintext token key --
        ````ServiceAccountTokenSummary```` has no ````key```` field.

        Args:
            serviceAccountId: The ID of the service account for which to return tokens.
            workspaceId: The ID of the workspace for which to return tokens.
        """
        paginator = self.client.get_paginator("list_workspace_service_account_tokens")
        args: dict[str, Any] = dict(
            serviceAccountId=self.serialize(serviceAccountId),
            workspaceId=self.serialize(workspaceId),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListWorkspaceServiceAccountTokensResponse(**_response)
            if response.serviceAccountTokens:
                results.extend(response.serviceAccountTokens)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, tokenId: str, serviceAccountId: str, workspaceId: str) -> None:
        """
        Delete a service account token.

        Args:
            tokenId: The ID of the token to delete.
            serviceAccountId: The ID of the service account from which to delete the
                token.
            workspaceId: The ID of the workspace from which to delete the token.
        """
        args: dict[str, Any] = dict(
            tokenId=self.serialize(tokenId),
            serviceAccountId=self.serialize(serviceAccountId),
            workspaceId=self.serialize(workspaceId),
        )
        self.client.delete_workspace_service_account_token(
            **{k: v for k, v in args.items() if v is not None}
        )


# ==============
# Service Models
# ==============


class AuthenticationSummary(Boto3Model):
    """
    A structure that describes whether the workspace uses SAML, IAM Identity Center, or
    both methods for user authentication, and whether that authentication is fully
    configured.
    """

    providers: "builtins.list[Literal['AWS_SSO', 'SAML']]"
    """
    Specifies whether the workspace uses SAML, IAM Identity Center, or both methods for
    user authentication.
    """

    samlConfigurationStatus: "Literal['CONFIGURED', 'NOT_CONFIGURED'] | None" = None
    """
    Specifies whether the workplace's user authentication method is fully configured.
    """

class VpcConfiguration(Boto3Model):
    """
    The configuration settings for an Amazon VPC that contains data sources for your
    Grafana workspace to connect to.

    Provided ``securityGroupIds`` and ``subnetIds`` must be part of the same VPC.

    Connecting to a private VPC is not yet available in the Asia Pacific (Seoul) Region
    (ap-northeast-2).
    """

    securityGroupIds: "builtins.list[str]"
    """
    The list of Amazon EC2 security group IDs attached to the Amazon VPC for your
    Grafana workspace to connect.

    Duplicates not allowed.
    """

    subnetIds: "builtins.list[str]"
    """
    The list of Amazon EC2 subnet IDs created in the Amazon VPC for your Grafana
    workspace to connect.

    Duplicates not allowed.
    """


class NetworkAccessConfiguration(Boto3Model):
    """
    The configuration settings for in-bound network access to your workspace.

    When this is configured, only listed IP addresses and VPC endpoints will be able to
    access your workspace. Standard
    Grafana authentication and authorization are still required.

    Access is granted to a caller that is in either the IP address list or the VPC
    endpoint list - they do not need to be in
    both.

    If this is not configured, or is removed, then all IP addresses and VPC endpoints
    are allowed. Standard Grafana
    authentication and authorization are still required.

    While both ``prefixListIds`` and ``vpceIds`` are required, you can pass in an empty
    array of strings for either
    parameter if you do not want to allow any of that type.

    If both are passed as empty arrays, no traffic is allowed to the workspace, because
    only *explicitly* allowed
    connections are accepted.
    """

    prefixListIds: "builtins.list[str]"
    """
    An array of prefix list IDs.

    A prefix list is a list of CIDR ranges of IP addresses. The IP addresses specified
    are allowed to access your workspace. If the list is not included in the
    configuration (passed an empty array) then no IP addresses are allowed to access the
    workspace. You create a prefix list using the Amazon VPC console.
    """

    vpceIds: "builtins.list[str]"
    """
    An array of Amazon VPC endpoint IDs for the workspace.

    You can create VPC endpoints to your Amazon Managed Grafana workspace for access
    from within a VPC. If a ``NetworkAccessConfiguration`` is specified then only VPC
    endpoints specified here are allowed to access the workspace. If you pass in an
    empty array of strings, then no VPCs are allowed to access the workspace.
    """


class ManagedGrafanaWorkspace(PrimaryBoto3Model):
    """
    A structure containing information about an Amazon Managed Grafana workspace in your
    account.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        ManagedGrafanaWorkspaceManager
    )

    workspaceName: str = Field(default=None, alias="name")
    """
    The name of the workspace.
    """

    Tags: dict[str, str] = Field(default_factory=dict, alias="tags")
    """
    The list of tags associated with the workspace.
    """

    accountAccessType: "Literal['CURRENT_ACCOUNT', 'ORGANIZATION'] | None" = None
    """
    Specifies whether the workspace can access Amazon Web Services resources in this
    Amazon Web Services account only, or whether it can also access Amazon Web Services
    resources in other accounts in the same organization.

    If this is
    ``ORGANIZATION``, the ``workspaceOrganizationalUnits`` parameter specifies which
    organizational units the workspace can
    access.
    """

    created: datetime = Field(frozen=True)
    """
    The date that the workspace was created.
    """

    dataSources: "builtins.list[Literal['AMAZON_OPENSEARCH_SERVICE', 'CLOUDWATCH', 'PROMETHEUS', 'XRAY', 'TIMESTREAM', 'SITEWISE', 'ATHENA', 'REDSHIFT', 'TWINMAKER']]" = Field(
        frozen=True
    )
    """
    Specifies the Amazon Web Services data sources that have been configured to have IAM
    roles and permissions created to allow Amazon Managed Grafana to read data from
    these sources.
    """

    description: str = Field(default=None, frozen=True)
    """
    The user-defined description of the workspace.
    """

    endpoint: str = Field(frozen=True)
    """
    The URL that users can use to access the Grafana console in the workspace.
    """

    grafanaVersion: str
    """
    The version of Grafana supported in this workspace.
    """
    id: str = Field(frozen=True)
    """
    The unique ID of this workspace.
    """
    modified: datetime = Field(frozen=True)
    """
    The most recent date that the workspace was modified.
    """

    organizationRoleName: "str | None" = None
    """
    The name of the IAM role that is used to access resources through Organizations.
    """

    notificationDestinations: "builtins.list[Literal['SNS']]" = Field(
        default_factory=list, frozen=True
    )
    """
    The Amazon Web Services notification channels that Amazon Managed Grafana can
    automatically create IAM roles and permissions for, to allow Amazon Managed Grafana
    to use these channels.
    """
    organizationalUnits: "builtins.list[str]" = Field(default_factory=list, frozen=True)
    """
    Specifies the organizational units that this workspace is allowed to use data
    sources from, if this workspace is in an account that is part of an organization.
    """

    permissionType: "Literal['CUSTOMER_MANAGED', 'SERVICE_MANAGED'] | None" = None
    """
    If this is ``SERVICE_MANAGED``, and the workplace was created through the Amazon
    Managed Grafana console, then Amazon Managed Grafana automatically creates the IAM
    roles and provisions the permissions that the workspace needs to use Amazon Web
    Services data sources and notification channels.
    """

    stackSetName: "str | None" = None
    """
    The name of the CloudFormation stack set that is used to generate IAM roles to be
    used for this workspace.
    """

    status: Literal[
        "ACTIVE",
        "CREATING",
        "DELETING",
        "FAILED",
        "UPDATING",
        "UPGRADING",
        "DELETION_FAILED",
        "CREATION_FAILED",
        "UPDATE_FAILED",
        "UPGRADE_FAILED",
        "LICENSE_REMOVAL_FAILED",
        "VERSION_UPDATING",
        "VERSION_UPDATE_FAILED",
        "DEGRADED",
    ] = Field(frozen=True)
    """
    The current status of the workspace.
    """

    workspaceRoleArn: "str | None" = None
    """
    The IAM role that grants permissions to the Amazon Web Services resources that the
    workspace will view data from.

    This role must already exist.
    """

    licenseType: Literal["ENTERPRISE", "ENTERPRISE_FREE_TRIAL"] = Field(
        default=None, frozen=True
    )
    """
    Specifies whether this workspace has a full Grafana Enterprise license.
    """

    freeTrialConsumed: bool = Field(default=None, frozen=True)
    """
    Specifies whether this workspace has already fully used its free trial for Grafana
    Enterprise.
    """

    licenseExpiration: datetime = Field(default=None, frozen=True)
    """
    If this workspace has a full Grafana Enterprise license purchased through Amazon Web
    Services Marketplace, this specifies when the license ends and will need to be
    renewed.

    Purchasing the Enterprise plugins option through Amazon Managed Grafana does not
    have an expiration. It is valid until the license is removed.
    """

    freeTrialExpiration: datetime = Field(default=None, frozen=True)
    """
    If this workspace is currently in the free trial period for Grafana Enterprise, this
    value specifies when that free trial ends.
    """

    authentication: AuthenticationSummary = Field(frozen=True)
    """
    A structure that describes whether the workspace uses SAML, IAM Identity Center, or
    both methods for user authentication.
    """

    vpcConfiguration: "VpcConfiguration | None" = None
    """
    The configuration for connecting to data sources in a private VPC (Amazon Virtual
    Private Cloud).
    """

    networkAccessControl: "NetworkAccessConfiguration | None" = None
    """
    The configuration settings for network access to your workspace.
    """

    grafanaToken: str = Field(default=None, frozen=True)
    """
    The token that ties this workspace to a Grafana Labs account.

    For more information, see
    `Link your account with Grafana Labs <https://docs.aws.amazon.com/grafana/latest/userguide/upgrade-to-Grafana-Enterprise.html#AMG-workspace-register-
    enterprise>`_.
    """

    ipAddressType: "Literal['IPv4', 'DualStack'] | None" = None
    """
    The type of IP addresses supported for connection to the workspace.

    Valid values are ``IPv4`` and ``DualStack``.
    """

    kmsKeyId: "str | None" = None
    """
    The ID or ARN of the Key Management Service key used for encrypting workspace data.
    """

    degradedWorkspaceReason: str = Field(default=None, frozen=True)
    """
    If the workspace is in the ``DEGRADED`` status, this field describes the reason the
    workspace is degraded.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`id` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.id

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`workspaceName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.workspaceName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`id` attribute.
        """
        return hash(self.id)


class ManagedGrafanaServiceAccount(PrimaryBoto3Model):
    """
    A structure that contains the information about one service account.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        ManagedGrafanaServiceAccountManager
    )

    serviceAccountName: str = Field(default=None, alias="name")
    """
    The name of the service account.
    """

    id: str
    """
    The unique ID of the service account.
    """

    isDisabled: str
    """
    Returns true if the service account is disabled.

    Service accounts can be disabled and enabled in the Amazon Managed Grafana console.
    """

    grafanaRole: Literal["ADMIN", "EDITOR", "VIEWER"]
    """
    The role of the service account, which sets the permission level used when calling
    Grafana APIs.
    """

    workspaceId: str | None = None
    """
    The id of the AWS Managed Grafana workspace that this service account belongs to.

    This is not part of the botocore ````ServiceAccountSummary```` shape; it is
    populated onto call results by the
    :py:func:`botocraft.mixins.grafana.service_accounts_add_workspace_context` and
    :py:func:`botocraft.mixins.grafana.service_account_create_to_service_account`
    decorators from call context
    because AWS Managed Grafana service accounts are always scoped to exactly one
    workspace.
    """
    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`serviceAccountName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.serviceAccountName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`id` attribute.
        """
        return hash(self.id)

    @property
    def pk(self) -> OrderedDict[str, Any]:
        """
        The primary key of the service account.

        This is a composite of ``id`` and ``workspaceId`` because AWS Managed Grafana
        service accounts are deleted via
        :py:meth:`botocraft.services.grafana.ManagedGrafanaServiceAccountManager.delete`,
        which requires both.
        """
        return OrderedDict(
            {
                "serviceAccountId": self.id,
                "workspaceId": self.workspaceId,
            }
        )


class ManagedGrafanaServiceAccountToken(PrimaryBoto3Model):
    """
    A structure that contains the information about a service account token.
    """
    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        ManagedGrafanaServiceAccountTokenManager
    )
    tokenName: str = Field(default=None, alias="name")
    """
    The name of the service account token.
    """
    id: str
    """
    The unique ID of the service account token.
    """

    createdAt: datetime
    """
    When the service account token was created.
    """

    expiresAt: datetime
    """
    When the service account token will expire.
    """

    lastUsedAt: "datetime | None" = None
    """
    The last time the token was used to authorize a Grafana HTTP API.
    """

    workspaceId: str | None = None
    """
    The id of the AWS Managed Grafana workspace that this service account token belongs
    to.

    Populated onto call results by the
    :py:func:`botocraft.mixins.grafana.service_account_tokens_add_context` and
    :py:func:`botocraft.mixins.grafana.service_account_token_create_to_token_with_key`
    decorators from call
    context.
    """

    serviceAccountId: str | None = None
    """
    The id of the service account that owns this service account token.

    Populated onto call results by the
    :py:func:`botocraft.mixins.grafana.service_account_tokens_add_context` and
    :py:func:`botocraft.mixins.grafana.service_account_token_create_to_token_with_key`
    decorators from call
    context.
    """

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`tokenName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.tokenName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`id` attribute.
        """
        return hash(self.id)

    @property
    def pk(self) -> OrderedDict[str, Any]:
        """
        The primary key of the service account token.

        This is a composite of ``id``, ``serviceAccountId``, and ``workspaceId`` because
        AWS Managed Grafana service account tokens are deleted via
        :py:meth:`botocraft.services.grafana.ManagedGrafanaServiceAccountTokenManager.delete`,
        which requires all three.
        """
        return OrderedDict(
            {
                "tokenId": self.id,
                "serviceAccountId": self.serviceAccountId,
                "workspaceId": self.workspaceId,
            }
        )


class ManagedGrafanaServiceAccountTokenWithKey(Boto3Model):
    """
    A structure that contains the information about a service account token.

    This structure is returned when creating the token. It is important to store the
    ``key`` that is returned, as it is not retrievable at a later time.

    If you lose the key, you can delete and recreate the token, which will create a new
    key.
    """
    key: "str | None" = Field(default=None, repr=False)
    """
    The plaintext token key.

    Excluded from the default ````repr```` so it is not accidentally leaked by
    ````print()````/logging a model instance. AWS Managed Grafana never returns this
    value again after this response.
    """

    id: str
    """
    The unique ID of the service account token.
    """

    name: str
    """
    The name of the service account token.
    """

    workspaceId: str | None = None
    """
    The id of the AWS Managed Grafana workspace that this service account token belongs
    to.
    """

    serviceAccountId: str | None = None
    """
    The id of the service account that owns this service account token.
    """

# =======================
# Request/Response Models
# =======================


class CreateWorkspaceResponse(Boto3Model):
    workspace: ManagedGrafanaWorkspace
    """
    A structure containing data about the workspace that was created.
    """


class DescribeWorkspaceResponse(Boto3Model):
    workspace: ManagedGrafanaWorkspace
    """
    A structure containing information about the workspace.
    """


class UpdateWorkspaceResponse(Boto3Model):
    workspace: ManagedGrafanaWorkspace
    """
    A structure containing data about the workspace that was created.
    """


class DeleteWorkspaceResponse(Boto3Model):
    workspace: ManagedGrafanaWorkspace
    """
    A structure containing information about the workspace that was deleted.
    """

class IdpMetadata(Boto3Model):
    """
    A structure containing the identity provider (IdP) metadata used to integrate the
    identity provider with this workspace.

    You can specify the metadata either by providing a URL to its location in the
    ``url`` parameter, or by specifying the full metadata in XML format in the ``xml``
    parameter. Specifying both will cause an error.
    """

    url: "str | None" = None
    """
    The URL of the location containing the IdP metadata.
    """

    xml: "str | None" = None
    """
    The full IdP metadata, in XML format.
    """

class AssertionAttributes(Boto3Model):
    """
    A structure that defines which attributes in the IdP assertion are to be used to
    define information about the users authenticated by the IdP to use the workspace.
    """

    name: "str | None" = None
    """
    The name of the attribute within the SAML assertion to use as the user full
    "friendly" names for SAML users.
    """

    login: "str | None" = None
    """
    The name of the attribute within the SAML assertion to use as the login names for
    SAML users.
    """
    email: "str | None" = None
    """
    The name of the attribute within the SAML assertion to use as the email names for
    SAML users.
    """

    groups: "str | None" = None
    """
    The name of the attribute within the SAML assertion to use as the user full
    "friendly" names for user groups.
    """

    role: "str | None" = None
    """
    The name of the attribute within the SAML assertion to use as the user roles.
    """
    org: "str | None" = None
    """
    The name of the attribute within the SAML assertion to use as the user full
    "friendly" names for the users' organizations.
    """

class RoleValues(Boto3Model):
    """
    This structure defines which groups defined in the SAML assertion attribute are to
    be mapped to the Grafana ``Admin`` and ``Editor`` roles in the workspace.

    SAML authenticated users not part of ``Admin`` or ``Editor`` role groups have
    ``Viewer`` permission over the workspace.
    """
    editor: "builtins.list[str] | None" = Field(default_factory=list)
    """
    A list of groups from the SAML assertion attribute to grant the Grafana ``Editor``
    role to.
    """

    admin: "builtins.list[str] | None" = Field(default_factory=list)
    """
    A list of groups from the SAML assertion attribute to grant the Grafana ``Admin``
    role to.
    """
class SamlConfiguration(Boto3Model):
    """
    A structure containing information about how this workspace works with SAML.
    """

    idpMetadata: IdpMetadata
    """
    A structure containing the identity provider (IdP) metadata used to integrate the
    identity provider with this workspace.
    """

    assertionAttributes: "AssertionAttributes | None" = None
    """
    A structure that defines which attributes in the SAML assertion are to be used to
    define information about the users authenticated by that IdP to use the workspace.
    """

    roleValues: "RoleValues | None" = None
    """
    A structure containing arrays that map group names in the SAML assertion to the
    Grafana ``Admin`` and ``Editor`` roles in the workspace.
    """

    allowedOrganizations: "builtins.list[str] | None" = Field(default_factory=list)
    """
    Lists which organizations defined in the SAML assertion are allowed to use the
    Amazon Managed Grafana workspace.

    If this is empty, all organizations in the assertion attribute have access.
    """

    loginValidityDuration: "int | None" = None
    """
    How long a sign-on session by a SAML user is valid, before the user has to sign on
    again.
    """

class SamlAuthentication(Boto3Model):
    """
    A structure containing information about how this workspace works with SAML.
    """

    status: Literal["CONFIGURED", "NOT_CONFIGURED"]
    """
    Specifies whether the workspace's SAML configuration is complete.
    """
    configuration: "SamlConfiguration | None" = None
    """
    A structure containing details about how this workspace works with SAML.
    """

class AwsSsoAuthentication(Boto3Model):
    """
    A structure containing information about how this workspace works with IAM Identity
    Center.
    """

    ssoClientId: "str | None" = None
    """
    The ID of the IAM Identity Center-managed application that is created by Amazon
    Managed Grafana.
    """

class AuthenticationDescription(Boto3Model):
    """
    A structure containing information about the user authentication methods used by the
    workspace.
    """

    providers: "builtins.list[Literal['AWS_SSO', 'SAML']]"
    """
    Specifies whether this workspace uses IAM Identity Center, SAML, or both methods to
    authenticate users to use the Grafana console in the Amazon Managed Grafana
    workspace.
    """
    saml: "SamlAuthentication | None" = None
    """
    A structure containing information about how this workspace works with SAML,
    including what attributes within the assertion are to be mapped to user information
    in the workspace.
    """

    awsSso: "AwsSsoAuthentication | None" = None
    """
    A structure containing information about how this workspace works with IAM Identity
    Center.
    """
class DescribeWorkspaceAuthenticationResponse(Boto3Model):
    authentication: AuthenticationDescription
    """
    A structure containing information about the authentication methods used in the
    workspace.
    """


class UpdateWorkspaceAuthenticationResponse(Boto3Model):
    authentication: AuthenticationDescription
    """
    A structure that describes the user authentication for this workspace after the
    update is made.
    """


class DescribeWorkspaceConfigurationResponse(Boto3Model):
    configuration: str
    """
    The configuration string for the workspace that you requested.

    For more information about the format and configuration options available, see
    `Working in your Grafana workspace <https://docs.aws.amazon.com/grafana/latest/userguide/AMG-
    configure-workspace.html>`_.
    """

    grafanaVersion: "str | None" = None
    """
    The supported Grafana version for the workspace.
    """

class UpdateWorkspaceConfigurationResponse(Boto3Model):
    pass


class AssociateLicenseResponse(Boto3Model):
    workspace: ManagedGrafanaWorkspace
    """
    A structure containing data about the workspace.
    """


class DisassociateLicenseResponse(Boto3Model):
    workspace: ManagedGrafanaWorkspace
    """
    A structure containing information about the workspace.
    """
class User(Boto3Model):
    """
    A structure that specifies one user or group in the workspace.
    """
    id: str
    """
    The ID of the user or group.
    """

    type: Literal["SSO_USER", "SSO_GROUP"]
    """
    Specifies whether this is a single user or a group.
    """
class PermissionEntry(Boto3Model):
    """
    A structure containing the identity of one user or group and the ``Admin``,
    ``Editor``, or ``Viewer`` role that they have.
    """

    user: User
    """
    A structure with the ID of the user or group with this role.
    """
    role: Literal["ADMIN", "EDITOR", "VIEWER"]
    """
    Specifies whether the user or group has the ``Admin``, ``Editor``, or ``Viewer``
    role.
    """


class ListPermissionsResponse(Boto3Model):
    nextToken: "str | None" = None
    """
    The token to use in a subsequent ``ListPermissions`` operation to return the next
    set of results.
    """

    permissions: "builtins.list[PermissionEntry]"
    """
    The permissions returned by the operation.
    """

class UpdateInstruction(Boto3Model):
    """Contains the instructions for one Grafana role permission update in a
    `UpdatePermissions <https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdatePermissions.html>`_ operation.
    """

    action: Literal["ADD", "REVOKE"]
    """
    Specifies whether this update is to add or revoke role permissions.
    """

    role: Literal["ADMIN", "EDITOR", "VIEWER"]
    """
    The role to add or revoke for the user or the group specified in ``users``.
    """

    users: "builtins.list[User]"
    """
    A structure that specifies the user or group to add or revoke the role for.
    """


class UpdateError(Boto3Model):
    """A structure containing information about one error encountered while performing an
    `UpdatePermissions <https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdatePermissions.html>`_ operation.
    """
    code: int
    """
    The error code.
    """

    message: str
    """
    The message for this error.
    """
    causedBy: UpdateInstruction
    """
    Specifies which permission update caused the error.
    """


class UpdatePermissionsResponse(Boto3Model):
    errors: "builtins.list[UpdateError]"
    """
    An array of structures that contain the errors from the operation, if any.
    """


class ListVersionsResponse(Boto3Model):
    nextToken: "str | None" = None
    """
    The token to use in a subsequent ``ListVersions`` operation to return the next set
    of results.
    """

    grafanaVersions: "builtins.list[str] | None" = Field(default_factory=list)
    """
    The Grafana versions available to create.

    If a workspace ID is included in the request, the Grafana versions to which this
    workspace can be upgraded.
    """

class CreateWorkspaceServiceAccountResponse(Boto3Model):
    id: str
    """
    The ID of the service account.
    """
    name: str
    """
    The name of the service account.
    """

    grafanaRole: Literal["ADMIN", "EDITOR", "VIEWER"]
    """
    The permission level given to the service account.
    """

    workspaceId: str
    """
    The workspace with which the service account is associated.
    """


class ListWorkspaceServiceAccountsResponse(Boto3Model):
    nextToken: "str | None" = None
    """
    The token to use when requesting the next set of service accounts.
    """

    serviceAccounts: "builtins.list[ManagedGrafanaServiceAccount]"
    """
    An array of structures containing information about the service accounts.
    """

    workspaceId: str
    """
    The workspace to which the service accounts are associated.
    """

class DeleteWorkspaceServiceAccountResponse(Boto3Model):
    serviceAccountId: str
    """
    The ID of the service account deleted.
    """
    workspaceId: str
    """
    The ID of the workspace where the service account was deleted.
    """


class CreateWorkspaceServiceAccountTokenResponse(Boto3Model):
    serviceAccountToken: ManagedGrafanaServiceAccountTokenWithKey
    """
    Information about the created token, including the key.

    Be sure to store the key securely.
    """

    serviceAccountId: str
    """
    The ID of the service account where the token was created.
    """

    workspaceId: str
    """
    The ID of the workspace where the token was created.
    """


class ListWorkspaceServiceAccountTokensResponse(Boto3Model):
    nextToken: "str | None" = None
    """
    The token to use when requesting the next set of service accounts.
    """

    serviceAccountTokens: "builtins.list[ManagedGrafanaServiceAccountToken]"
    """
    An array of structures containing information about the tokens.
    """

    serviceAccountId: str
    """
    The ID of the service account where the tokens reside.
    """

    workspaceId: str
    """
    The ID of the workspace where the tokens reside.
    """

class DeleteWorkspaceServiceAccountTokenResponse(Boto3Model):
    tokenId: str
    """
    The ID of the token that was deleted.
    """

    serviceAccountId: str
    """
    The ID of the service account where the token was deleted.
    """

    workspaceId: str
    """
    The ID of the workspace where the token was deleted.
    """
