# This file is automatically generated by botocraft.  Do not edit directly.
# mypy: disable-error-code="index, override, assignment, union-attr, misc"
from pydantic import Field
from botocraft.mixins.kinesis import consumers_include_tags
import builtins
from .abstract import (
    Boto3Model,
    ReadonlyBoto3Model,
    PrimaryBoto3Model,
    ReadonlyPrimaryBoto3Model,
    Boto3ModelManager,
    ReadonlyBoto3ModelManager,
)
from botocraft.mixins.kinesis import streams_include_tags
from .abstract import PrimaryBoto3ModelQuerySet
from botocraft.mixins.kinesis import stream_include_tags
from botocraft.mixins.tags import TagsDictMixin
from typing import ClassVar, Literal, Any, Type as ModelType, cast
from botocraft.mixins.kinesis import KinesisStreamManagerMixin
from .common import Tag
from botocraft.mixins.kinesis import KinesisStreamModelMixin
from botocraft.mixins.kinesis import consumer_include_tags
from botocraft.mixins.kinesis import KinesisConsumerManagerMixin
from botocraft.mixins.kinesis import KinesisShardManagerMixin
from collections import OrderedDict
from datetime import datetime

# ===============
# Managers
# ===============


class KinesisStreamManager(KinesisStreamManagerMixin, Boto3ModelManager):
    service_name: str = "kinesis"

    @stream_include_tags
    def get(
        self,
        StreamName: str,
        *,
        StreamARN: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> "KinesisStream | None":
        """
        Provides a summarized description of the specified Kinesis data stream without
        the shard list.

        Args:
            StreamName: The name of the stream to describe.

        Keyword Args:
            StreamARN: The ARN of the stream.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            StreamName=self.serialize(StreamName),
            StreamARN=self.serialize(StreamARN),
            StreamId=self.serialize(StreamId),
        )
        _response = self.client.describe_stream_summary(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeStreamSummaryOutput(**_response)

        if response and response.StreamDescriptionSummary:
            self.sessionize(response.StreamDescriptionSummary)
            return response.StreamDescriptionSummary
        return None

    @streams_include_tags
    def list(
        self,
        *,
        Limit: "int | None" = None,
        ExclusiveStartStreamName: "str | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists your Kinesis data streams.

        Keyword Args:
            Limit: The maximum number of streams to list. The default value is 100. If
                you specify a value greater than 100, at
                most 100 results are returned.
            ExclusiveStartStreamName: The name of the stream to start the list with.
        """
        paginator = self.client.get_paginator("list_streams")
        args: dict[str, Any] = dict(
            Limit=self.serialize(Limit),
            ExclusiveStartStreamName=self.serialize(ExclusiveStartStreamName),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListStreamsOutput(**_response)
            if response.StreamSummaries:
                results.extend(response.StreamSummaries)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(
        self,
        StreamName: str,
        *,
        EnforceConsumerDeletion: "bool | None" = None,
        StreamARN: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> None:
        """
        Deletes a Kinesis data stream and all its shards and data.

        You must shut down any applications that are operating on the stream before you
        delete the stream. If an application attempts to operate on a deleted stream, it
        receives the
        exception ``ResourceNotFoundException``.

        Args:
            StreamName: The name of the stream to delete.

        Keyword Args:
            EnforceConsumerDeletion: If this parameter is unset (``null``) or if you set
                it to ``false``, and the stream has
                registered consumers, the call to ``DeleteStream`` fails with a
                ``ResourceInUseException``.
            StreamARN: The ARN of the stream.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            StreamName=self.serialize(StreamName),
            EnforceConsumerDeletion=self.serialize(EnforceConsumerDeletion),
            StreamARN=self.serialize(StreamARN),
            StreamId=self.serialize(StreamId),
        )
        self.client.delete_stream(**{k: v for k, v in args.items() if v is not None})

    def update_shard_count(
        self,
        TargetShardCount: int,
        ScalingType: Literal["UNIFORM_SCALING"],
        *,
        StreamName: "str | None" = None,
        StreamARN: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> "UpdateShardCountOutput":
        """
        Updates the shard count of the specified stream to the specified number of
        shards.

        This API is only supported for the data streams with the provisioned capacity
        mode.

        Args:
            TargetShardCount: The new number of shards. This value has the following
                default limits. By default, you cannot do
                the following:
            ScalingType: The scaling type. Uniform scaling creates shards of equal size.

        Keyword Args:
            StreamName: The name of the stream.
            StreamARN: The ARN of the stream.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            TargetShardCount=self.serialize(TargetShardCount),
            ScalingType=self.serialize(ScalingType),
            StreamName=self.serialize(StreamName),
            StreamARN=self.serialize(StreamARN),
            StreamId=self.serialize(StreamId),
        )
        _response = self.client.update_shard_count(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = UpdateShardCountOutput(**_response)

        results: "UpdateShardCountOutput" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("UpdateShardCountOutput", results)

    def update_stream_mode(
        self,
        StreamARN: str,
        StreamModeDetails: "KinesisStreamModeDetails",
        *,
        StreamId: "str | None" = None,
        WarmThroughputMiBps: "int | None" = None,
    ) -> None:
        """
        Updates the capacity mode of the data stream.

        Currently, in Kinesis Data Streams, you can choose between an **on- demand**
        capacity mode and a **provisioned** capacity mode for your data stream.

        Args:
            StreamARN: Specifies the ARN of the data stream whose capacity mode you want
                to update.
            StreamModeDetails: Specifies the capacity mode to which you want to set your
                data stream. Currently, in Kinesis Data
                Streams, you can choose between an **on-demand** capacity mode and a
                **provisioned** capacity mode for your data
                streams.

        Keyword Args:
            StreamId: Not Implemented. Reserved for future use.
            WarmThroughputMiBps: The target warm throughput in MB/s that the stream
                should be scaled to handle. This represents
                the throughput capacity that will be immediately available for write
                operations. This field is only valid when the
                stream mode is being updated to on-demand.
        """
        args: dict[str, Any] = dict(
            StreamARN=self.serialize(StreamARN),
            StreamModeDetails=self.serialize(StreamModeDetails),
            StreamId=self.serialize(StreamId),
            WarmThroughputMiBps=self.serialize(WarmThroughputMiBps),
        )
        self.client.update_stream_mode(
            **{k: v for k, v in args.items() if v is not None}
        )

    def update_stream_warm_throughput(
        self,
        WarmThroughputMiBps: int,
        *,
        StreamARN: "str | None" = None,
        StreamName: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> "UpdateStreamWarmThroughputOutput":
        """
        Updates the warm throughput configuration for the specified Amazon Kinesis Data
        Streams on-demand data stream.

        This operation allows you to proactively scale your on-demand data stream to a
        specified throughput level, enabling better
        performance for sudden traffic spikes.

        Args:
            WarmThroughputMiBps: The target warm throughput in MB/s that the stream
                should be scaled to handle. This represents
                the throughput capacity that will be immediately available for write
                operations.

        Keyword Args:
            StreamARN: The ARN of the stream to be updated.
            StreamName: The name of the stream to be updated.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            WarmThroughputMiBps=self.serialize(WarmThroughputMiBps),
            StreamARN=self.serialize(StreamARN),
            StreamName=self.serialize(StreamName),
            StreamId=self.serialize(StreamId),
        )
        _response = self.client.update_stream_warm_throughput(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = UpdateStreamWarmThroughputOutput(**_response)

        results: "UpdateStreamWarmThroughputOutput" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("UpdateStreamWarmThroughputOutput", results)

    def update_max_record_size(
        self,
        MaxRecordSizeInKiB: int,
        *,
        StreamARN: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> None:
        """
        This allows you to update the ``MaxRecordSize`` of a single record that you can
        write to, and read from a stream.

        You can ingest and digest single records up to 10240 KiB.

        Args:
            MaxRecordSizeInKiB: The maximum record size of a single record in KiB that
                you can write to, and read from a stream.
                Specify a value between 1024 and 10240 KiB (1 to 10 MiB). If you specify
                a value that is out of this range,
                ``UpdateMaxRecordSize`` sends back an ``ValidationException`` message.

        Keyword Args:
            StreamARN: The Amazon Resource Name (ARN) of the stream for the
                ``MaxRecordSize`` update.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            MaxRecordSizeInKiB=self.serialize(MaxRecordSizeInKiB),
            StreamARN=self.serialize(StreamARN),
            StreamId=self.serialize(StreamId),
        )
        self.client.update_max_record_size(
            **{k: v for k, v in args.items() if v is not None}
        )


class KinesisConsumerManager(KinesisConsumerManagerMixin, Boto3ModelManager):
    service_name: str = "kinesis"

    @consumer_include_tags
    def get(
        self,
        ConsumerARN: str,
        *,
        StreamARN: "str | None" = None,
        ConsumerName: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> "KinesisConsumer | None":
        """
        To get the description of a registered consumer, provide the ARN of the
        consumer.

        Alternatively, you can provide the ARN of the data stream and the name you gave
        the consumer when you registered it. You may also provide all three parameters,
        as long as they don't conflict with each other. If you don't know the name or
        ARN of the consumer that you want to
        describe, you can use the ListStreamConsumers operation to get a list of the
        descriptions of all the consumers that are
        currently registered with a given data stream.

        Args:
            ConsumerARN: The ARN returned by Kinesis Data Streams when you registered
                the consumer.

        Keyword Args:
            StreamARN: The ARN of the Kinesis data stream that the consumer is
                registered with. For more information, see
                `Amazon Resource Names (ARNs) and Amazon Web Services Service Namespaces
                <https://docs.aws.amazon.com/general/latest/gr/aws-arns-and- namespaces.html#arn-syntax-kinesis-streams>`_.
            ConsumerName: The name that you gave to the consumer.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            StreamARN=self.serialize(StreamARN),
            ConsumerName=self.serialize(ConsumerName),
            ConsumerARN=self.serialize(ConsumerARN),
            StreamId=self.serialize(StreamId),
        )
        _response = self.client.describe_stream_consumer(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeStreamConsumerOutput(**_response)

        if response and response.ConsumerDescription:
            self.sessionize(response.ConsumerDescription)
            return response.ConsumerDescription
        return None

    @consumers_include_tags
    def list(
        self,
        StreamARN: str,
        *,
        StreamCreationTimestamp: "datetime | None" = None,
        StreamId: "str | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists the consumers registered to receive data from a stream using enhanced fan-
        out, and provides information about each consumer.

        Args:
            StreamARN: The ARN of the Kinesis data stream for which you want to list the
                registered consumers. For more
                information, see `Amazon Resource Names (ARNs) and Amazon Web Services
                Service Namespaces
                <https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-kinesis-streams>`_.

        Keyword Args:
            StreamCreationTimestamp: Specify this input parameter to distinguish data
                streams that have the same name. For
                example, if you create a data stream and then delete it, and you later
                create another data stream with the same
                name, you can use this input parameter to specify which of the two
                streams you want to list the consumers for.
            StreamId: Not Implemented. Reserved for future use.
        """
        paginator = self.client.get_paginator("list_stream_consumers")
        args: dict[str, Any] = dict(
            StreamARN=self.serialize(StreamARN),
            StreamCreationTimestamp=self.serialize(StreamCreationTimestamp),
            StreamId=self.serialize(StreamId),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListStreamConsumersOutput(**_response)
            if response.Consumers:
                results.extend(response.Consumers)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(
        self,
        ConsumerARN: str,
        *,
        StreamARN: "str | None" = None,
        ConsumerName: "str | None" = None,
        StreamId: "str | None" = None,
    ) -> None:
        """
        To deregister a consumer, provide its ARN.

        Alternatively, you can provide the ARN of the data stream and the name you gave
        the consumer when you registered it. You may also provide all three parameters,
        as long as they don't conflict with
        each other. If you don't know the name or ARN of the consumer that you want to
        deregister, you can use the
        ListStreamConsumers operation to get a list of the descriptions of all the
        consumers that are currently registered with
        a given data stream. The description of a consumer contains its name and ARN.

        Args:
            ConsumerARN: The ARN returned by Kinesis Data Streams when you registered
                the consumer. If you don't know the ARN of
                the consumer that you want to deregister, you can use the
                ListStreamConsumers operation to get a list of the
                descriptions of all the consumers that are currently registered with a
                given data stream. The description of a
                consumer contains its ARN.

        Keyword Args:
            StreamARN: The ARN of the Kinesis data stream that the consumer is
                registered with. For more information, see
                `Amazon Resource Names (ARNs) and Amazon Web Services Service Namespaces
                <https://docs.aws.amazon.com/general/latest/gr/aws-arns-and- namespaces.html#arn-syntax-kinesis-streams>`_.
            ConsumerName: The name that you gave to the consumer.
            StreamId: Not Implemented. Reserved for future use.
        """
        args: dict[str, Any] = dict(
            StreamARN=self.serialize(StreamARN),
            ConsumerName=self.serialize(ConsumerName),
            ConsumerARN=self.serialize(ConsumerARN),
            StreamId=self.serialize(StreamId),
        )
        self.client.deregister_stream_consumer(
            **{k: v for k, v in args.items() if v is not None}
        )


class KinesisShardManager(KinesisShardManagerMixin, Boto3ModelManager):
    service_name: str = "kinesis"


# ==============
# Service Models
# ==============


class KinesisStreamModeDetails(Boto3Model):
    """
    Specifies the capacity mode to which you want to set your data stream.

    Currently, in Kinesis Data Streams, you can choose between an **on-demand** capacity
    mode and a **provisioned** capacity mode for your data streams.
    """

    StreamMode: Literal["PROVISIONED", "ON_DEMAND"]
    """
    Specifies the capacity mode to which you want to set your data stream.

    Currently, in Kinesis Data Streams, you can choose between an **on-demand** capacity
    mode and a **provisioned** capacity mode for your data streams.
    """


class KinesisEnhancedMetrics(Boto3Model):
    """
    Represents enhanced metrics types.
    """

    ShardLevelMetrics: "builtins.list[Literal['IncomingBytes', 'IncomingRecords', 'OutgoingBytes', 'OutgoingRecords', 'WriteProvisionedThroughputExceeded', 'ReadProvisionedThroughputExceeded', 'IteratorAgeMilliseconds', 'ALL']] | None" = Field(
        default_factory=list
    )
    """
    List of shard-level metrics.
    """

class KinesisWarmThroughput(Boto3Model):
    """
    Represents the warm throughput configuration on the stream.

    This is only present for On-Demand Kinesis Data Streams in accounts that have
    ``MinimumThroughputBillingCommitment`` enabled.
    """

    TargetMiBps: "int | None" = None
    """
    The target warm throughput value on the stream.

    This indicates that the stream is currently scaling towards this target value.
    """

    CurrentMiBps: "int | None" = None
    """
    The current warm throughput value on the stream.

    This is the write throughput in MiBps that the stream is currently scaled to handle.
    """

class KinesisStream(TagsDictMixin, KinesisStreamModelMixin, PrimaryBoto3Model):
    """
    The summary of a stream.
    """

    tag_class: ClassVar[ModelType[Boto3Model]] = Tag
    manager_class: ClassVar[ModelType[Boto3ModelManager]] = KinesisStreamManager

    StreamName: str
    """
    The name of a stream.
    """

    StreamARN: str = Field(frozen=True)
    """
    The ARN of the stream.
    """

    StreamStatus: Literal["CREATING", "DELETING", "ACTIVE", "UPDATING"] = Field(
        frozen=True
    )
    """
    The status of the stream.
    """

    StreamModeDetails: "KinesisStreamModeDetails | None" = None
    """
    Specifies the capacity mode to which you want to set your data stream.

    Currently, in Kinesis Data Streams, you can choose between an **on-demand** capacity
    mode and a **provisioned** capacity mode for your data streams.
    """

    StreamCreationTimestamp: datetime = Field(default=None, frozen=True)
    """
    The timestamp at which the stream was created.
    """

    ShardCount: int | None = None
    """
    Requested shard count used when creating a provisioned stream.
    """

    WarmThroughputMiBps: int | None = None
    """
    Requested warm throughput in MiB/s used during create or update calls.
    """

    Tags: "builtins.list[Tag] | None" = Field(default_factory=list)
    """
    Tags associated with the stream.
    """

    StreamId: str = Field(default=None, frozen=True)
    """
    Not Implemented.

    Reserved for future use.
    """

    RetentionPeriodHours: int = Field(default=None, frozen=True)
    """
    The current retention period, in hours.
    """

    EnhancedMonitoring: "builtins.list[KinesisEnhancedMetrics]" = Field(
        default_factory=list, frozen=True
    )
    """
    Represents the current enhanced monitoring settings of the stream.
    """

    EncryptionType: Literal["NONE", "KMS"] = Field(default=None, frozen=True)
    """
    The encryption type used.

    This value is one of the following:
    """

    KeyId: str = Field(default=None, frozen=True)
    """
    The GUID for the customer-managed Amazon Web Services KMS key to use for encryption.

    This value can be a globally unique identifier, a fully specified ARN to either an
    alias or a key, or an alias name prefixed by "alias/".You can also use a master key
    owned by Kinesis Data Streams by specifying the alias ``aws/kinesis``.
    """

    OpenShardCount: int = Field(default=None, frozen=True)
    """
    The number of open shards in the stream.
    """

    ConsumerCount: int = Field(default=None, frozen=True)
    """
    The number of enhanced fan-out consumers registered with the stream.
    """
    WarmThroughput: KinesisWarmThroughput = Field(default=None, frozen=True)
    """
    The warm throughput in MB/s for the stream.

    This represents the throughput capacity that will be immediately available for write
    operations.
    """
    MaxRecordSizeInKiB: int = Field(default=None, frozen=True)
    """
    The maximum record size of a single record in kibibyte (KiB) that you can write to,
    and read from a stream.
    """
    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`StreamName` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.StreamName
    @property
    def arn(self) -> str | None:
        """
        Return the ARN of the model.

        This is the value of the :py:attr:`StreamARN` attribute.

        Returns:
            The ARN of the model instance.
        """
        return self.StreamARN
    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`StreamName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.StreamName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`StreamName` attribute.
        """
        return hash(self.StreamName)

    @property
    def shards(self) -> "list[KinesisShard] | None":
        """
        Return the shards that belong to this stream.
        """
        try:
            pk = OrderedDict(
                {
                    "StreamARN": self.StreamARN,
                }
            )
        except AttributeError:
            return []
        return KinesisShard.objects.using(self.session).list(**pk)  # type: ignore[arg-type]

    def update_shard_count(
        self, TargetShardCount: int, ScalingType: Literal["UNIFORM_SCALING"]
    ) -> "UpdateShardCountOutput":
        """
        Update the shard count for this stream.

        Args:
            TargetShardCount: The new number of shards. This value has the following
                default limits. By default, you cannot do
                the following:
            ScalingType: The scaling type. Uniform scaling creates shards of equal size.
        """
        return (
            cast("KinesisStreamManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .update_shard_count(
                TargetShardCount, ScalingType, StreamARN=cast("str", self.StreamARN)
            )
        )

    def update_stream_mode(
        self,
        StreamModeDetails: KinesisStreamModeDetails,
        WarmThroughputMiBps: "int | None" = None,
    ) -> "None":
        """
        Update the capacity mode for this stream.

        Args:
            StreamModeDetails: Specifies the capacity mode to which you want to set your
                data stream. Currently, in Kinesis Data
                Streams, you can choose between an **on-demand** capacity mode and a
                **provisioned** capacity mode for your data
                streams.

        Keyword Args:
            WarmThroughputMiBps: The target warm throughput in MB/s that the stream
                should be scaled to handle. This represents
                the throughput capacity that will be immediately available for write
                operations. This field is only valid when the
                stream mode is being updated to on-demand.
        """
        return (
            cast("KinesisStreamManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .update_stream_mode(
                StreamModeDetails,
                StreamARN=cast("str", self.StreamARN),
                WarmThroughputMiBps=WarmThroughputMiBps,
            )
        )

    def update_stream_warm_throughput(
        self, WarmThroughputMiBps: int
    ) -> "UpdateStreamWarmThroughputOutput":
        """
        Update the warm throughput for this stream.

        Args:
            WarmThroughputMiBps: The target warm throughput in MB/s that the stream
                should be scaled to handle. This represents
                the throughput capacity that will be immediately available for write
                operations.
        """
        return (
            cast("KinesisStreamManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .update_stream_warm_throughput(
                WarmThroughputMiBps, StreamARN=cast("str", self.StreamARN)
            )
        )

    def update_max_record_size(self, MaxRecordSizeInKiB: int) -> "None":
        """
        Update the maximum record size for this stream.

        Args:
            MaxRecordSizeInKiB: The maximum record size of a single record in KiB that
                you can write to, and read from a stream.
                Specify a value between 1024 and 10240 KiB (1 to 10 MiB). If you specify
                a value that is out of this range,
                ``UpdateMaxRecordSize`` sends back an ``ValidationException`` message.
        """
        return (
            cast("KinesisStreamManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .update_max_record_size(
                MaxRecordSizeInKiB, StreamARN=cast("str", self.StreamARN)
            )
        )
class KinesisConsumer(TagsDictMixin, PrimaryBoto3Model):
    """
    An object that represents the details of the consumer you registered.

    This type of object is returned by RegisterStreamConsumer.
    """

    tag_class: ClassVar[ModelType[Boto3Model]] = Tag
    manager_class: ClassVar[ModelType[Boto3ModelManager]] = KinesisConsumerManager

    ConsumerName: str
    """
    The name of the consumer is something you choose when you register the consumer.
    """
    ConsumerARN: str = Field(frozen=True)
    """
    When you register a consumer, Kinesis Data Streams generates an ARN for it.

    You need this ARN to be able to call SubscribeToShard.
    """

    ConsumerStatus: Literal["CREATING", "DELETING", "ACTIVE"] = Field(frozen=True)
    """
    A consumer can't read data while in the ``CREATING`` or ``DELETING`` states.
    """

    ConsumerCreationTimestamp: datetime = Field(frozen=True)
    """
    
    """

    Tags: "builtins.list[Tag] | None" = Field(default_factory=list)
    """
    Tags associated with the consumer.
    """
    StreamARN: str = Field(default=None, frozen=True)
    """
    The ARN of the stream with which you registered the consumer.
    """
    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`ConsumerARN` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.ConsumerARN
    @property
    def arn(self) -> str | None:
        """
        Return the ARN of the model.

        This is the value of the :py:attr:`ConsumerARN` attribute.

        Returns:
            The ARN of the model instance.
        """
        return self.ConsumerARN
    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`ConsumerName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.ConsumerName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`ConsumerARN` attribute.
        """
        return hash(self.ConsumerARN)
class HashKeyRange(Boto3Model):
    """
    The range of possible hash key values for the shard, which is a set of ordered
    contiguous positive integers.
    """

    StartingHashKey: str
    """
    The starting hash key of the hash key range.
    """
    EndingHashKey: str
    """
    The ending hash key of the hash key range.
    """
class SequenceNumberRange(Boto3Model):
    """
    The range of possible sequence numbers for the shard.
    """

    StartingSequenceNumber: str
    """
    The starting sequence number for the range.
    """

    EndingSequenceNumber: "str | None" = None
    """
    The ending sequence number for the range.

    Shards that are in the OPEN state have an ending sequence number of ``null``.
    """

class KinesisShard(ReadonlyPrimaryBoto3Model):
    """
    A uniquely identified group of data records in a Kinesis data stream.
    """
    manager_class: ClassVar[ModelType[Boto3ModelManager]] = KinesisShardManager

    ShardId: str
    """
    The unique identifier of the shard within the stream.
    """

    ParentShardId: "str | None" = None
    """
    The shard ID of the shard's parent.
    """
    AdjacentParentShardId: "str | None" = None
    """
    The shard ID of the shard adjacent to the shard's parent.
    """
    HashKeyRange: "HashKeyRange"
    """
    The range of possible hash key values for the shard, which is a set of ordered
    contiguous positive integers.
    """

    SequenceNumberRange: "SequenceNumberRange"
    """
    The range of possible sequence numbers for the shard.
    """

    StreamARN: str | None = None
    """
    ARN of stream that owns this shard.
    """

    StreamName: str | None = None
    """
    Name of stream that owns this shard.
    """

    @property
    def pk(self) -> OrderedDict[str, Any]:
        """
        Stream-scoped composite identity for the shard.
        """
        return (
            OrderedDict({"StreamARN": self.StreamARN, "ShardId": self.ShardId})
            if self.StreamARN
            else OrderedDict({"StreamName": self.StreamName, "ShardId": self.ShardId})
        )

    def iterator(
        self,
        ShardIteratorType: "Literal['AT_SEQUENCE_NUMBER', 'AFTER_SEQUENCE_NUMBER', 'TRIM_HORIZON', 'LATEST', 'AT_TIMESTAMP']",
        StartingSequenceNumber: "str | None" = None,
        Timestamp: "datetime | None" = None,
    ) -> "str | None":
        """
        Get an iterator for this shard.

        Args:
            ShardIteratorType: Determines how the shard iterator is used to start
                reading data records from the shard.

        Keyword Args:
            StartingSequenceNumber: The sequence number of the data record in the shard
                from which to start reading. Used with
                shard iterator type AT_SEQUENCE_NUMBER and AFTER_SEQUENCE_NUMBER.
            Timestamp: The time stamp of the data record from which to start reading.
                Used with shard iterator type
                AT_TIMESTAMP. A time stamp is the Unix epoch date with precision in
                milliseconds. For example,
                ``2016-04-04T19:58:46.480-00:00`` or ``1459799926.480``. If a record
                with this exact time stamp does not exist, the
                iterator returned is for the next (later) record. If the time stamp is
                older than the current trim horizon, the
                iterator returned is for the oldest untrimmed data record
                (TRIM_HORIZON).
        """
        return (
            cast("KinesisShardManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .iterator(
                cast("str", self.ShardId),
                ShardIteratorType,
                StreamARN=self.StreamARN,
                StreamName=self.StreamName,
                StartingSequenceNumber=StartingSequenceNumber,
                Timestamp=Timestamp,
            )
        )


class KinesisRecord(Boto3Model):
    """
    The unit of data of the Kinesis data stream, which is composed of a sequence number,
    a partition key, and a data blob.
    """

    SequenceNumber: str
    """
    The unique identifier of the record within its shard.
    """

    ApproximateArrivalTimestamp: "datetime | None" = None
    """
    The approximate time that the record was inserted into the stream.
    """

    Data: bytes
    """
    The data blob.

    The data in the blob is both opaque and immutable to Kinesis Data Streams, which
    does not inspect, interpret, or change the data in the blob in any way. When the
    data blob (the payload before base64-encoding) is added to the partition key size,
    the total size must not exceed the maximum record size (1 MiB).
    """

    PartitionKey: str
    """
    Identifies which shard in the stream the data record is assigned to.
    """

    EncryptionType: "Literal['NONE', 'KMS'] | None" = None
    """
    The encryption type used on the record.

    This parameter can be one of the following values:
    """

    StreamARN: str | None = None
    """
    ARN of stream that produced this record.
    """

    ShardId: str | None = None
    """
    Shard identifier that produced this record.
    """
# =======================
# Request/Response Models
# =======================


class StreamDescriptionSummary(Boto3Model):
    """
    Represents the output for DescribeStreamSummary.
    """

    StreamName: str
    """
    The name of the stream being described.
    """
    StreamARN: str
    """
    The Amazon Resource Name (ARN) for the stream being described.
    """

    StreamId: "str | None" = None
    """
    Not Implemented.

    Reserved for future use.
    """

    StreamStatus: Literal["CREATING", "DELETING", "ACTIVE", "UPDATING"]
    """
    The current status of the stream being described.

    The stream status is one of the following states:
    """

    StreamModeDetails: "KinesisStreamModeDetails | None" = None
    """
    Specifies the capacity mode to which you want to set your data stream.

    Currently, in Kinesis Data Streams, you can choose between an **on-demand**
    ycapacity mode and a **provisioned** capacity mode for your data streams.
    """

    RetentionPeriodHours: int
    """
    The current retention period, in hours.
    """
    StreamCreationTimestamp: datetime
    """
    The approximate time that the stream was created.
    """

    EnhancedMonitoring: "builtins.list[KinesisEnhancedMetrics]"
    """
    Represents the current enhanced monitoring settings of the stream.
    """

    EncryptionType: "Literal['NONE', 'KMS'] | None" = None
    """
    The encryption type used.

    This value is one of the following:
    """

    KeyId: "str | None" = None
    """
    The GUID for the customer-managed Amazon Web Services KMS key to use for encryption.

    This value can be a globally unique identifier, a fully specified ARN to either an
    alias or a key, or an alias name prefixed by "alias/".You can also use a master key
    owned by Kinesis Data Streams by specifying the alias ``aws/kinesis``.
    """

    OpenShardCount: int
    """
    The number of open shards in the stream.
    """

    ConsumerCount: "int | None" = None
    """
    The number of enhanced fan-out consumers registered with the stream.
    """

    WarmThroughput: "KinesisWarmThroughput | None" = None
    """
    The warm throughput in MB/s for the stream.

    This represents the throughput capacity that will be immediately available for write
    operations.
    """

    MaxRecordSizeInKiB: "int | None" = None
    """
    The maximum record size of a single record in kibibyte (KiB) that you can write to,
    and read from a stream.
    """

class DescribeStreamSummaryOutput(Boto3Model):
    StreamDescriptionSummary: "StreamDescriptionSummary"
    """
    A StreamDescriptionSummary containing information about the stream.
    """


class ListStreamsOutput(Boto3Model):
    """
    Represents the output for ``ListStreams``.
    """

    StreamNames: "builtins.list[str]"
    """
    The names of the streams that are associated with the Amazon Web Services account
    making the ``ListStreams`` request.
    """

    HasMoreStreams: bool
    """
    If set to ``true``, there are more streams available to list.
    """

    NextToken: "str | None" = None
    """
    
    """

    StreamSummaries: "builtins.list[KinesisStream] | None" = Field(default_factory=list)
    """
    
    """
class UpdateShardCountOutput(Boto3Model):
    StreamName: "str | None" = None
    """
    The name of the stream.
    """
    CurrentShardCount: "int | None" = None
    """
    The current number of shards.
    """
    TargetShardCount: "int | None" = None
    """
    The updated number of shards.
    """

    StreamARN: "str | None" = None
    """
    The ARN of the stream.
    """

class UpdateStreamWarmThroughputOutput(Boto3Model):
    StreamARN: "str | None" = None
    """
    The ARN of the stream that was updated.
    """

    StreamName: "str | None" = None
    """
    The name of the stream that was updated.
    """

    WarmThroughput: "KinesisWarmThroughput | None" = None
    """
    Specifies the updated warm throughput configuration for your data stream.
    """

class ConsumerDescription(Boto3Model):
    """
    An object that represents the details of a registered consumer.

    This type of object is returned by DescribeStreamConsumer.
    """

    ConsumerName: str
    """
    The name of the consumer is something you choose when you register the consumer.
    """

    ConsumerARN: str
    """
    When you register a consumer, Kinesis Data Streams generates an ARN for it.

    You need this ARN to be able to call SubscribeToShard.
    """

    ConsumerStatus: Literal["CREATING", "DELETING", "ACTIVE"]
    """
    A consumer can't read data while in the ``CREATING`` or ``DELETING`` states.
    """

    ConsumerCreationTimestamp: datetime
    """
    
    """

    StreamARN: str
    """
    The ARN of the stream with which you registered the consumer.
    """

class DescribeStreamConsumerOutput(Boto3Model):
    ConsumerDescription: "ConsumerDescription"
    """
    An object that represents the details of the consumer.
    """


class ListStreamConsumersOutput(Boto3Model):
    Consumers: "builtins.list[KinesisConsumer] | None" = Field(default_factory=list)
    """
    An array of JSON objects.

    Each object represents one registered consumer.
    """

    NextToken: "str | None" = None
    """
When the number of consumers that are registered with the data stream is greater than
the default value for the
``MaxResults`` parameter, or if you explicitly specify a value for ``MaxResults`` that
is less than the number of
registered consumers, the response includes a pagination token named ``NextToken``. You
can specify this ``NextToken``
value in a subsequent call to ``ListStreamConsumers`` to list the next set of registered
consumers. For more information
about the use of this pagination token when calling the ``ListStreamConsumers``
operation, see
ListStreamConsumersInput$NextToken.
    """
