# This file is automatically generated by botocraft.  Do not edit directly.
# mypy: disable-error-code="index, override, assignment, union-attr, misc"
from botocraft.services.common import Tag
from datetime import datetime
from botocraft.mixins.logs import convert_log_group_tags
import builtins
from .abstract import PrimaryBoto3ModelQuerySet
from botocraft.mixins.logs import create_log_group_extended
from .abstract import (
    Boto3Model,
    ReadonlyBoto3Model,
    PrimaryBoto3Model,
    ReadonlyPrimaryBoto3Model,
    Boto3ModelManager,
    ReadonlyBoto3ModelManager,
)
from botocraft.mixins.logs import query_definition_from_put
from botocraft.mixins.logs import LogGroupManagerMixin
from botocraft.mixins.logs import paginate_query_definitions
from pydantic import Field
from typing import ClassVar, Literal, Any, Type as ModelType, cast
from botocraft.mixins.logs import QueryDefinitionManagerMixin
from botocraft.mixins.logs import convert_log_groups_tags
from botocraft.mixins.tags import TagsDictMixin

# ===============
# Managers
# ===============


class LogGroupManager(LogGroupManagerMixin, Boto3ModelManager):
    service_name: str = "logs"

    @create_log_group_extended
    def create(self, model: "LogGroup", tags: "dict[str, str] | None" = None) -> None:
        """
        Creates a log group with the specified name.

        You can create up to 1,000,000 log groups per Region per account.

        Args:
            model: The :py:class:`LogGroup` to create.

        Keyword Args:
            tags: The key-value pairs to use for the tags.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            logGroupName=data.get("logGroupName"),
            kmsKeyId=data.get("kmsKeyId"),
            tags=self.serialize(tags),
            logGroupClass=data.get("logGroupClass"),
            deletionProtectionEnabled=data.get("deletionProtectionEnabled"),
        )
        self.client.create_log_group(**{k: v for k, v in args.items() if v is not None})

    def delete(self, logGroupName: str) -> None:
        """
        Deletes the specified log group and permanently deletes all the archived log
        events associated with the log group.

        Args:
            logGroupName: The name of the log group.
        """
        args: dict[str, Any] = dict(logGroupName=self.serialize(logGroupName))
        self.client.delete_log_group(**{k: v for k, v in args.items() if v is not None})

    @convert_log_group_tags
    def get(
        self,
        logGroupIdentifier: str,
        *,
        accountIdentifiers: "builtins.list[str] | None" = None,
        logGroupNamePattern: "str | None" = None,
        limit: "int | None" = None,
        includeLinkedAccounts: "bool | None" = None,
    ) -> "LogGroup | None":
        """
        Returns information about log groups, including data sources that ingest into
        each log group.

        You can return all your log groups or filter the results by prefix. The results
        are ASCII-sorted by log group name.

        Args:
            logGroupIdentifier: The identifier of the log group to get. If this is in
                the same account you are querying, you can
                use the log group name, if you also set ````includeLinkedAccounts```` to
                ````true````, you must use the log group
                ARN.

        Keyword Args:
            accountIdentifiers: When ``includeLinkedAccounts`` is set to ``true``, use
                this parameter to specify the list of
                accounts to search. You can specify as many as 20 account IDs in the
                array.
            logGroupNamePattern: If you specify a string for this parameter, the
                operation returns only log groups that have
                names that match the string based on a case-sensitive substring search.
                For example, if you specify ``DataLogs``,
                log groups named ``DataLogs``, ``aws/DataLogs``, and ``GroupDataLogs``
                would match, but ``datalogs``, ``Data/log/s``
                and ``Groupdata`` would not match.
            limit: The maximum number of items returned. If you don't specify a value,
                the default is up to 50 items.
            includeLinkedAccounts: If you are using a monitoring account, set this to
                ``true`` to have the operation return log
                groups in the accounts listed in ``accountIdentifiers``.
        """
        args: dict[str, Any] = dict(
            accountIdentifiers=self.serialize(accountIdentifiers),
            logGroupNamePattern=self.serialize(logGroupNamePattern),
            limit=self.serialize(limit),
            includeLinkedAccounts=self.serialize(includeLinkedAccounts),
            logGroupIdentifiers=self.serialize([logGroupIdentifier]),
        )
        _response = self.client.describe_log_groups(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeLogGroupsResponse(**_response)

        if response and response.logGroups:
            self.sessionize(response.logGroups[0])
            return response.logGroups[0]
        return None

    @convert_log_groups_tags
    def list(
        self,
        *,
        accountIdentifiers: "builtins.list[str] | None" = None,
        logGroupNamePrefix: "str | None" = None,
        logGroupNamePattern: "str | None" = None,
        limit: "int | None" = None,
        includeLinkedAccounts: "bool | None" = None,
        logGroupClass: "Literal['STANDARD', 'INFREQUENT_ACCESS', 'DELIVERY'] | None" = None,
        logGroupIdentifiers: "builtins.list[str] | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Returns information about log groups, including data sources that ingest into
        each log group.

        You can return all your log groups or filter the results by prefix. The results
        are ASCII-sorted by log group name.

        Keyword Args:
            accountIdentifiers: When ``includeLinkedAccounts`` is set to ``true``, use
                this parameter to specify the list of
                accounts to search. You can specify as many as 20 account IDs in the
                array.
            logGroupNamePrefix: The prefix to match.
            logGroupNamePattern: If you specify a string for this parameter, the
                operation returns only log groups that have
                names that match the string based on a case-sensitive substring search.
                For example, if you specify ``DataLogs``,
                log groups named ``DataLogs``, ``aws/DataLogs``, and ``GroupDataLogs``
                would match, but ``datalogs``, ``Data/log/s``
                and ``Groupdata`` would not match.
            limit: The maximum number of items returned. If you don't specify a value,
                the default is up to 50 items.
            includeLinkedAccounts: If you are using a monitoring account, set this to
                ``true`` to have the operation return log
                groups in the accounts listed in ``accountIdentifiers``.
            logGroupClass: Use this parameter to limit the results to only those log
                groups in the specified log group class. If
                you omit this parameter, log groups of all classes can be returned.
            logGroupIdentifiers: Use this array to filter the list of log groups
                returned. If you specify this parameter, the
                only other filter that you can choose to specify is
                ``includeLinkedAccounts``.
        """
        paginator = self.client.get_paginator("describe_log_groups")
        args: dict[str, Any] = dict(
            accountIdentifiers=self.serialize(accountIdentifiers),
            logGroupNamePrefix=self.serialize(logGroupNamePrefix),
            logGroupNamePattern=self.serialize(logGroupNamePattern),
            limit=self.serialize(limit),
            includeLinkedAccounts=self.serialize(includeLinkedAccounts),
            logGroupClass=self.serialize(logGroupClass),
            logGroupIdentifiers=self.serialize(logGroupIdentifiers),
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = DescribeLogGroupsResponse(**_response)
            if response.logGroups:
                results.extend(response.logGroups)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def get_fields(
        self,
        *,
        logGroupName: "str | None" = None,
        time: "int | None" = None,
        logGroupIdentifier: "str | None" = None,
    ) -> "builtins.list[LogGroupField]":
        """
        Returns a list of the fields that are included in log events in the specified
        log group.

        Includes the percentage of log events that contain each field. The search is
        limited to a time period that you specify.

        Keyword Args:
            logGroupName: The name of the log group to search.
            time: The time to set as the center of the query. If you specify ``time``,
                the 8 minutes before and 8 minutes after
                this time are searched. If you omit ``time``, the most recent 15 minutes
                up to the current time are searched.
            logGroupIdentifier: Specify either the name or ARN of the log group to view.
                If the log group is in a source account
                and you are using a monitoring account, you must specify the ARN.
        """
        args: dict[str, Any] = dict(
            logGroupName=self.serialize(logGroupName),
            time=self.serialize(time),
            logGroupIdentifier=self.serialize(logGroupIdentifier),
        )
        _response = self.client.get_log_group_fields(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetLogGroupFieldsResponse(**_response)

        results: "builtins.list[LogGroupField]" = None
        if response is not None:
            results = response.logGroupFields

        self.sessionize(results)
        return cast("builtins.list[LogGroupField]", results)

    def start_query(
        self,
        startTime: int,
        endTime: int,
        queryString: str,
        *,
        queryLanguage: "Literal['CWLI', 'SQL', 'PPL'] | None" = None,
        logGroupName: "str | None" = None,
        logGroupNames: "builtins.list[str] | None" = None,
        logGroupIdentifiers: "builtins.list[str] | None" = None,
        limit: "int | None" = None,
    ) -> "StartQueryResponse":
        """
        Starts a query of one or more log groups or data sources using CloudWatch Logs
        Insights.

        You specify the log groups or data sources and time range to query and the query
        string to use. You can query up to 10 data sources in a single query.

        Args:
            startTime: The beginning of the time range to query. The range is inclusive,
                so the specified start time is included
                in the query. Specified as epoch time, the number of seconds since
                ``January 1, 1970, 00:00:00 UTC``.
            endTime: The end of the time range to query. The range is inclusive, so the
                specified end time is included in the
                query. Specified as epoch time, the number of seconds since ``January 1,
                1970, 00:00:00 UTC``.
            queryString: The query string to use. For more information, see `CloudWatch
                Logs Insights Query Syntax
                <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html>`_.

        Keyword Args:
            queryLanguage: Specify the query language to use for this query. The options
                are Logs Insights QL, OpenSearch PPL,
                and OpenSearch SQL. For more information about the query languages that
                CloudWatch Logs supports, see `Supported
                query languages <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_Languages.html>`_.
            logGroupName: The log group on which to perform the query.
            logGroupNames: The list of log groups to be queried. You can include up to
                50 log groups.
            logGroupIdentifiers: The list of log groups to query. You can include up to
                50 log groups.
            limit: The maximum number of log events to return from the query. The
                maximum limit is 100,000. The maximum events
                returned in a single GetQueryResults API call is 10,000 log events per
                request. You can retrieve up to 100,000 log
                event results from a query by paginating with the ``nextToken``. 100,000
                limit is only supported for Logs Insights
                QL and is currently not supported for PPL and SQL query languages.
        """
        args: dict[str, Any] = dict(
            startTime=self.serialize(startTime),
            endTime=self.serialize(endTime),
            queryString=self.serialize(queryString),
            queryLanguage=self.serialize(queryLanguage),
            logGroupName=self.serialize(logGroupName),
            logGroupNames=self.serialize(logGroupNames),
            logGroupIdentifiers=self.serialize(logGroupIdentifiers),
            limit=self.serialize(limit),
        )
        _response = self.client.start_query(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = StartQueryResponse(**_response)

        results: "StartQueryResponse" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("StartQueryResponse", results)

    def get_query_results(
        self,
        queryId: str,
        *,
        nextToken: "str | None" = None,
        maxItems: "int | None" = None,
    ) -> "GetQueryResultsResponse":
        """
        Returns the results from the specified query.

        Args:
            queryId: The ID number of the query.

        Keyword Args:
            nextToken: The token for the next set of items to return. The token expires
                after 1 hour.
            maxItems: The maximum number of log events to return in the response. The
                maximum is 10,000 log events per request.
                You can retrieve up to 100,000 log event results from a query by
                paginating with the ``nextToken``.
        """
        args: dict[str, Any] = dict(
            queryId=self.serialize(queryId),
            nextToken=self.serialize(nextToken),
            maxItems=self.serialize(maxItems),
        )
        _response = self.client.get_query_results(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetQueryResultsResponse(**_response)

        results: "GetQueryResultsResponse" = None
        if response is not None:
            results = response

        self.sessionize(results)
        return cast("GetQueryResultsResponse", results)


class QueryDefinitionManager(QueryDefinitionManagerMixin, Boto3ModelManager):
    service_name: str = "logs"

    @query_definition_from_put
    def create(self, model: "QueryDefinition", clientToken: "str | None" = None) -> str:
        """
        Creates or updates a query definition for CloudWatch Logs Insights.

        For more information, see `Analyzing Log Data with CloudWatch Logs Insights <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html>`_.

        Args:
            model: The :py:class:`QueryDefinition` to create.

        Keyword Args:
            clientToken: Used as an idempotency token, to avoid returning an exception
                if the service receives the same request
                twice because of a network error.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            name=data.get("name"),
            queryString=data.get("queryString"),
            queryLanguage=data.get("queryLanguage"),
            queryDefinitionId=data.get("queryDefinitionId"),
            logGroupNames=data.get("logGroupNames"),
            clientToken=self.serialize(clientToken),
            parameters=data.get("parameters"),
        )
        _response = self.client.put_query_definition(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = PutQueryDefinitionResponse(**_response)

        self.sessionize(response.queryDefinitionId)
        return cast("str", response.queryDefinitionId)

    @query_definition_from_put
    def update(self, model: "QueryDefinition", clientToken: "str | None" = None) -> str:
        """
        Creates or updates a query definition for CloudWatch Logs Insights.

        For more information, see `Analyzing Log Data with CloudWatch Logs Insights <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html>`_.

        Args:
            model: The :py:class:`QueryDefinition` to update.

        Keyword Args:
            clientToken: Used as an idempotency token, to avoid returning an exception
                if the service receives the same request
                twice because of a network error.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            name=data.get("name"),
            queryString=data.get("queryString"),
            queryLanguage=data.get("queryLanguage"),
            queryDefinitionId=data.get("queryDefinitionId"),
            logGroupNames=data.get("logGroupNames"),
            clientToken=self.serialize(clientToken),
            parameters=data.get("parameters"),
        )
        _response = self.client.put_query_definition(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = PutQueryDefinitionResponse(**_response)

        self.sessionize(response.queryDefinitionId)
        return cast("str", response.queryDefinitionId)

    def delete(self, queryDefinitionId: str) -> None:
        """
        Deletes a saved CloudWatch Logs Insights query definition.

        A query definition contains details about a saved CloudWatch Logs Insights
        query.

        Args:
            queryDefinitionId: The ID of the query definition that you want to delete.
                You can use `DescribeQueryDefinitions
                <https://docs.aws.amazon.c om/AmazonCloudWatchLogs/latest/APIReference/API_DescribeQueryDefinitions.html>`_ to
                retrieve the IDs of your saved query definitions.
        """
        args: dict[str, Any] = dict(queryDefinitionId=self.serialize(queryDefinitionId))
        self.client.delete_query_definition(
            **{k: v for k, v in args.items() if v is not None}
        )

    @paginate_query_definitions
    def list(
        self,
        *,
        queryLanguage: "Literal['CWLI', 'SQL', 'PPL'] | None" = None,
        queryDefinitionNamePrefix: "str | None" = None,
        maxResults: "int | None" = None,
        nextToken: "str | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        This operation returns a paginated list of your saved CloudWatch Logs Insights
        query definitions.

        You can retrieve query definitions from the current account or from a source
        account that is linked to the current account.

        Keyword Args:
            queryLanguage: The query language used for this query. For more information
                about the query languages that
                CloudWatch Logs supports, see `Supported query languages
                <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_Languages.html>`_.
            queryDefinitionNamePrefix: Use this parameter to filter your results to only
                the query definitions that have names
                that start with the prefix you specify.
            maxResults: Limits the number of returned query definitions to the specified
                number.
            nextToken: The token for the next set of items to return. The token expires
                after 24 hours.
        """
        args: dict[str, Any] = dict(
            queryLanguage=self.serialize(queryLanguage),
            queryDefinitionNamePrefix=self.serialize(queryDefinitionNamePrefix),
            maxResults=self.serialize(maxResults),
            nextToken=self.serialize(nextToken),
        )
        _response = self.client.describe_query_definitions(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = DescribeQueryDefinitionsResponse(**_response)
        if response and response.queryDefinitions:
            self.sessionize(response.queryDefinitions)
            return PrimaryBoto3ModelQuerySet(response.queryDefinitions)
        return PrimaryBoto3ModelQuerySet([])


# ==============
# Service Models
# ==============


class LogGroup(TagsDictMixin, PrimaryBoto3Model):
    """
    Represents a log group.
    """

    tag_class: ClassVar[ModelType[Boto3Model]] = Tag
    manager_class: ClassVar[ModelType[Boto3ModelManager]] = LogGroupManager

    Arn: str = Field(default=None, alias="arn")
    """
    The Amazon Resource Name (ARN) of the log group.

    This version of the ARN includes a trailing ``:*`` after the log group name.
    """

    logGroupName: "str | None" = None
    """
    The name of the log group.
    """

    creationTime: int = Field(default=None, frozen=True)
    """
    The creation time of the log group, expressed as the number of milliseconds after
    Jan 1, 1970 00:00:00 UTC.
    """

    retentionInDays: int = Field(default=None, frozen=True)
    """
    The number of days to retain the log events in the specified log group.

    Possible values are: 1, 3, 5, 7, 14, 30, 60, 90,
    120, 150, 180, 365, 400, 545, 731, 1096, 1827, 2192, 2557, 2922, 3288, and 3653.
    """

    metricFilterCount: int = Field(default=None, frozen=True)
    """
    The number of metric filters.
    """

    storedBytes: int = Field(default=None, frozen=True)
    """
    The number of bytes stored.
    """
    kmsKeyId: "str | None" = None
    """
    The Amazon Resource Name (ARN) of the KMS key to use when encrypting log data.
    """

    dataProtectionStatus: Literal["ACTIVATED", "DELETED", "ARCHIVED", "DISABLED"] = (
        Field(default=None, frozen=True)
    )
    """
    Displays whether this log group has a protection policy, or whether it had one in
    the past.

    For more information, see
    `P utDataProtectionPolicy <https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDataProtectionPolicy
    .html>`_.
    """

    inheritedProperties: "builtins.list[Literal['ACCOUNT_DATA_PROTECTION']]" = Field(
        default_factory=list, frozen=True
    )
    """
    Displays all the properties that this log group has inherited from account-level
    settings.
    """

    logGroupClass: "Literal['STANDARD', 'INFREQUENT_ACCESS', 'DELIVERY'] | None" = None
    """
    This specifies the log group class for this log group.

    There are three classes:
    """

    logGroupArn: str = Field(default=None, frozen=True)
    """
    The Amazon Resource Name (ARN) of the log group.

    This version of the ARN doesn't include a trailing ``:*`` after the log group name.
    """

    deletionProtectionEnabled: "bool | None" = None
    """
    Indicates whether deletion protection is enabled for this log group.

    When enabled, deletion protection blocks all deletion operations until it is
    explicitly disabled.
    """

    bearerTokenAuthenticationEnabled: bool = Field(default=None, frozen=True)
    """
    Indicates whether bearer token authentication is enabled for this log group.

    When enabled, bearer token authentication is allowed on operations until it is
    explicitly disabled.
    """

    Tags: "builtins.list[Tag] | None" = Field(default_factory=list)
    """
    The tags associated with the log group.
    """
    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`Arn` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.Arn
    @property
    def arn(self) -> str | None:
        """
        Return the ARN of the model.

        This is the value of the :py:attr:`Arn` attribute.

        Returns:
            The ARN of the model instance.
        """
        return self.Arn
    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`logGroupName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.logGroupName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`Arn` attribute.
        """
        return hash(self.Arn)

    def get_fields(self, time: "int | None" = None) -> "builtins.list[LogGroupField]":
        """
        Return field statistics for log events in this log group.

        Keyword Args:
            time: The time to set as the center of the query. If you specify ``time``,
                the 8 minutes before and 8 minutes after
                this time are searched. If you omit ``time``, the most recent 15 minutes
                up to the current time are searched.
        """
        return (
            cast("LogGroupManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .get_fields(logGroupName=self.logGroupName, time=time)
        )

    def start_query(
        self,
        startTime: int,
        endTime: int,
        queryString: str,
        queryLanguage: "Literal['CWLI', 'SQL', 'PPL'] | None" = None,
        limit: "int | None" = None,
    ) -> "StartQueryResponse":
        """
        Start a CloudWatch Logs Insights query against this log group.

        Args:
            startTime: The beginning of the time range to query. The range is inclusive,
                so the specified start time is included
                in the query. Specified as epoch time, the number of seconds since
                ``January 1, 1970, 00:00:00 UTC``.
            endTime: The end of the time range to query. The range is inclusive, so the
                specified end time is included in the
                query. Specified as epoch time, the number of seconds since ``January 1,
                1970, 00:00:00 UTC``.
            queryString: The query string to use. For more information, see `CloudWatch
                Logs Insights Query Syntax
                <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html>`_.

        Keyword Args:
            queryLanguage: Specify the query language to use for this query. The options
                are Logs Insights QL, OpenSearch PPL,
                and OpenSearch SQL. For more information about the query languages that
                CloudWatch Logs supports, see `Supported
                query languages <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_Languages.html>`_.
            limit: The maximum number of log events to return from the query. The
                maximum limit is 100,000. The maximum events
                returned in a single GetQueryResults API call is 10,000 log events per
                request. You can retrieve up to 100,000 log
                event results from a query by paginating with the ``nextToken``. 100,000
                limit is only supported for Logs Insights
                QL and is currently not supported for PPL and SQL query languages.
        """
        return (
            cast("LogGroupManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .start_query(
                startTime,
                endTime,
                queryString,
                logGroupName=self.logGroupName,
                queryLanguage=queryLanguage,
                limit=limit,
            )
        )

    def get_query_results(
        self,
        queryId: str,
        nextToken: "str | None" = None,
        maxItems: "int | None" = None,
    ) -> "GetQueryResultsResponse":
        """
        Fetch results for a CloudWatch Logs Insights query.

        Args:
            queryId: The ID number of the query.

        Keyword Args:
            nextToken: The token for the next set of items to return. The token expires
                after 1 hour.
            maxItems: The maximum number of log events to return in the response. The
                maximum is 10,000 log events per request.
                You can retrieve up to 100,000 log event results from a query by
                paginating with the ``nextToken``.
        """
        return (
            cast("LogGroupManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .get_query_results(queryId, nextToken=nextToken, maxItems=maxItems)
        )
class QueryParameter(Boto3Model):
    """
    This structure defines a query parameter for a saved CloudWatch Logs Insights query
    definition.

    Query parameters are supported only for Logs Insights QL queries. They are
    placeholder variables that you can reference in a query string using the
    ``{{parameterName}}`` syntax. Each parameter can include a default value and a
    description.
    """

    name: str
    """
    The name of the query parameter.

    A query parameter name must start with a letter or underscore, and contain only
    letters, digits, and underscores.
    """

    defaultValue: "str | None" = None
    """
    The default value to use for this query parameter if no value is supplied at
    execution time.
    """

    description: "str | None" = None
    """
    A description of the query parameter that explains its purpose or expected values.
    """

class QueryDefinition(PrimaryBoto3Model):
    """
    This structure contains details about a saved CloudWatch Logs Insights query
    definition.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = QueryDefinitionManager

    queryDefinitionName: str = Field(default=None, alias="name")
    """
    The name of the query definition.
    """

    queryLanguage: "Literal['CWLI', 'SQL', 'PPL'] | None" = None
    """
    The query language used for this query.

    For more information about the query languages that CloudWatch Logs supports, see
    `Supported query languages <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_Languages.html>`_.
    """
    queryDefinitionId: "str | None" = None
    """
    The unique ID of the query definition.
    """

    queryString: "str | None" = None
    """
    The query string to use for this definition.

    For more information, see
    `CloudWatch Logs Insights Query Syntax <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html>`_.
    """
    lastModified: int = Field(default=None, frozen=True)
    """
    The date that the query definition was most recently modified.
    """

    logGroupNames: "builtins.list[str] | None" = Field(default_factory=list)
    """
    If this query definition contains a list of log groups that it is limited to, that
    list appears here.
    """

    parameters: "builtins.list[QueryParameter] | None" = Field(default_factory=list)
    """
    If this query definition contains a list of query parameters that define placeholder
    variables for the query string, that list appears here.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`queryDefinitionId` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.queryDefinitionId

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`queryDefinitionName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.queryDefinitionName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`queryDefinitionId` attribute.
        """
        return hash(self.queryDefinitionId)


# =======================
# Request/Response Models
# =======================


class DescribeLogGroupsResponse(Boto3Model):
    logGroups: "builtins.list[LogGroup] | None" = Field(default_factory=list)
    """
    An array of structures, where each structure contains the information about one log
    group.
    """
    nextToken: "str | None" = None
    """
    The token for the next set of items to return.

    The token expires after 24 hours.
    """
class LogGroupField(Boto3Model):
    """
    The fields contained in log events found by a ``GetLogGroupFields`` operation, along
    with the percentage of queried log events in which each field appears.
    """

    name: "str | None" = None
    """
    The name of a log field.
    """

    percent: "int | None" = None
    """
    The percentage of log events queried that contained the field.
    """

class GetLogGroupFieldsResponse(Boto3Model):
    logGroupFields: "builtins.list[LogGroupField] | None" = Field(default_factory=list)
    """
    The array of fields found in the query.

    Each object in the array contains the name of the field, along with the percentage
    of time it appeared in the log events that were queried.
    """

class StartQueryResponse(Boto3Model):
    queryId: "str | None" = None
    """
    The unique ID of the query.
    """

class ResultField(Boto3Model):
    """
    Contains one field from one log event returned by a CloudWatch Logs Insights query,
    along with the value of that field.

    For more information about the fields that are generated by CloudWatch logs, see
    `Supported Logs and Discovered Fields <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData-discoverable-fields.html>`_.
    """

    field: "str | None" = None
    """
    The log event field.
    """

    value: "str | None" = None
    """
    The value of this field.
    """

class QueryStatistics(Boto3Model):
    """
    Contains the number of log events scanned by the query, the number of log events
    that matched the query criteria, and the total number of bytes in the log events
    that were scanned.

    If the query involved log groups that have field index policies, the estimated
    number of skipped log events and the total bytes of those skipped log events are
    included. Using field indexes to skip log events in queries reduces scan volume and
    improves performance. For more information, see
    `Create field indexes to improve query performance and reduce scan volume <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatchLogs-Field-Indexing.html>`_.
    """

    recordsMatched: "float | None" = None
    """
    The number of log events that matched the query string.
    """

    recordsScanned: "float | None" = None
    """
    The total number of log events scanned during the query.
    """

    estimatedRecordsSkipped: "float | None" = None
    """
    An estimate of the number of log events that were skipped when processing this
    query, because the query contained an indexed field.

    Skipping these entries lowers query costs and improves the query performance time.
    For more information about field indexes, see
    `PutIndexPolicy <https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutIndexPolicy.html>`_.
    """

    bytesScanned: "float | None" = None
    """
    The total number of bytes in the log events scanned during the query.
    """

    estimatedBytesSkipped: "float | None" = None
    """
    An estimate of the number of bytes in the log events that were skipped when
    processing this query, because the query contained an indexed field.

    Skipping these entries lowers query costs and improves the query performance time.
    For more information about field indexes, see
    `PutIndexPolicy <https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutIndexPolicy.html>`_.
    """

    logGroupsScanned: "float | None" = None
    """
    The number of log groups that were scanned by this query.
    """

class GetQueryResultsResponse(Boto3Model):
    queryLanguage: "Literal['CWLI', 'SQL', 'PPL'] | None" = None
    """
    The query language used for this query.

    For more information about the query languages that CloudWatch Logs supports, see
    `Supported query languages <https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData_Languages.html>`_.
    """
    results: "builtins.list[builtins.list[ResultField]] | None" = Field(
        default_factory=list
    )
    """
    The log events that matched the query criteria during the most recent time it ran.
    """
    statistics: "QueryStatistics | None" = None
    """
    Includes the number of log events scanned by the query, the number of log events
    that matched the query criteria, and the total number of bytes in the scanned log
    events.

    These values reflect the full raw results of the query.
    """
    status: "Literal['Scheduled', 'Running', 'Complete', 'Failed', 'Cancelled', 'Timeout', 'Unknown'] | None" = None
    """
    The status of the most recent running of the query.

    Possible values are ``Cancelled``, ``Complete``, ``Failed``, ``Running``,
    ``Scheduled``, ``Timeout``, and ``Unknown``.
    """

    encryptionKey: "str | None" = None
    """
If you associated an KMS key with the CloudWatch Logs Insights query results in this
account, this field displays the
ARN of the key that's used to encrypt the query results when
`StartQuery <https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_StartQuery.html>`_ stores them.
    """
    nextToken: "str | None" = None
    """
    If there are more log events remaining in the results, the response includes a
    ``nextToken``.

    You can use this token in a subsequent ``GetQueryResults`` request to get the next
    set of results. You can retrieve up to 100,000 log event results from a query by
    paginating with this token. This is only supported for Logs Insights QL and is
    currently not supported for PPL and SQL query languages.
    """

class PutQueryDefinitionResponse(Boto3Model):
    queryDefinitionId: "str | None" = None
    """
    The ID of the query definition.
    """

class DeleteQueryDefinitionResponse(Boto3Model):
    success: "bool | None" = None
    """
    A value of TRUE indicates that the operation succeeded.

    FALSE indicates that the operation failed.
    """
class DescribeQueryDefinitionsResponse(Boto3Model):
    queryDefinitions: "builtins.list[QueryDefinition] | None" = Field(
        default_factory=list
    )
    """
    The list of query definitions that match your request.
    """

    nextToken: "str | None" = None
    """
    The token for the next set of items to return.

    The token expires after 24 hours.
    """
