# This file is automatically generated by botocraft.  Do not edit directly.
# mypy: disable-error-code="index, override, assignment, union-attr, misc"
from pydantic import Field
from botocraft.mixins.ses import refresh_custom_verification_template_after_mutation
from botocraft.mixins.ses import SESReceiptRuleSetManagerMixin
from botocraft.mixins.ses import template_metadata_to_models
from typing import Literal, cast
from botocraft.mixins.ses import SESReceiptFilterManagerMixin
from botocraft.mixins.ses import SESTemplateManagerMixin
import builtins
from botocraft.mixins.ses import custom_verification_template_response_to_model
from .abstract import (
    Boto3Model,
    ReadonlyBoto3Model,
    PrimaryBoto3Model,
    ReadonlyPrimaryBoto3Model,
    Boto3ModelManager,
    ReadonlyBoto3ModelManager,
)
from typing import ClassVar, Any, Type as ModelType
from botocraft.mixins.ses import identity_names_to_models
from botocraft.mixins.ses import SESIdentityManagerMixin
from botocraft.mixins.ses import SESCustomVerificationEmailTemplateManagerMixin
from botocraft.mixins.ses import SESConfigurationSetManagerMixin
from datetime import datetime
from botocraft.mixins.tags import TagsDictMixin
from .abstract import PrimaryBoto3ModelQuerySet

# ===============
# Managers
# ===============


class SESIdentityManager(SESIdentityManagerMixin, Boto3ModelManager):
    service_name: str = "ses"

    @identity_names_to_models
    def list(
        self,
        *,
        IdentityType: "Literal['EmailAddress', 'Domain'] | None" = None,
        MaxItems: "int | None" = None,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Returns a list containing all of the identities (email addresses and domains)
        for your Amazon Web Services account in the current Amazon Web Services Region,
        regardless of verification status.

        Keyword Args:
            IdentityType: The type of the identities to list. Possible values are
                "EmailAddress" and "Domain". If this parameter
                is omitted, then all identities are listed.
            MaxItems: The maximum number of identities per page. Possible values are
                1-1000 inclusive.
        """
        paginator = self.client.get_paginator("list_identities")
        args: dict[str, Any] = dict(
            IdentityType=self.serialize(IdentityType), MaxItems=self.serialize(MaxItems)
        )
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListIdentitiesResponse(**_response)
            if response.Identities:
                results.extend(response.Identities)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results


class SESConfigurationSetManager(SESConfigurationSetManagerMixin, Boto3ModelManager):
    service_name: str = "ses"

    def list(self, *, MaxItems: "int | None" = None) -> PrimaryBoto3ModelQuerySet:
        """
        Provides a list of the configuration sets associated with your Amazon SES
        account in the current Amazon Web Services
        Region. For information about using configuration sets, see `Monitoring Your
        Amazon SES Sending
        Activity <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html>`_ in the *Amazon SES Developer Guide.*

        Keyword Args:
            MaxItems: The number of configuration sets to return.

        """
        paginator = self.client.get_paginator("list_configuration_sets")
        args: dict[str, Any] = dict(MaxItems=self.serialize(MaxItems))
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = SESListConfigurationSetsResponse(**_response)
            if response.ConfigurationSets:
                results.extend(response.ConfigurationSets)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, name: str) -> None:
        """
        Deletes a configuration set.

        Configuration sets enable you to publish email sending events. For information about using configuration sets, see the `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-
        activity.html>`_.

        Args:
            name: The name of the configuration set to delete.
        """
        args: dict[str, Any] = dict(ConfigurationSetName=self.serialize(name))
        self.client.delete_configuration_set(
            **{k: v for k, v in args.items() if v is not None}
        )


class SESTemplateManager(SESTemplateManagerMixin, Boto3ModelManager):
    service_name: str = "ses"

    def get(self, name: str) -> "SESTemplate | None":
        """
        Displays the template object (which includes the Subject line, HTML part and
        text part) for the template you specify.

        Args:
            name: The name of the template to retrieve.
        """
        args: dict[str, Any] = dict(TemplateName=self.serialize(name))
        _response = self.client.get_template(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = GetTemplateResponse(**_response)

        if response and response.Template:
            self.sessionize(response.Template)
            return response.Template
        return None

    @template_metadata_to_models
    def list(self, *, MaxItems: "int | None" = None) -> PrimaryBoto3ModelQuerySet:
        """
        Lists the email templates present in your Amazon SES account in the current
        Amazon Web Services Region.

        Keyword Args:
            MaxItems: The maximum number of templates to return. This value must be at
                least 1 and less than or equal to 100. If
                more than 100 items are requested, the page size will automatically set
                to 100. If you do not specify a value, 10 is
                the default page size.
        """
        paginator = self.client.get_paginator("list_templates")
        args: dict[str, Any] = dict(MaxItems=self.serialize(MaxItems))
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListTemplatesResponse(**_response)
            if response.TemplatesMetadata:
                results.extend(response.TemplatesMetadata)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, name: str) -> None:
        """
        Deletes an email template.

        Args:
            name: The name of the template to be deleted.
        """
        args: dict[str, Any] = dict(TemplateName=self.serialize(name))
        self.client.delete_template(**{k: v for k, v in args.items() if v is not None})


class SESCustomVerificationEmailTemplateManager(
    SESCustomVerificationEmailTemplateManagerMixin, Boto3ModelManager
):
    service_name: str = "ses"

    @refresh_custom_verification_template_after_mutation
    def create(self, model: "SESCustomVerificationEmailTemplate") -> None:
        """
        Creates a new custom verification email template.

        Args:
            model: The :py:class:`CustomVerificationEmailTemplate` to create.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            TemplateName=data.get("TemplateName"),
            FromEmailAddress=data.get("FromEmailAddress"),
            TemplateSubject=data.get("TemplateSubject"),
            TemplateContent=data.get("TemplateContent"),
            SuccessRedirectionURL=data.get("SuccessRedirectionURL"),
            FailureRedirectionURL=data.get("FailureRedirectionURL"),
        )
        self.client.create_custom_verification_email_template(
            **{k: v for k, v in args.items() if v is not None}
        )

    @refresh_custom_verification_template_after_mutation
    def update(self, model: "SESCustomVerificationEmailTemplate") -> None:
        """
        Updates an existing custom verification email template.

        Args:
            model: The :py:class:`CustomVerificationEmailTemplate` to update.
        """
        data = model.model_dump(exclude_none=True, by_alias=True)
        args = dict(
            TemplateName=data.get("TemplateName"),
            FromEmailAddress=data.get("FromEmailAddress"),
            TemplateSubject=data.get("TemplateSubject"),
            TemplateContent=data.get("TemplateContent"),
            SuccessRedirectionURL=data.get("SuccessRedirectionURL"),
            FailureRedirectionURL=data.get("FailureRedirectionURL"),
        )
        self.client.update_custom_verification_email_template(
            **{k: v for k, v in args.items() if v is not None}
        )

    @custom_verification_template_response_to_model
    def get(self, name: str) -> "SESCustomVerificationEmailTemplate | None":
        """
        Returns the custom email verification template for the template name you
        specify.

        Args:
            name: The name of the custom verification email template to retrieve.
        """
        args: dict[str, Any] = dict(TemplateName=self.serialize(name))
        _response = self.client.get_custom_verification_email_template(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = SESCustomVerificationEmailTemplate(**_response)

        if response:
            self.sessionize(response)
            return response
        return None

    def list(
        self,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists the existing custom verification email templates for your account in the
        current Amazon Web Services Region.
        """
        paginator = self.client.get_paginator(
            "list_custom_verification_email_templates"
        )
        args: dict[str, Any] = dict()
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListCustomVerificationEmailTemplatesResponse(**_response)
            if response.CustomVerificationEmailTemplates:
                results.extend(response.CustomVerificationEmailTemplates)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, name: str) -> None:
        """
        Deletes an existing custom verification email template.

        Args:
            name: The name of the custom verification email template to delete.
        """
        args: dict[str, Any] = dict(TemplateName=self.serialize(name))
        self.client.delete_custom_verification_email_template(
            **{k: v for k, v in args.items() if v is not None}
        )


class SESReceiptFilterManager(SESReceiptFilterManagerMixin, Boto3ModelManager):
    service_name: str = "ses"

    def list(
        self,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists the IP address filters associated with your Amazon Web Services account in
        the current Amazon Web Services Region.
        """
        args: dict[str, Any] = dict()
        _response = self.client.list_receipt_filters(
            **{k: v for k, v in args.items() if v is not None}
        )
        response = ListReceiptFiltersResponse(**_response)
        if response and response.Filters:
            self.sessionize(response.Filters)
            return PrimaryBoto3ModelQuerySet(response.Filters)
        return PrimaryBoto3ModelQuerySet([])

    def delete(self, name: str) -> None:
        """
        Deletes the specified IP address filter.

        Args:
            name: The name of the IP address filter to delete.
        """
        args: dict[str, Any] = dict(FilterName=self.serialize(name))
        self.client.delete_receipt_filter(
            **{k: v for k, v in args.items() if v is not None}
        )


class SESReceiptRuleSetManager(SESReceiptRuleSetManagerMixin, Boto3ModelManager):
    service_name: str = "ses"

    def list(
        self,
    ) -> PrimaryBoto3ModelQuerySet:
        """
        Lists the receipt rule sets that exist under your Amazon Web Services account in
        the current Amazon Web Services Region.

        If there are additional receipt rule sets to be retrieved, you receive a
        ``NextToken`` that you can provide to the next call to ``ListReceiptRuleSets``
        to retrieve the additional entries.
        """
        paginator = self.client.get_paginator("list_receipt_rule_sets")
        args: dict[str, Any] = dict()
        response_iterator = paginator.paginate(
            **{k: v for k, v in args.items() if v is not None}
        )
        results = []
        for _response in response_iterator:
            if list(_response.keys()) == ["ResponseMetadata"]:
                break
            if "ResponseMetadata" in _response:
                del _response["ResponseMetadata"]
            response = ListReceiptRuleSetsResponse(**_response)
            if response.RuleSets:
                results.extend(response.RuleSets)
            else:
                if getattr(response, "NextToken", None):
                    continue
                break
        self.sessionize(results)
        if results and isinstance(results[0], Boto3Model):
            return PrimaryBoto3ModelQuerySet(results)
        return results

    def delete(self, name: str) -> None:
        """
        Deletes the specified receipt rule set and all of the receipt rules it contains.

        Args:
            name: The name of the receipt rule set to delete.
        """
        args: dict[str, Any] = dict(RuleSetName=self.serialize(name))
        self.client.delete_receipt_rule_set(
            **{k: v for k, v in args.items() if v is not None}
        )


# ==============
# Service Models
# ==============


class SESDestination(Boto3Model):
    """
    Represents the destination of the message, consisting of To:, CC:, and BCC: fields.

    Amazon SES does not support the SMTPUTF8 extension, as described in
    `RFC6531 <https://tools.ietf.org/html/rfc6531>`_.
    For    this reason, the email address string must be 7-bit ASCII. If you want to
    send to or from email addresses that contain    Unicode characters in the domain
    part of an address, you must encode the domain using Punycode. Punycode is not
    permitted in the local part of the email address (the part before the @ sign) nor in
    the "friendly from" name. If you    want to use Unicode characters in the "friendly
    from" name, you must encode the "friendly from" name using MIME encoded-    word
    syntax, as described in
    `Sending raw email using the Amazon SES API <https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html>`_.
    For more information about Punycode, see
    `RFC 3492 <http://tools.ietf.org/html/rfc3492>`_.
    """

    ToAddresses: "builtins.list[str] | None" = Field(default_factory=list)
    """
    The recipients to place on the To: line of the message.
    """

    CcAddresses: "builtins.list[str] | None" = Field(default_factory=list)
    """
    The recipients to place on the CC: line of the message.
    """

    BccAddresses: "builtins.list[str] | None" = Field(default_factory=list)
    """
    The recipients to place on the BCC: line of the message.
    """


class SESContent(Boto3Model):
    """
    Represents textual data, plus an optional character set specification.

    By default, the text must be 7-bit ASCII, due to the constraints of the SMTP
    protocol. If the text must contain any other characters, then you must also specify
    a character set. Examples include UTF-8, ISO-8859-1, and Shift_JIS.
    """

    Data: str
    """
    The textual data of the content.
    """

    Charset: "str | None" = None
    """
    The character set of the content.
    """


class SESBody(Boto3Model):
    """
    Represents the body of the message.

    You can specify text, HTML, or both. If you use both, then the message should
    display correctly in the widest variety of email clients.
    """

    Text: "SESContent | None" = None
    """
    The content of the message, in text format.

    Use this for text-based email clients, or clients on high-latency networks (such as
    mobile devices).
    """

    Html: "SESContent | None" = None
    """
    The content of the message, in HTML format.

    Use this for email clients that can process HTML. You can include clickable links,
    formatted text, and much more in an HTML message.
    """


class SESMessage(Boto3Model):
    """
    Represents the message to be sent, composed of a subject and a body.
    """

    Subject: SESContent
    """
    The subject of the message: A short summary of the content, which appears in the
    recipient's inbox.
    """

    Body: SESBody
    """
    The message body.
    """


class SESMessageTag(Boto3Model):
    """
    Contains the name and value of a tag that you can provide to ``SendEmail`` or
    ``SendRawEmail`` to apply to an email.

    Message tags, which you use with configuration sets, enable you to publish email
    sending events. For information about using configuration sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-
    sending-activity.html>`_.
    """

    Name: str
    """
    The name of the tag.

    The name must meet the following requirements:
    """

    Value: str
    """
    The value of the tag.

    The value must meet the following requirements:
    """


class SESRawMessage(Boto3Model):
    """
    Represents the raw data of the message.
    """

    Data: bytes
    """
    The raw data of the message.

    This data needs to base64-encoded if you are accessing Amazon SES directly through
    the HTTPS interface. If you are accessing Amazon SES using an Amazon Web Services
    SDK, the SDK takes care of the base 64-encoding for you. In all cases, the client
    must ensure that the message format complies with Internet email standards regarding
    email header fields, MIME types, and MIME encoding.
    """


class SESIdentity(PrimaryBoto3Model):
    """
    Represents the verification attributes of a single identity.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = SESIdentityManager
    VerificationStatus: "Literal['Pending', 'Success', 'Failed', 'TemporaryFailure', 'NotStarted'] | None" = None
    """
    The verification status of the identity: "Pending", "Success", "Failed", or
    "TemporaryFailure".
    """

    VerificationToken: "str | None" = None
    """
    The verification token for a domain identity.

    Null for email address identities.
    """

    Identity: "str | None" = None
    """
    Email address or domain represented by this SES sender identity.
    """

    IdentityType: Literal["EmailAddress", "Domain"] | None = None
    """
    Lightweight classification of whether this identity is an email address or domain.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`Identity` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.Identity

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`Identity` attribute.

        Returns:
            The name of the model instance.
        """
        return self.Identity

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`Identity` attribute.
        """
        return hash(self.Identity)

    def send_mail(
        self,
        Destination: SESDestination,
        Message: SESMessage,
        ReplyToAddresses: builtins.list[str] | None = None,
        ReturnPath: str | None = None,
        SourceArn: str | None = None,
        ReturnPathArn: str | None = None,
        Tags: builtins.list[SESMessageTag] | None = None,
        ConfigurationSetName: str | None = None,
    ) -> "str":
        """
        Send an email from this identity.

        Args:
            Destination: The destination for this email, composed of To:, CC:, and BCC:
                fields.
            Message: The message to be sent.

        Keyword Args:
            ReplyToAddresses: The reply-to email address(es) for the message. If the
                recipient replies to the message, each
                reply-to address receives the reply.
            ReturnPath: The email address that bounces and complaints are forwarded to
                when feedback forwarding is enabled. If
                the message cannot be delivered to the recipient, then an error message
                is returned from the recipient's ISP; this
                message is forwarded to the email address specified by the
                ``ReturnPath`` parameter. The ``ReturnPath`` parameter is
                never overwritten. This email address must be either individually
                verified with Amazon SES, or from a domain that
                has been verified with Amazon SES.
            SourceArn: This parameter is used only for sending authorization. It is the
                ARN of the identity that is associated
                with the sending authorization policy that permits you to send for the
                email address specified in the ``Source``
                parameter.
            ReturnPathArn: This parameter is used only for sending authorization. It is
                the ARN of the identity that is
                associated with the sending authorization policy that permits you to use
                the email address specified in the
                ``ReturnPath`` parameter.
            Tags: A list of tags, in the form of name/value pairs, to apply to an email
                that you send using ``SendEmail``. Tags
                correspond to characteristics of the email that you define, so that you
                can publish email sending events.
            ConfigurationSetName: The name of the configuration set to use when you send
                an email using ``SendEmail``.
        """
        return (
            cast("SESIdentityManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .send_mail(
                cast("str", self.Identity),
                Destination,
                Message,
                ReplyToAddresses=ReplyToAddresses,
                ReturnPath=ReturnPath,
                SourceArn=SourceArn,
                ReturnPathArn=ReturnPathArn,
                Tags=Tags,
                ConfigurationSetName=ConfigurationSetName,
            )
        )

    def send_raw_mail(
        self,
        RawMessage: SESRawMessage,
        Destinations: builtins.list[str] | None = None,
        FromArn: str | None = None,
        SourceArn: str | None = None,
        ReturnPathArn: str | None = None,
        Tags: builtins.list[SESMessageTag] | None = None,
        ConfigurationSetName: str | None = None,
    ) -> "str":
        """
        Send a raw email from this identity.

        Args:
            RawMessage: The raw email message itself. The message has to meet the
                following criteria:

        Keyword Args:
            Destinations: A list of destinations for the message, consisting of To:,
                CC:, and BCC: addresses.
            FromArn: This parameter is used only for sending authorization. It is the
                ARN of the identity that is associated
                with the sending authorization policy that permits you to specify a
                particular "From" address in the header of the
                raw email.
            SourceArn: This parameter is used only for sending authorization. It is the
                ARN of the identity that is associated
                with the sending authorization policy that permits you to send for the
                email address specified in the ``Source``
                parameter.
            ReturnPathArn: This parameter is used only for sending authorization. It is
                the ARN of the identity that is
                associated with the sending authorization policy that permits you to use
                the email address specified in the
                ``ReturnPath`` parameter.
            Tags: A list of tags, in the form of name/value pairs, to apply to an email
                that you send using ``SendRawEmail``.
                Tags correspond to characteristics of the email that you define, so that
                you can publish email sending events.
            ConfigurationSetName: The name of the configuration set to use when you send
                an email using ``SendRawEmail``.
        """
        return (
            cast("SESIdentityManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .send_raw_mail(
                cast("str", self.Identity),
                RawMessage,
                Destinations=Destinations,
                FromArn=FromArn,
                SourceArn=SourceArn,
                ReturnPathArn=ReturnPathArn,
                Tags=Tags,
                ConfigurationSetName=ConfigurationSetName,
            )
        )


class SESConfigurationSet(PrimaryBoto3Model):
    """
    The name of the configuration set.

    Configuration sets let you create groups of rules that you can apply to the emails
    you send using Amazon SES. For more information about using configuration sets, see
    `Using Amazon SES Configuration Sets <https://docs.aws.amazon.com/ses/latest/dg/using-configuration-sets.html>`_
    in the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/>`_.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = SESConfigurationSetManager

    ConfigurationSetName: str = Field(default=None, alias="Name")
    """
    The name of the configuration set.

    The name must meet the following requirements:
    """

    EventDestinations: "list[EventDestination] | None" = None
    """
    Event destinations configured for this configuration set.
    """

    TrackingOptions: "SESTrackingOptions | None" = None
    """
    Open and click tracking configuration for this set.
    """

    DeliveryOptions: "SESDeliveryOptions | None" = None
    """
    Delivery behavior associated with this configuration set.
    """

    ReputationOptions: "SESReputationOptions | None" = None
    """
    Reputation settings associated with this configuration set.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`ConfigurationSetName` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.ConfigurationSetName

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`ConfigurationSetName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.ConfigurationSetName
    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`ConfigurationSetName` attribute.
        """
        return hash(self.ConfigurationSetName)

class SESBulkEmailDestination(Boto3Model):
    """
    An array that contains one or more Destinations, as well as the tags and replacement
    data associated with each of those Destinations.
    """

    Destination: SESDestination
    """
    Represents the destination of the message, consisting of To:, CC:, and BCC: fields.
    """

    ReplacementTags: "builtins.list[SESMessageTag] | None" = Field(default_factory=list)
    """
    A list of tags, in the form of name/value pairs, to apply to an email that you send
    using ``SendBulkTemplatedEmail``.

    Tags correspond to characteristics of the email that you define, so that you can
    publish email sending events.
    """

    ReplacementTemplateData: "str | None" = None
    """
    A list of replacement values to apply to the template.

    This parameter is a JSON object, typically consisting of key- value pairs in which
    the keys correspond to replacement tags in the email template.
    """

class SESTemplate(PrimaryBoto3Model):
    """
    The content of the email, composed of a subject line and either an HTML part or a
    text-only part.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = SESTemplateManager

    TemplateName: str = Field(frozen=True)
    """
    The name of the template.

    You use this name when you send email using the ``SendTemplatedEmail`` or
    ``SendBulkTemplatedEmail`` operations.
    """

    SubjectPart: str = Field(default=None, frozen=True)
    """
    The subject line of the email.
    """
    TextPart: str = Field(default=None, frozen=True)
    """
    The email body that is visible to recipients whose email clients do not display HTML
    content.
    """
    HtmlPart: str = Field(default=None, frozen=True)
    """
    The HTML body of the email.
    """

    CreatedTimestamp: datetime | None = None
    """
    Creation time returned by list operations.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`TemplateName` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.TemplateName
    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`TemplateName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.TemplateName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`TemplateName` attribute.
        """
        return hash(self.TemplateName)

    def send_mail(
        self,
        Source: str,
        Destination: SESDestination,
        TemplateData: str,
        ReplyToAddresses: builtins.list[str] | None = None,
        ReturnPath: str | None = None,
        SourceArn: str | None = None,
        ReturnPathArn: str | None = None,
        Tags: builtins.list[SESMessageTag] | None = None,
        ConfigurationSetName: str | None = None,
    ) -> "str":
        """
        Send a templated email with this template.

        Args:
            Source: The email address that is sending the email. This email address must
                be either individually verified with
                Amazon SES, or from a domain that has been verified with Amazon SES. For
                information about verifying identities, see
                the `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html>`_.
            Destination: The destination for this email, composed of To:, CC:, and BCC:
                fields. A Destination can include up to
                50 recipients across these three fields.
            TemplateData: A list of replacement values to apply to the template. This
                parameter is a JSON object, typically
                consisting of key- value pairs in which the keys correspond to
                replacement tags in the email template.

        Keyword Args:
            ReplyToAddresses: The reply-to email address(es) for the message. If the
                recipient replies to the message, each
                reply-to address receives the reply.
            ReturnPath: The email address that bounces and complaints are forwarded to
                when feedback forwarding is enabled. If
                the message cannot be delivered to the recipient, then an error message
                is returned from the recipient's ISP; this
                message is forwarded to the email address specified by the
                ``ReturnPath`` parameter. The ``ReturnPath`` parameter is
                never overwritten. This email address must be either individually
                verified with Amazon SES, or from a domain that
                has been verified with Amazon SES.
            SourceArn: This parameter is used only for sending authorization. It is the
                ARN of the identity that is associated
                with the sending authorization policy that permits you to send for the
                email address specified in the ``Source``
                parameter.
            ReturnPathArn: This parameter is used only for sending authorization. It is
                the ARN of the identity that is
                associated with the sending authorization policy that permits you to use
                the email address specified in the
                ``ReturnPath`` parameter.
            Tags: A list of tags, in the form of name/value pairs, to apply to an email
                that you send using
                ``SendTemplatedEmail``. Tags correspond to characteristics of the email
                that you define, so that you can publish
                email sending events.
            ConfigurationSetName: The name of the configuration set to use when you send
                an email using ``SendTemplatedEmail``.
        """
        return (
            cast("SESTemplateManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .send_mail(
                Source,
                Destination,
                cast("str", self.TemplateName),
                TemplateData,
                ReplyToAddresses=ReplyToAddresses,
                ReturnPath=ReturnPath,
                SourceArn=SourceArn,
                ReturnPathArn=ReturnPathArn,
                Tags=Tags,
                ConfigurationSetName=ConfigurationSetName,
            )
        )

    def send_bulk_templated_mail(
        self,
        Source: str,
        Destinations: builtins.list[SESBulkEmailDestination],
        SourceArn: str | None = None,
        ReplyToAddresses: builtins.list[str] | None = None,
        ReturnPath: str | None = None,
        ReturnPathArn: str | None = None,
        ConfigurationSetName: str | None = None,
        DefaultTags: builtins.list[SESMessageTag] | None = None,
    ) -> "builtins.list[SESBulkEmailDestinationStatus]":
        """
        Send bulk templated email with this template.

        Args:
            Source: The email address that is sending the email. This email address must
                be either individually verified with
                Amazon SES, or from a domain that has been verified with Amazon SES. For
                information about verifying identities, see
                the `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html>`_.
            Destinations: One or more ``Destination`` objects. All of the recipients in
                a ``Destination`` receive the same
                version of the email. You can specify up to 50 ``Destination`` objects
                within a ``Destinations`` array.

        Keyword Args:
            SourceArn: This parameter is used only for sending authorization. It is the
                ARN of the identity that is associated
                with the sending authorization policy that permits you to send for the
                email address specified in the ``Source``
                parameter.
            ReplyToAddresses: The reply-to email address(es) for the message. If the
                recipient replies to the message, each
                reply-to address receives the reply.
            ReturnPath: The email address that bounces and complaints are forwarded to
                when feedback forwarding is enabled. If
                the message cannot be delivered to the recipient, then an error message
                is returned from the recipient's ISP; this
                message is forwarded to the email address specified by the
                ``ReturnPath`` parameter. The ``ReturnPath`` parameter is
                never overwritten. This email address must be either individually
                verified with Amazon SES, or from a domain that
                has been verified with Amazon SES.
            ReturnPathArn: This parameter is used only for sending authorization. It is
                the ARN of the identity that is
                associated with the sending authorization policy that permits you to use
                the email address specified in the
                ``ReturnPath`` parameter.
            ConfigurationSetName: The name of the configuration set to use when you send
                an email using
                ``SendBulkTemplatedEmail``.
            DefaultTags: A list of tags, in the form of name/value pairs, to apply to an
                email that you send to a destination
                using ``SendBulkTemplatedEmail``.
        """
        return (
            cast("SESTemplateManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .send_bulk_templated_mail(
                Source,
                cast("str", self.TemplateName),
                Destinations,
                SourceArn=SourceArn,
                ReplyToAddresses=ReplyToAddresses,
                ReturnPath=ReturnPath,
                ReturnPathArn=ReturnPathArn,
                ConfigurationSetName=ConfigurationSetName,
                DefaultTags=DefaultTags,
            )
        )


class SESCustomVerificationEmailTemplate(PrimaryBoto3Model):
    """
    Contains information about a custom verification email template.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = (
        SESCustomVerificationEmailTemplateManager
    )
    TemplateName: "str | None" = None
    """
    The name of the custom verification email template.
    """

    FromEmailAddress: "str | None" = None
    """
    The email address that the custom verification email is sent from.
    """

    TemplateSubject: "str | None" = None
    """
    The subject line of the custom verification email.
    """

    SuccessRedirectionURL: "str | None" = None
    """
    The URL that the recipient of the verification email is sent to if his or her
    address is successfully verified.
    """

    FailureRedirectionURL: "str | None" = None
    """
    The URL that the recipient of the verification email is sent to if his or her
    address is not successfully verified.
    """

    TemplateContent: str | None = None
    """
    Email body content used for verification messages.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`TemplateName` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.TemplateName

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`TemplateName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.TemplateName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`TemplateName` attribute.
        """
        return hash(self.TemplateName)

    def send_verification_mail(
        self, EmailAddress: str, ConfigurationSetName: str | None = None
    ) -> "str":
        """
        Send a custom verification email with this template.

        Args:
            EmailAddress: The email address to verify.

        Keyword Args:
            ConfigurationSetName: Name of a configuration set to use when sending the
                verification email.
        """
        return (
            cast("SESCustomVerificationEmailTemplateManager", self.objects)  # type: ignore[attr-defined]
            .using(self.session)
            .send_verification_mail(
                EmailAddress,
                cast("str", self.TemplateName),
                ConfigurationSetName=ConfigurationSetName,
            )
        )


class ReceiptIpFilter(Boto3Model):
    """
    A receipt IP address filter enables you to specify whether to accept or reject mail
    originating from an IP address or range of IP addresses.

    For information about setting up IP address filters, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-ip-filtering-console-walkthrough.html>`_.
    """

    Policy: Literal["Block", "Allow"]
    """
    Indicates whether to block or allow incoming mail from the specified IP addresses.
    """

    Cidr: str
    """
    A single IP address or a range of IP addresses to block or allow, specified in
    Classless Inter-Domain Routing (CIDR) notation.

    An example of a single email address is 10.0.0.1. An example of a range of IP
    addresses is 10.0.0.1/24. For more information about CIDR notation, see
    `RFC 2317 <https://tools.ietf.org/html/rfc2317>`_.
    """


class SESReceiptFilter(PrimaryBoto3Model):
    """
    A receipt IP address filter enables you to specify whether to accept or reject mail
    originating from an IP address or range of IP addresses.

    For information about setting up IP address filters, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-ip-filtering-console-walkthrough.html>`_.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = SESReceiptFilterManager

    FilterName: str = Field(default=None, alias="Name")
    """
    The name of the IP address filter.

    The name must meet the following requirements:
    """

    IpFilter: ReceiptIpFilter = Field(frozen=True)
    """
    A structure that provides the IP addresses to block or allow, and whether to block
    or allow incoming mail from them.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`FilterName` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.FilterName

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`FilterName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.FilterName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`FilterName` attribute.
        """
        return hash(self.FilterName)


class SESReceiptRuleSet(PrimaryBoto3Model):
    """
    Information about a receipt rule set.

    A receipt rule set is a collection of rules that specify what Amazon SES should do
    with mail it receives on behalf of your account's verified domains.

    For information about setting up receipt rule sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-concepts.html#receiving-email-concepts-rules>`_.
    """

    manager_class: ClassVar[ModelType[Boto3ModelManager]] = SESReceiptRuleSetManager

    ReceiptRuleSetName: str = Field(default=None, alias="Name")
    """
    The name of the receipt rule set.

    The name must meet the following requirements:
    """

    CreatedTimestamp: datetime = Field(default=None, frozen=True)
    """
    The date and time the receipt rule set was created.
    """

    Rules: "list[ReceiptRule] | None" = None
    """
    Receipt rules contained in this rule set.
    """

    @property
    def pk(self) -> str | None:
        """
        Return the primary key of the model.

        This is the value of the :py:attr:`ReceiptRuleSetName` attribute.

        Returns:
            The primary key of the model instance.
        """
        return self.ReceiptRuleSetName

    @property
    def name(self) -> str | None:
        """
        Return the name of the model.

        This is the value of the :py:attr:`ReceiptRuleSetName` attribute.

        Returns:
            The name of the model instance.
        """
        return self.ReceiptRuleSetName

    def __hash__(self) -> int:
        """
        Return the hash of the model.

        This is the value of the
        :py:attr:`ReceiptRuleSetName` attribute.
        """
        return hash(self.ReceiptRuleSetName)


class SESBulkEmailDestinationStatus(Boto3Model):
    """
    An object that contains the response from the ``SendBulkTemplatedEmail`` operation.
    """

    Status: "Literal['Success', 'MessageRejected', 'MailFromDomainNotVerified', 'ConfigurationSetDoesNotExist', 'TemplateDoesNotExist', 'AccountSuspended', 'AccountThrottled', 'AccountDailyQuotaExceeded', 'InvalidSendingPoolName', 'AccountSendingPaused', 'ConfigurationSetSendingPaused', 'InvalidParameterValue', 'TransientFailure', 'Failed'] | None" = None
    """
    The status of a message sent using the ``SendBulkTemplatedEmail`` operation.
    """

    Error: "str | None" = None
    """
    A description of an error that prevented a message being sent using the
    ``SendBulkTemplatedEmail`` operation.
    """

    MessageId: "str | None" = None
    """
    The unique message identifier returned from the ``SendBulkTemplatedEmail``
    operation.
    """

class SESKinesisFirehoseDestination(Boto3Model):
    """
    Contains the delivery stream ARN and the IAM role ARN associated with an Amazon
    Kinesis Firehose event destination.

    Event destinations, such as Amazon Kinesis Firehose, are associated with
    configuration sets, which enable you to publish email sending events. For
    information about using configuration sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html>`_.
    """

    IAMRoleARN: str
    """
    The ARN of the IAM role under which Amazon SES publishes email sending events to the
    Amazon Kinesis Firehose stream.
    """
    DeliveryStreamARN: str
    """
    The ARN of the Amazon Kinesis Firehose stream that email sending events should be
    published to.
    """


class CloudWatchDimensionConfiguration(Boto3Model):
    """
    Contains the dimension configuration to use when you publish email sending events to
    Amazon CloudWatch.

    For information about publishing email sending events to Amazon CloudWatch, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html>`_.
    """

    DimensionName: str
    """
    The name of an Amazon CloudWatch dimension associated with an email sending metric.

    The name must meet the following
    requirements:
    """

    DimensionValueSource: Literal["messageTag", "emailHeader", "linkTag"]
    """
    The place where Amazon SES finds the value of a dimension to publish to Amazon
    CloudWatch.

    To use the message tags that you specify using an ``X-SES-MESSAGE-TAGS`` header or a
    parameter to the ``SendEmail``/``SendRawEmail`` API, specify ``messageTag``. To use
    your own email headers, specify ``emailHeader``. To put a custom tag on any link
    included in your email, specify ``linkTag``.
    """

    DefaultDimensionValue: str
    """
    The default value of the dimension that is published to Amazon CloudWatch if you do
    not provide the value of the dimension when you send an email.

    The default value must meet the following requirements:
    """


class SESCloudWatchDestination(Boto3Model):
    """
    Contains information associated with an Amazon CloudWatch event destination to which
    email sending events are published.

    Event destinations, such as Amazon CloudWatch, are associated with configuration
    sets, which enable you to publish email sending events. For information about using
    configuration sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html>`_.
    """

    DimensionConfigurations: "builtins.list[CloudWatchDimensionConfiguration]"
    """
    A list of dimensions upon which to categorize your emails when you publish email
    sending events to Amazon CloudWatch.
    """


class SESSNSDestination(Boto3Model):
    """
    Contains the topic ARN associated with an Amazon Simple Notification Service (Amazon
    SNS) event destination.

    Event destinations, such as Amazon SNS, are associated with configuration sets,
    which enable you to publish email sending events. For information about using
    configuration sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html>`_.
    """

    TopicARN: str
    """
    The ARN of the Amazon SNS topic for email sending events.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_ Amazon SNS operation.
    """
class EventDestination(Boto3Model):
    """
    Contains information about an event destination.

    When you create or update an event destination, you must provide one, and only one,
    destination. The destination can be Amazon CloudWatch, Amazon Kinesis Firehose or
    Amazon Simple Notification Service (Amazon SNS).

    Event destinations are associated with configuration sets, which enable you to
    publish email sending events to Amazon CloudWatch, Amazon Kinesis Firehose, or
    Amazon Simple Notification Service (Amazon SNS). For information about using
    configuration sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-
    activity.html>`_.
    """

    EventDestinationName: str = Field(default=None, alias="Name")
    """
    The name of the event destination.

    The name must meet the following requirements:
    """
    Enabled: "bool | None" = None
    """
    Sets whether Amazon SES publishes events to this destination when you send an email
    with the associated configuration set.

    Set to ``true`` to enable publishing to this destination; set to ``false`` to
    prevent publishing to this destination. The default value is ``false``.
    """
    MatchingEventTypes: "builtins.list[Literal['send', 'reject', 'bounce', 'complaint', 'delivery', 'open', 'click', 'renderingFailure']]"
    """
    The type of email sending events to publish to the event destination.
    """

    KinesisFirehoseDestination: "SESKinesisFirehoseDestination | None" = None
    """
    An object that contains the delivery stream ARN and the IAM role ARN associated with
    an Amazon Kinesis Firehose event destination.
    """

    CloudWatchDestination: "SESCloudWatchDestination | None" = None
    """
    An object that contains the names, default values, and sources of the dimensions
    associated with an Amazon CloudWatch event destination.
    """

    SNSDestination: "SESSNSDestination | None" = None
    """
    An object that contains the topic ARN associated with an Amazon Simple Notification
    Service (Amazon SNS) event destination.
    """
class SESTrackingOptions(Boto3Model):
    """
    A domain that is used to redirect email recipients to an Amazon SES-operated domain.

    This domain captures open and click events generated by Amazon SES emails.

    For more information, see
    `Configuring Custom Domains to Handle Open and Click Tracking <https://docs.aws.amazon.com/ses/latest/dg/configure-custom-open-click-domains.html>`_
    in the *Amazon SES
    Developer Guide*.
    """

    CustomRedirectDomain: "str | None" = None
    """
    The custom subdomain that is used to redirect email recipients to the Amazon SES
    event tracking domain.
    """

class SESDeliveryOptions(Boto3Model):
    """
    Specifies whether messages that use the configuration set are required to use
    Transport Layer Security (TLS).
    """

    TlsPolicy: "Literal['Require', 'Optional'] | None" = None
    """
    Specifies whether messages that use the configuration set are required to use
    Transport Layer Security (TLS).

    If the value is ``Require``, messages are only delivered if a TLS connection can be
    established. If the value is ``Optional``, messages can be delivered in plain text
    if a TLS connection can't be established.
    """

class SESReputationOptions(Boto3Model):
    """
    Contains information about the reputation settings for a configuration set.
    """

    SendingEnabled: "bool | None" = None
    """
    Describes whether email sending is enabled or disabled for the configuration set.

    If the value is ``true``, then Amazon SES sends emails that use the configuration
    set. If the value is ``false``, Amazon SES does not send emails that use the
    configuration set. The default value is ``true``. You can change this setting using
    UpdateConfigurationSetSendingEnabled.
    """

    ReputationMetricsEnabled: "bool | None" = None
    """
    Describes whether or not Amazon SES publishes reputation metrics for the
    configuration set, such as bounce and complaint rates, to Amazon CloudWatch.
    """

    LastFreshStart: "datetime | None" = None
    """
    The date and time at which the reputation metrics for the configuration set were
    last reset.

    Resetting these metrics is known as a *fresh start*.
    """

class SESS3Action(Boto3Model):
    """
    When included in a receipt rule, this action saves the received message to an Amazon
    Simple Storage Service (Amazon S3) bucket and, optionally, publishes a notification
    to Amazon Simple Notification Service (Amazon SNS).

    To enable Amazon SES to write emails to your Amazon S3 bucket, use an Amazon Web
    Services KMS key to encrypt your emails, or publish to an Amazon SNS topic of
    another account, Amazon SES must have permission to access those resources. For
    information about granting permissions, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-permissions.html>`_.

    When you save your emails to an Amazon S3 bucket, the maximum email size (including
    headers) is 40 MB. Emails larger than that bounces.

    For information about specifying Amazon S3 actions in receipt rules, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-s3.html>`_.
    """

    TopicArn: "str | None" = None
    """
    The ARN of the Amazon SNS topic to notify when the message is saved to the Amazon S3
    bucket.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_
    operation in Amazon SNS.
    """

    BucketName: str
    """
    The name of the Amazon S3 bucket for incoming email.
    """

    ObjectKeyPrefix: "str | None" = None
    """
    The key prefix of the Amazon S3 bucket.

    The key prefix is similar to a directory name that enables you to store similar data
    under the same directory in a bucket.
    """

    KmsKeyArn: "str | None" = None
    """
    The customer managed key that Amazon SES should use to encrypt your emails before
    saving them to the Amazon S3 bucket.

    You can use the Amazon Web Services managed key or a customer managed key that you
    created in Amazon Web Services KMS as
    follows:
    """
    IamRoleArn: "str | None" = None
    """
    The ARN of the IAM role to be used by Amazon Simple Email Service while writing to
    the Amazon S3 bucket, optionally encrypting your mail via the provided customer
    managed key, and publishing to the Amazon SNS topic.

    This role should
    have access to the following APIs:
    """
class SESBounceAction(Boto3Model):
    """
    When included in a receipt rule, this action rejects the received email by returning
    a bounce response to the sender and, optionally, publishes a notification to Amazon
    Simple Notification Service (Amazon SNS).

    For information about sending a bounce message in response to a received email, see
    the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-bounce.html>`_.
    """

    TopicArn: "str | None" = None
    """
    The Amazon Resource Name (ARN) of the Amazon SNS topic to notify when the bounce
    action is taken.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_
    operation in Amazon
    SNS.
    """

    SmtpReplyCode: str
    """
The SMTP reply code, as defined by `RFC 5321 <https://tools.ietf.org/html/rfc5321>`_.
    """

    StatusCode: "str | None" = None
    """
The SMTP enhanced status code, as defined by `RFC 3463 <https://tools.ietf.org/html/rfc3463>`_.
    """

    Message: str
    """
    Human-readable text to include in the bounce message.
    """

    Sender: str
    """
    The email address of the sender of the bounced email.

    This is the address from which the bounce message is sent.
    """

class SESWorkmailAction(Boto3Model):
    """
    When included in a receipt rule, this action calls Amazon WorkMail and, optionally,
    publishes a notification to Amazon Simple Notification Service (Amazon SNS). It
    usually isn't necessary to set this up manually, because Amazon WorkMail adds the
    rule automatically during its setup procedure.

    For information using a receipt rule to call Amazon WorkMail, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-workmail.html>`_.
    """

    TopicArn: "str | None" = None
    """
    The Amazon Resource Name (ARN) of the Amazon SNS topic to notify when the WorkMail
    action is called.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_
    operation in
    Amazon SNS.
    """

    OrganizationArn: str
    """
    The Amazon Resource Name (ARN) of the Amazon WorkMail organization.

    Amazon WorkMail ARNs use the following format:
    """

class SESLambdaAction(Boto3Model):
    """
    When included in a receipt rule, this action calls an Amazon Web Services Lambda
    function and, optionally, publishes a notification to Amazon Simple Notification
    Service (Amazon SNS).

    To enable Amazon SES to call your Amazon Web Services Lambda function or to publish
    to an Amazon SNS topic of another account, Amazon SES must have permission to access
    those resources. For information about giving permissions, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-permissions.html>`_.

    For information about using Amazon Web Services Lambda actions in receipt rules, see
    the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-lambda.html>`_.
    """

    TopicArn: "str | None" = None
    """
    The Amazon Resource Name (ARN) of the Amazon SNS topic to notify when the Lambda
    action is executed.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_
    operation in
    Amazon SNS.
    """

    FunctionArn: str
    """
    The Amazon Resource Name (ARN) of the Amazon Web Services Lambda function.

    An example of an Amazon Web Services Lambda function ARN is
    ``arn:aws:lambda:us-west-2:account-id:function:MyFunction``. For more information
    about Amazon Web
    Services Lambda, see the `Amazon Web Services Lambda Developer
    Guide <https://docs.aws.amazon.com/lambda/latest/dg/welcome.html>`_.
    """
    InvocationType: "Literal['Event', 'RequestResponse'] | None" = None
    """
    The invocation type of the Amazon Web Services Lambda function.

    An invocation type of ``RequestResponse`` means that the execution of the function
    immediately results in a response, and a value of ``Event`` means that the function
    is invoked asynchronously. The default value is ``Event``. For information about
    Amazon Web Services Lambda invocation types, see the
    `Amazon Web Services Lambda Developer Guide <https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html>`_.
    """

class SESStopAction(Boto3Model):
    """
    When included in a receipt rule, this action terminates the evaluation of the
    receipt rule set and, optionally, publishes a notification to Amazon Simple
    Notification Service (Amazon SNS).

    For information about setting a stop action in a receipt rule, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-stop.html>`_.
    """

    Scope: Literal["RuleSet"]
    """
    The scope of the StopAction.

    The only acceptable value is ``RuleSet``.
    """

    TopicArn: "str | None" = None
    """
    The Amazon Resource Name (ARN) of the Amazon SNS topic to notify when the stop
    action is taken.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_
    Amazon SNS operation.
    """

class SESAddHeaderAction(Boto3Model):
    """
    When included in a receipt rule, this action adds a header to the received email.

    For information about adding a header using a receipt rule, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-add-header.html>`_.
    """

    HeaderName: str
    """
    The name of the header to add to the incoming message.

    The name must contain at least one character, and can contain up to 50 characters.
    It consists of alphanumeric (a-z, A-Z, 0-9) characters and dashes.
    """

    HeaderValue: str
    """
    The content to include in the header.

    This value can contain up to 2048 characters. It can't contain newline (``n``) or
    carriage return (``r``) characters.
    """
class SESSNSAction(Boto3Model):
    """
    When included in a receipt rule, this action publishes a notification to Amazon
    Simple Notification Service (Amazon SNS). This action includes a complete copy of
    the email content in the Amazon SNS notifications. Amazon SNS notifications for all
    other actions simply provide information about the email. They do not include the
    email content itself.

    If you own the Amazon SNS topic, you don't need to do anything to give Amazon SES
    permission to publish emails to it. However, if you don't own the Amazon SNS topic,
    you need to attach a policy to the topic to give Amazon SES permissions to access
    it. For information about giving permissions, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-permissions.html>`_.

    You can only publish emails that are 150 KB or less (including the header) to Amazon
    SNS. Larger emails bounce. If you anticipate emails larger than 150 KB, use the S3
    action instead.

    For information about using a receipt rule to publish an Amazon SNS notification,
    see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action-sns.html>`_.
    """

    TopicArn: str
    """
    The Amazon Resource Name (ARN) of the Amazon SNS topic to notify.

    You can find the ARN of a topic by using the
    `ListTopics <https://docs.aws.amazon.com/sns/latest/api/API_ListTopics.html>`_ operation in Amazon SNS.
    """

    Encoding: "Literal['UTF-8', 'Base64'] | None" = None
    """
    The encoding to use for the email within the Amazon SNS notification.

    UTF-8 is easier to use, but may not preserve all special characters when a message
    was encoded with a different encoding format. Base64 preserves all special
    characters. The default value is UTF-8.
    """

class SESConnectAction(Boto3Model):
    """
    When included in a receipt rule, this action parses the received message and starts
    an email contact in Amazon Connect on your behalf.

    When you receive emails, the maximum email size (including headers) is 40 MB.
    Additionally, emails may only have up to 10 attachments. Emails larger than 40 MB or
    with more than 10 attachments will be bounced.

    We recommend that you configure this action via Amazon Connect.
    """

    InstanceARN: str
    """
    The Amazon Resource Name (ARN) for the Amazon Connect instance that Amazon SES
    integrates with for starting email contacts.
    """

    IAMRoleARN: str
    """
    The Amazon Resource Name (ARN) of the IAM role to be used by Amazon Simple Email
    Service while starting email contacts to the Amazon Connect instance.

    This role should have permission to invoke ``connect:StartEmailContact`` for the
    given Amazon Connect instance.
    """


class ReceiptAction(Boto3Model):
    """
    An action that Amazon SES can take when it receives an email on behalf of one or
    more email addresses or domains that you own. An instance of this data type can
    represent only one action.

    For information about setting up receipt rules, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-receipt-rules-console-walkthrough.html>`_.
    """

    S3Action: "SESS3Action | None" = None
    """
    Saves the received message to an Amazon Simple Storage Service (Amazon S3) bucket
    and, optionally, publishes a notification to Amazon SNS.
    """

    BounceAction: "SESBounceAction | None" = None
    """
    Rejects the received email by returning a bounce response to the sender and,
    optionally, publishes a notification to Amazon Simple Notification Service (Amazon
    SNS).
    """

    WorkmailAction: "SESWorkmailAction | None" = None
    """
    Calls Amazon WorkMail and, optionally, publishes a notification to Amazon Amazon
    SNS.
    """

    LambdaAction: "SESLambdaAction | None" = None
    """
    Calls an Amazon Web Services Lambda function, and optionally, publishes a
    notification to Amazon SNS.
    """
    StopAction: "SESStopAction | None" = None
    """
    Terminates the evaluation of the receipt rule set and optionally publishes a
    notification to Amazon SNS.
    """

    AddHeaderAction: "SESAddHeaderAction | None" = None
    """
    Adds a header to the received email.
    """
    SNSAction: "SESSNSAction | None" = None
    """
    Publishes the email content within a notification to Amazon SNS.
    """
    ConnectAction: "SESConnectAction | None" = None
    """
    Parses the received message and starts an email contact in Amazon Connect on your
    behalf.
    """

class ReceiptRule(Boto3Model):
    """
    Receipt rules enable you to specify which actions Amazon SES should take when it
    receives mail on behalf of one or more email addresses or domains that you own.

    Each receipt rule defines a set of email addresses or domains that it applies to. If
    the email addresses or domains match at least one recipient address of the message,
    Amazon SES executes all of the receipt rule's actions on the message.

    For information about setting up receipt rules, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/receiving-email-receipt-rules-console-walkthrough.html>`_.
    """

    ReceiptRuleName: str = Field(default=None, alias="Name")
    """
    The name of the receipt rule.

    The name must meet the following requirements:
    """

    Enabled: "bool | None" = None
    """
    If ``true``, the receipt rule is active.

    The default value is ``false``.
    """

    TlsPolicy: "Literal['Require', 'Optional'] | None" = None
    """
    Specifies whether Amazon SES should require that incoming email is delivered over a
    connection encrypted with Transport Layer Security (TLS).

    If this parameter is set to ``Require``, Amazon SES bounces emails that are not
    received over TLS. The default is ``Optional``.
    """

    Recipients: "builtins.list[str] | None" = Field(default_factory=list)
    """
    The recipient domains and email addresses that the receipt rule applies to.

    If this field is not specified, this rule matches all recipients on all verified
    domains.
    """

    Actions: "builtins.list[ReceiptAction] | None" = Field(default_factory=list)
    """
    An ordered list of actions to perform on messages that match at least one of the
    recipient email addresses or domains specified in the receipt rule.
    """

    ScanEnabled: "bool | None" = None
    """
    If ``true``, then messages that this receipt rule applies to are scanned for spam
    and viruses.

    The default value is
    ``false``.
    """

# =======================
# Request/Response Models
# =======================


class ListIdentitiesResponse(Boto3Model):
    """
    A list of all identities that you have attempted to verify under your Amazon Web
    Services account, regardless of verification status.
    """

    Identities: "builtins.list[str]"
    """
    A list of identities.
    """

    NextToken: "str | None" = None
    """
    The token used for pagination.
    """

class SESListConfigurationSetsResponse(Boto3Model):
    """
    A list of configuration sets associated with your Amazon Web Services account.

    Configuration sets enable you to publish email sending events. For information about
    using configuration sets, see the
    `Amazon SES Developer Guide <https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html>`_.
    """

    ConfigurationSets: "builtins.list[SESConfigurationSet] | None" = Field(
        default_factory=list
    )
    """
    A list of configuration sets.
    """

    NextToken: "str | None" = None
    """
    A token indicating that there are additional configuration sets available to be
    listed.

    Pass this token to successive calls of ``ListConfigurationSets``.
    """

class SESDeleteConfigurationSetResponse(Boto3Model):
    """
    An empty element returned on a successful request.
    """


class GetTemplateResponse(Boto3Model):
    Template: "SESTemplate | None" = None
    """
    The content of the email, composed of a subject line and either an HTML part or a
    text-only part.
    """

class TemplateMetadata(Boto3Model):
    """
    Contains information about an email template.
    """

    Name: "str | None" = None
    """
    The name of the template.
    """

    CreatedTimestamp: "datetime | None" = None
    """
    The time and date the template was created.
    """

class ListTemplatesResponse(Boto3Model):
    TemplatesMetadata: "builtins.list[TemplateMetadata] | None" = Field(
        default_factory=list
    )
    """
    An array the contains the name and creation time stamp for each template in your
    Amazon SES account.
    """

    NextToken: "str | None" = None
    """
    A token indicating that there are additional email templates available to be listed.

    Pass this token to a subsequent call to ``ListTemplates`` to retrieve the next set
    of email templates within your page size.
    """
class DeleteTemplateResponse(Boto3Model):
    pass


class GetCustomVerificationEmailTemplateResponse(Boto3Model):
    """
    The content of the custom verification email template.
    """

    TemplateName: "str | None" = None
    """
    The name of the custom verification email template.
    """

    FromEmailAddress: "str | None" = None
    """
    The email address that the custom verification email is sent from.
    """

    TemplateSubject: "str | None" = None
    """
    The subject line of the custom verification email.
    """

    TemplateContent: "str | None" = None
    """
    The content of the custom verification email.
    """
    SuccessRedirectionURL: "str | None" = None
    """
    The URL that the recipient of the verification email is sent to if his or her
    address is successfully verified.
    """

    FailureRedirectionURL: "str | None" = None
    """
    The URL that the recipient of the verification email is sent to if his or her
    address is not successfully verified.
    """

class ListCustomVerificationEmailTemplatesResponse(Boto3Model):
    """
    A paginated list of custom verification email templates.
    """

    CustomVerificationEmailTemplates: "builtins.list[SESCustomVerificationEmailTemplate] | None" = Field(
        default_factory=list
    )
    """
    A list of the custom verification email templates that exist in your account.
    """

    NextToken: "str | None" = None
    """
    A token indicating that there are additional custom verification email templates
    available to be listed.

    Pass this token to a subsequent call to ``ListTemplates`` to retrieve the next 50
    custom verification email templates.
    """
class ListReceiptFiltersResponse(Boto3Model):
    """
    A list of IP address filters that exist under your Amazon Web Services account.
    """

    Filters: "builtins.list[SESReceiptFilter] | None" = Field(default_factory=list)
    """
    A list of IP address filter data structures, which each consist of a name, an IP
    address range, and whether to allow or block mail from it.
    """

class DeleteReceiptFilterResponse(Boto3Model):
    """
    An empty element returned on a successful request.
    """


class ListReceiptRuleSetsResponse(Boto3Model):
    """
    A list of receipt rule sets that exist under your Amazon Web Services account.
    """

    RuleSets: "builtins.list[SESReceiptRuleSet] | None" = Field(default_factory=list)
    """
    The metadata for the currently active receipt rule set.

    The metadata consists of the rule set name and the timestamp of when the rule set
    was created.
    """

    NextToken: "str | None" = None
    """
    A token indicating that there are additional receipt rule sets available to be
    listed.

    Pass this token to successive calls of ``ListReceiptRuleSets`` to retrieve up to 100
    receipt rule sets at a time.
    """

class DeleteReceiptRuleSetResponse(Boto3Model):
    """
    An empty element returned on a successful request.
    """
